### ISSUE TITLE
[dask-on-ray] ValueError on read-only memory

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#10124]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 0.9dev

I was trying out the new Ray backend plugin for Dask and ran into a read-only error. Looks like the Dask code tries to write in-place, but Ray doesn't allow it since objects are immutable.

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
```
import ray
import dask
import dask.dataframe as dd
import pandas as pd
import numpy as np
from ray.experimental.dask import ray_dask_get

import time

N_ROWS = 1000
N_PARTITIONS = 100

ray.init()

df = dd.from_pandas(pd.DataFrame(np.random.randn(N_ROWS, 2), columns=['a', 'b']), npartitions=N_PARTITIONS)
start = time.time()
print(df.groupby('b').a.sum().compute(scheduler=ray_dask_get))
end = time.time()
print("ray", end - start)
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by stephanie-wang** [comment]
cc @clarkzinzow, do you have any ideas? Also cc @ericl.

**Comment by clarkzinzow** [comment]
@stephanie-wang Just ran the reproduction script and it worked for me off commit [7ffb37f711f0045f1d1199db139e31e58fcbbe00](https://github.com/ray-project/ray/commit/7ffb37f711f0045f1d1199db139e31e58fcbbe00). Dask collections generally aren't allow to mutate in place, that shouldn't even be possible to express in a Dask graph, so I'm wondering what you're running into here... 🤔

**Comment by ericl** [comment]
```
Traceback (most recent call last):
  File "d.py", line 18, in <module>
    print(df.groupby('b').a.sum().compute(scheduler=ray_dask_get))
  File "/usr/local/lib/python3.6/dist-packages/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dask/base.py", line 447, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/eric/Desktop/ray/python/ray/experimental/dask/scheduler.py", line 92, in ray_dask_get
    result = ray_get_unpack(object_refs)
  File "/home/eric/Desktop/ray/python/ray/experimental/dask/scheduler.py", line 257, in ray_get_unpack
    computed_result = ray.get(object_refs)
  File "/home/eric/Desktop/ray/python/ray/worker.py", line 1552, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::ray.experimental.dask.scheduler.dask_task_wrapper() (pid=22464, ip=192.168.5.121)
  File "python/ray/_raylet.pyx", line 437, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
ray.exceptions.RayTaskError: ray::ray.experimental.dask.scheduler.dask_task_wrapper() (pid=22473, ip=192.168.5.121)
  File "python/ray/_raylet.pyx", line 437, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
ray.exceptions.RayTaskError: ray::ray.experimental.dask.scheduler.dask_task_wrapper() (pid=22469, ip=192.168.5.121)
  File "python/ray/_raylet.pyx", line 437, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
ray.exceptions.RayTaskError: ray::ray.experimental.dask.scheduler.dask_task_wrapper() (pid=22473, ip=192.168.5.121)
  File "python/ray/_raylet.pyx", line 474, in ray._raylet.execute_task
  File "/home/eric/Desktop/ray/python/ray/experimental/dask/scheduler.py", line 233, in dask_task_wrapper
    return func(*actual_args)
  File "/usr/local/lib/python3.6/dist-packages/dask/utils.py", line 31, in apply
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dask/dataframe/groupby.py", line 295, in _apply_chunk
    return func(g[columns], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dask/utils.py", line 895, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/groupby/groupby.py", line 1372, in f
    return self._cython_agg_general(alias, alt=npfunc, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/groupby/groupby.py", line 891, in _cython_agg_general
    obj._values, how, min_count=min_count
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/groupby/ops.py", line 587, in aggregate
    "aggregate", values, how, axis, min_count=min_count
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/groupby/ops.py", line 530, in _cython_operation
    result, counts, values, codes, func, is_datetimelike, min_count
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/groupby/ops.py", line 608, in _aggregate
    agg_func(result, counts, values, comp_ids, min_count)
  File "pandas/_libs/groupby.pyx", line 453, in pandas._libs.groupby._group_add
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
```

I can reproduce, I believe it's due to some argument being passed to the task wrapper that is presented as a readonly Ray object. It's probably specific to particular dask/pandas/numpy versions.

**Comment by clarkzinzow** [comment]
Do you mind giving your versions of Numpy, Dask and Pandas? I'm on Python 3.7.5 and:
```
clark@clark-dev:(ws)/ray $ pip freeze | rg "numpy|dask|pandas"
dask==2.20.0
numpy==1.18.1
pandas==0.25.3
```

**Comment by clarkzinzow** [comment]
Ah thanks for the trace back @ericl!

**Comment by ericl** [comment]
dask==2.22.0
numpy==1.17.1
numpy-stl==2.10.1
pandas==0.24.2

**Comment by clarkzinzow** [comment]
It looks like this is a recurring Pandas bug, most recent manifestation: https://github.com/pandas-dev/pandas/issues/31710.

**Comment by clarkzinzow** [comment]
Also [this](https://github.com/pandas-dev/pandas/issues/23276). It looks like the older bug was fixed for [0.24+](https://github.com/pandas-dev/pandas/commit/dcbf8b5118b4a079899a7bc14e4175eeb75368fb), and the more recent bug was fixed for [1.1+](https://github.com/pandas-dev/pandas/commit/5351732faf4b7186628579709439e1b29494a560).

**Comment by ericl** [comment]
Hmm I still see the issue for 1.1.0. Unless pandas has fixed itself to handle read-only arrays properly, we might have to add defensive copies for all numpy arrays passed as arguments to tasks.

dask==2.22.0
numpy==1.17.1
numpy-stl==2.10.1
pandas==1.1.0

**Comment by ericl** [comment]
@stephanie-wang as a workaround you can try this patch:
```
diff --git a/python/ray/experimental/dask/scheduler.py b/python/ray/experimental/dask/scheduler.py
index b15164525..c738c96c8 100644
--- a/python/ray/experimental/dask/scheduler.py
+++ b/python/ray/experimental/dask/scheduler.py
@@ -1,4 +1,5 @@
 import atexit
+import copy
 from collections import defaultdict
 from multiprocessing.pool import ThreadPool
 import threading
@@ -229,6 +230,7 @@ def dask_task_wrapper(func, repack, *args):
     repacked_args, repacked_deps = repack(args)
     # Recursively execute Dask-inlined tasks.
     actual_args = [_execute_task(a, repacked_deps) for a in repacked_args]
+    actual_args = copy.deepcopy(actual_args)
     # Execute the actual underlying Dask task.
     return func(*actual_args)
```

**Comment by clarkzinzow** [comment]
Upgrading to most recent Dask still works, upgrading Pandas breaks it. I'm guessing that this is another case in which Pandas isn't handling read-only arrays properly.

>we might have to add defensive copies for all numpy arrays passed as arguments to tasks.

That seems terribly expensive, but until Pandas fixes this, that might be required. Although I'm pretty sure that this issue is exclusive to dataframes, so we'd only have to copy Pandas dataframe arguments; we've hit most of the NumPy surface with the Dask-Ray scheduler and have never hit this error.

**Comment by clarkzinzow** [comment]
For this particular case, I think that we just need to add `const` [here](https://github.com/pandas-dev/pandas/blob/a3f5c6a5a3f05edc1c56ab8051f28c4cf322c45c/pandas/_libs/groupby.pyx#L475) to get Cython to accept read-only arrays. And if that's the case, `const` should probably be added to all of the other groupby functions in that module.

**Comment by clarkzinzow** [comment]
And to do that, we'll have to wait for const fused type memory views to be released in Cython.

- [Issue](https://github.com/cython/cython/issues/1772)
- [PR](https://github.com/cython/cython/pull/3118) adding support

**Comment by ericl** [comment]
Hmm yeah, if we insert a copy only for pandas dataframes, that doesn't seem so bad (not sure if the copy will add that much overhead in the first place). We can also make it a config flag.

**Comment by clarkzinzow** [comment]
I tested it out with `const float64_t[:, :]` and that fixes it. Building Pandas from source takes a good while.

I don't think we'll be seeing const fused type memory views in Cython 0.x anytime soon, so that nature of a fix won't be available in Pandas anytime soon.

**Comment by clarkzinzow** [comment]
Note that this particular instance of this issue was fixed in Pandas 1.1.2:

- [Issue](https://github.com/pandas-dev/pandas/issues/36014)
- [PR](https://github.com/pandas-dev/pandas/pull/36061)
- [Release notes](https://pandas.pydata.org/pandas-docs/version/1.2.0/whatsnew/v1.1.2.html)

**Comment by cszhu** [comment]
Hello! This P2 issue has seen no activity in at least 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
