### ISSUE TITLE
Actors don't seem to recover when using ray.wait()

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1036]
The following script can be used to reproduce the issue:

1) Set up a ray cluster with multiple nodes
2) Run the script (with the cluster redis address). The script will submit simple actor tasks at a rate of 100 tasks/s. It then prints out the cumulative number of tasks submitted, completed, pending. It also prints out tasks from which `ray.wait()` returns multiple times (duplicated? -- not sure what's going on there). 
3) When the throughput stabilizes, kill a node manually via e.g. `ray.stop()`.
4) Observe that some tasks remain in `pending` state forever. I've also seen error messages printed out on the driver stdout as well.

I've also tried this with non-actor tasks and saw some tasks that hung, though not as many.

```python
import time
import numpy as np
import ray
import random
import threading


@ray.remote(checkpoint_interval=10)
class Counter(object):
    def __init__(self, y):
        self.x = y

    def inc(self, y):
        time.sleep(0.0)
        self.x += y
        return self.x


def setup_actors(num_actors):
    counters = [Counter.remote(1) for _ in range(num_actors)]
    return counters


if __name__ == '__main__':
    address_info = ray.init(redis_address="172.30.1.119:6379")
    pending = []
    counters = setup_actors(200)
    tasks_per_second = 100
    tasks_submitted = 0
    tasks_completed = 0
    duplicated = 0
    start = time.time()
    last_print = start
    i = 0
    seen = set()
    while True:
        tasks_to_launch = (
            (time.time() - start) * tasks_per_second - tasks_submitted)
        while tasks_to_launch > 0:
            pending.append(random.choice(counters).inc.remote(1))
            tasks_submitted += 1
            tasks_to_launch -= 1
        if pending:
            ready, pending = ray.wait(
                pending, num_returns=min(1, len(pending)), timeout=10)
        else:
            time.sleep(.01)
        num_ready = len(ready)
        ready = set(ready).difference(seen)
        duplicated += num_ready - len(ready)
        tasks_completed += len(ready)
        seen = seen.union(ready)
        if time.time() - last_print > 1:
            print(
                "time", i,
                "submitted", tasks_submitted,
                "completed", tasks_completed,
                "running", len(pending),
                "duplicated", duplicated)
            last_print = time.time()
            i += 1
```

cc @stephanie-wang

**Comment by robertnishihara** [comment]
If this is the same problem as #1103, it should be fixed by #1118.

**Comment by robertnishihara** [comment]
@ericl has this been resolved?

**Comment by ericl** [comment]
Unfortunately I still see this as of b6c42f96beab3ee00fe4b246e5e9d0479ad379ca. I created a 2-worker cluster using the setup script and ran `ray stop` during the middle of the above script, and see the number of pending tasks grows forever after the `ray stop` (and also the duplicate return from wait issue still seems there).

```
time 147 submitted 14902 completed 11307 running 3595 duplicated 3463
time 148 submitted 15002 completed 11352 running 3650 duplicated 3463
time 149 submitted 15106 completed 11395 running 3711 duplicated 3463
time 150 submitted 15209 completed 11434 running 3775 duplicated 3463
time 151 submitted 15310 completed 11483 running 3827 duplicated 3463
time 152 submitted 15412 completed 11530 running 3882 duplicated 3463
time 153 submitted 15511 completed 11571 running 3940 duplicated 3463
```

I also saw this in the monitor.py logs:
```
WARNING:root:Removed b'plasma_manager', client ID c4db95b6895da9c1e1b3396169a4cae643598f55
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/monitor.py", line 676, in <module>
    monitor.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/monitor.py", line 621, in run
    self.cleanup_object_table()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/monitor.py", line 218, in cleanup_object_table
    objects = self.state.object_table()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/experimental/state.py", line 233, in object_table
    self._object_table(binary_to_object_id(object_id_binary)))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/experimental/state.py", line 197, in _object_table
    result_table_response, 0)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/core/generated/ResultTableReply.py", line 12, in GetRootAsResultTableReply
    n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flatbuffers/encode.py", line 24, in Get
    return packer_type.unpack_from(memoryview_type(buf), head)[0]
TypeError: memoryview: a bytes-like object is required, not 'NoneType'
```

**Comment by stephanie-wang** [comment]
That error in `monitor.py` looks similar to #1410.

The original issue is likely because calling `ray.wait` isn't actually implemented (#499).

**Comment by robertnishihara** [comment]
Oh nice, I've been trying to reproduce that bug.. @ericl can it be reproduced reliably?

**Comment by ericl** [comment]
The issue here is 100% reproducible

**Comment by robertnishihara** [comment]
@ericl after looking at this a bit more, I think the "duplicated" object IDs are not a real phenomenon. In particular, the appearance of duplicate object IDs occurs when you go through the `else` branch of the statement

```python
        if pending:
            ready, pending = ray.wait(
                pending, num_returns=min(1, len(pending)), timeout=10)
        else:
            time.sleep(.01)
```

Because then the `ready` set gets reused from one iteration to the next.

**Comment by edoakes** [comment]
@ericl is this fixed now?

**Comment by ericl** [comment]
Yeah
