### ISSUE TITLE
[dashboard] [autoscaler] Dashboard does not show actors once workers are autoscaled

### ISSUE THREAD

**Issue by PidgeyBE** [ray-project/ray#11080]
### What is the problem?

* ray 1.0.0rc2
* kubernetes autoscaling

### Reproduction (REQUIRED)
1. Start an autoscaling cluster
2. Go to dashboard -> This works
3. Deploy some ray actors and wait for autoscaling to deploy the necessary workers

Result: The ray dashboard does show the newly added workers, but does not show any actors deployed on the workers.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

BR, Pieterjan
@rkooo567 @mfitton

**Comment by mfitton** [comment]
Hmm, that's interesting. This could be because the machine view leans on PSUtil to get information about the Ray workers and what they're executing. Perhaps this isn't working correctly with Kubernetes at the moment. @ijrsvt do you know off hand whether things like PSUtil work correctly when autoscaling using kubernetes?

**Comment by PidgeyBE** [comment]
@mfitton Just to make this clear: Without autoscaling, by deploying a ray cluster manually on kubernetes, the dashboard works!

**Comment by ijrsvt** [comment]
@mfitton not that I'm aware of?

**Comment by ericl** [comment]
Should be fixed now

**Comment by PidgeyBE** [comment]
Still having issues with it.
This shows up as plain text in the dashboard in the latest nightly, when autoscaling:

```
Error: Traceback (most recent call last): File "/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/new_dashboard/utils.py", line 351, in _update_cache response = task.result() File "/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/new_dashboard/modules/stats_collector/stats_collector_head.py", line 89, in get_all_nodes all_node_details = await DataOrganizer.get_all_node_details() File "/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/new_dashboard/datacenter.py", line 193, in get_all_node_details for node_id in DataSource.nodes.keys() File "/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/new_dashboard/datacenter.py", line 193, in <listcomp> for node_id in DataSource.nodes.keys() File "/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/new_dashboard/datacenter.py", line 141, in get_node_info node_stats["viewData"], KeyError: 'viewData'
```

**Comment by PidgeyBE** [comment]
Also
```
SyntaxError: Unexpected token I in JSON at position 4
```
When using autoscaling in ray 1.0.1

cc @ericl
