### ISSUE TITLE
Unable to access Ray dashboard when running Ray on Kubernetes

### ISSUE THREAD

**Issue by ankur6ue** [ray-project/ray#11457]
### What is the problem?
Unable to access Ray dashboard when running Ray on a kubernetes cluster

*Ray version and other system information (Python version, TensorFlow version, OS):*
latest rayproject/autoscaler docker image
### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Just added containerPort: 8265 to expose 8265 on the head deployment. When I get the IP of the head pod using kubectl -get deployments -o wide and then go to that ip:8265, I get this site can't be reached..

Here's the ray-cluster.yaml:
```
# Ray head node service, allowing worker pods to discover the head node.
apiVersion: v1
kind: Service
metadata:
  namespace: ray
  name: ray-head
spec:
  ports:
    # Redis ports.
    - name: redis-primary
      port: 6379
      targetPort: 6379
    - name: redis-shard-0
      port: 6380
      targetPort: 6380
    - name: redis-shard-1
      port: 6381
      targetPort: 6381

    # Ray internal communication ports.
    - name: object-manager
      port: 12345
      targetPort: 12345
    - name: node-manager
      port: 12346
      targetPort: 12346
  selector:
    component: ray-head
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ray
  name: ray-head
spec:
  # Do not change this - Ray currently only supports one head node per cluster.
  replicas: 1
  selector:
    matchLabels:
      component: ray-head
      type: ray
  template:
    metadata:
      labels:
        component: ray-head
        type: ray
    spec:
      # If the head node goes down, the entire cluster (including all worker
      # nodes) will go down as well. If you want Kubernetes to bring up a new
      # head node in this case, set this to "Always," else set it to "Never."
      restartPolicy: Always

      # This volume allocates shared memory for Ray to use for its plasma
      # object store. If you do not provide this, Ray will fall back to
      # /tmp which cause slowdowns if is not a shared memory volume.
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
        - name: ray-head
          image: rayproject/autoscaler
          # imagePullPolicy: Never
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args: 
            - "ray start --head --node-ip-address=$MY_POD_IP --port=6379 --redis-shard-ports=6380,6381 --num-cpus=$MY_CPU_REQUEST \
            --object-manager-port=12345 --node-manager-port=12346 --dashboard-port 8265 --redis-password=password --block"
          ports:
            - containerPort: 6379 # Redis port.
            - containerPort: 6380 # Redis port.
            - containerPort: 6381 # Redis port.
            - containerPort: 12345 # Ray internal communication.
            - containerPort: 12346 # Ray internal communication.
            - containerPort: 8265 # Ray dashboard

          # This volume allocates shared memory for Ray to use for its plasma
          # object store. If you do not provide this, Ray will fall back to
          # /tmp which cause slowdowns if is not a shared memory volume.
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            # This is used in the ray start command so that Ray can spawn the
            # correct number of processes. Omitting this may lead to degraded
            # performance.
            - name: MY_CPU_REQUEST
              value: "3"
            #   valueFrom:
            #    resourceFieldRef:
            #      resource: requests.cpu
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ray
  name: ray-worker
spec:
  # Change this to scale the number of worker nodes started in the Ray cluster.
  replicas: 1
  selector:
    matchLabels:
      component: ray-worker
      type: ray
  template:
    metadata:
      labels:
        component: ray-worker
        type: ray
    spec:
      restartPolicy: Always
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: ray-worker
        image: rayproject/autoscaler
        # imagePullPolicy: Never
        imagePullPolicy: Always
        command: ["/bin/bash", "-c", "--"]
        args:
          - "ray start --node-ip-address=$MY_POD_IP --num-cpus=$MY_CPU_REQUEST --address=$RAY_HEAD_SERVICE_HOST:$RAY_HEAD_SERVICE_PORT_REDIS_PRIMARY \
          --object-manager-port=12345 --node-manager-port=12346 --redis-password=password --block"
        ports:
          - containerPort: 12345 # Ray internal communication.
          - containerPort: 12346 # Ray internal communication.
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

          # This is used in the ray start command so that Ray can spawn the
          # correct number of processes. Omitting this may lead to degraded
          # performance.
          - name: MY_CPU_REQUEST
            value: "3"
            # valueFrom:
            #  resourceFieldRef:
            #    resource: requests.cpu
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
```
If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by Vysybyl** [comment]
Similar issue here (I also experienced the same issue as described by the issue above with google cloud service and ray autoscaler). 

Please check the JS error below, I think it's the right lead to solve this.

I am using a single GCP VM in a VPN (setup with openvpn).

I ssh to the remote machine and start ray 1.0.0 with command:
```bash
ray start \
      --head \
      --port=6379 \
      --object-manager-port=8076 \
      --include-dashboard=true \
      --dashboard-host=0.0.0.0 \
      --dashboard-port=8266
```
I get 
```bash
Local node IP: xx.xx.xx.xx
2020-10-19 10:25:10,664	INFO services.py:1164 -- View the Ray dashboard at http://xx.xx.xx.xx:8266

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='xx.xx.xx.xx:6379' --redis-password='yyyyyyyyyyyyyyy'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='yyyyyyyyyyyyyyy')
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop
```
At this point I can connect to the dashboard with no issues.

Then I start a local 0-resource node (otherwise I can't run ray.init on my local machine)
`ray start --address='xx.xx.xx.xx:6379' --redis-password='yyyyyyyyyyyyyyy' --num-cpus=0 --num-gpus=0`

From this point on the dashboard is blank. The page renders for a couple of frames, then it disappears. The anchor HTML object is there on the page but JS does not show anything.  

I can't see anything relevant from the network log on the browser, but the browser console shows:
```javascript
react-dom.production.min.js:209 TypeError: Cannot read property 'toFixed' of null
    at dn (GPU.tsx:92)
    at Qi (react-dom.production.min.js:153)
    at vl (react-dom.production.min.js:261)
    at cu (react-dom.production.min.js:246)
    at lu (react-dom.production.min.js:246)
    at Zl (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ho (react-dom.production.min.js:122)
    at Ko (react-dom.production.min.js:123)
```
If I stop my local ray process with `ray stop`, the JS error disappears and the dashboard is displayed again. 

**None of this has any effect on the python API**. `ray.init`, `ray.remote`, `ray.get`, etc. all works fine.

**Comment by mfitton** [comment]
@Vysybyl I believe the issue you're seeing is one that #11313 is tracking. I'm working on a fix at the moment.
As far as the issue that @ankur6ue mentioned, I'm not sure what the cause is exactly. Could you provide any additional information like the dashboard log and error log? It's at `/tmp/ray/session_latest/logs/dashboard.err` and `/tmp/ray/session_latest/logs/dashboard.out`

**Comment by Vysybyl** [comment]
Hi @mfitton, 

Thanks a lot for taking care of this!

I don't have the original logs right now since I'm using as head node a cloud VM that is deleted once I finish using it. 

I tried to replicate the issue running `ray start --head` on my local machine. If what follows is not enough I'll grab the logs from the remote VM next time I use it.

Strangely, I run into a similar but maybe unrelated issue (see point 2 below) trying to run a head node with 0 cpus.

1) I run

`ray start --head --num-cpus=1 --num-gpus=0`

The dashboard flickers for a second and then becomes blank

The error from the console is 
```javascript
react-dom.production.min.js:209 TypeError: Cannot read property 'find' of null
    at GRAM.tsx:119
    at Array.map (<anonymous>)
    at WorkerFeatureRenderFn (GRAM.tsx:118)
    at Qi (react-dom.production.min.js:153)
    at vl (react-dom.production.min.js:261)
    at cu (react-dom.production.min.js:246)
    at lu (react-dom.production.min.js:246)
    at Zl (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
el @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
di @ react-dom.production.min.js:131
il @ react-dom.production.min.js:212
pu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ho @ react-dom.production.min.js:122
du @ react-dom.production.min.js:248
Zl @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ho @ react-dom.production.min.js:122
Ko @ react-dom.production.min.js:123
qo @ react-dom.production.min.js:122
eu @ react-dom.production.min.js:240
notify @ Subscription.js:19
t.notifyNestedSubs @ Subscription.js:92
t.handleChangeWrapper @ Subscription.js:97
v @ redux.js:221
(anonymous) @ index.js:11
(anonymous) @ redux.js:477
(anonymous) @ Dashboard.tsx:66
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Dashboard.tsx:77
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ main.8fe93ca5.chunk.js:1
il @ react-dom.production.min.js:212
pu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ho @ react-dom.production.min.js:122
du @ react-dom.production.min.js:248
Zl @ react-dom.production.min.js:239
Ql @ react-dom.production.min.js:230
_u @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
tu @ react-dom.production.min.js:240
$u @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
134 @ index.tsx:6
l @ (index):1
121 @ main.8fe93ca5.chunk.js:1
l @ (index):1
r @ (index):1
t @ (index):1
(anonymous) @ main.8fe93ca5.chunk.js:1
Show 29 more frames
react-dom.production.min.js:209 TypeError: Cannot read property 'toFixed' of null
    at dn (GPU.tsx:92)
    at Qi (react-dom.production.min.js:153)
    at vl (react-dom.production.min.js:261)
    at cu (react-dom.production.min.js:246)
    at lu (react-dom.production.min.js:246)
    at Zl (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ho (react-dom.production.min.js:122)
    at Ko (react-dom.production.min.js:123)
```

The logs are 
[ray_1cpu_0gpus_logs.zip](https://github.com/ray-project/ray/files/5432832/ray_1cpu_0gpus_logs.zip)


2) I run

`ray start --head --num-cpus=0 --num-gpus=0`  

(I'm not really expecting a 0-resource head node to work, but I think this should at least raise an error...)

The dashboard shows a json error 
![ray_0cpus_0gpus](https://user-images.githubusercontent.com/18312039/97081030-fb2ff500-15ff-11eb-94d9-1e5912dbea84.png)


The error from the console is 
```javascript
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8265/api/raylet_info:1 
```

The logs are 
[ray_0cpus_0gpus_logs.zip](https://github.com/ray-project/ray/files/5432836/ray_0cpus_0gpus_logs.zip)

I'm on xubuntu (Ubuntu 20.04.1 LTS), conda env with python 3.8.3, ray version 1.0.0 from pypi.

**Comment by mfitton** [comment]
@Vysybyl Ah, I'm sorry you encountered this. There was a bug in the last couple versions of the dashboard that caused the page to not load when there are no workers in the cluster. If you start up some workers by launching tasks or actors, the page should display. That said, the issue is tracked here: https://github.com/ray-project/ray/issues/11384 
This issue is actually fixed in the most recent version of the dashboard (currently in the nightly, and slated for the 1.2.0 release in a few weeks).

**Comment by rkooo567** [comment]
@ankur6ue can you verify if the issue is resolved in the latest version?

**Comment by mfitton** [comment]
I'm going to close as there hasn't been recent activity, and I believe the issue has been fixed. Please reopen if I've made a mistake.

**Comment by danlg** [comment]
I believe this is not fixed  even with -p 8265 on docker run command, that doesn't work

on mac 
docker run --shm-size=100M -t --tty --interactive  -p 8265 rayproject/ray
(base) ray@8d3972dc8dbc:/$ ray start --head
Local node IP: 172.17.0.2
2021-01-15 10:06:00,245	INFO services.py:1173 -- View the Ray dashboard at http://localhost:8265
=> not able to see the dashboard...

**Comment by harryge00** [comment]
@danlg It should work. Try this:
```
docker run --shm-size=100M -t --tty --interactive -p 8265:8265 rayproject/ray

(base) ray@9b7d8802e3a2:/$ ray start  --head  --dashboard-host=0.0.0.0
```
View the Ray dashboard at http://localhost:8265

**Comment by SheldonCurtiss** [comment]
still getting this

**Comment by rkooo567** [comment]
When you guys say it doesn't, work does that mean the port forwarding is not working or the page is not displayed?

**Comment by rkooo567** [comment]
Also, not sure if it is K8s related, but cc @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
@SheldonCurtiss could you describe how you're deploying Ray on k8s and accessing the dashboard?

**Comment by ankur6ue** [comment]
Here's how:
kubernetes yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: ray-head
spec:
  containers:
    - name: ray-head
      image: rayproject/ray # tesseract-ocr:latest
      command: [ "/bin/bash", "-c", "--"]
      args:
        - "sleep 3600"
      #  - "ray start --head --num-cpus=$MY_CPU_REQUEST"
      # We want to use a local image, as opposed to from a container repo
      imagePullPolicy: Never
      ports:
        - containerPort: 6379  # Redis port
        - containerPort: 10001  # Used by Ray Client
        - containerPort: 8265  # Used by Ray Dashboard
        - containerPort: 8000 # Used by Ray Serve
```
do k create -f <yaml-name>
exec into the container and start ray:
k exec --stdin --tty ray-head -- /bin/bash
ray start --head --num-cpus=4

Go to pod_ip:8265 on a browser. Dashboard should show up. It doesn't. Interestingly, when I curl pod_ip:8265, I get connection refused, but when I curl pod_ip:10001, I get curl: (1) Received HTTP/0.9 when not allowed, which tells me that there is nothing wrong the port forwarding set up..

**Comment by DmitriGekhtman** [comment]
What version of Ray is used here?

**Comment by ankur6ue** [comment]
Latest version.. 1.4.1 I believe

**Comment by ankur6ue** [comment]
When I run ray from inside a docker container, then I'm able to access the dashboard from outside:

```
 docker run -itd --rm --name=$CONTAINER_NAME --cpus=0.000 \
  --network=host
  $IMAGE_NAME /bin/bash

  docker exec $CONTAINER_NAME \
    ray start --head --num-cpus=$NUM_CPUS --port=8265
```
Please help debug what goes wrong when it is running as a kubernetes pod..

**Comment by DmitriGekhtman** [comment]
To view the dashboard, you need to run the following locally (outside the cluster)
`kubectl port-forward ray-head 8265:8265`
then open `http://localhost:8265` in a browser.

Check out the [docs](https://docs.ray.io/en/master/cluster/kubernetes.html) for the recommended way of using Ray on K8s.

**Comment by DmitriGekhtman** [comment]
We should probably make that the default.

**Comment by DmitriGekhtman** [comment]
> Hum... Wouldn't that be dangerous though?
> 
> For Docker, there would be no problem, since the container is closed to the outside world by default.
> 
> However, if I'm just running a python script, `0.0.0.0` would open the dashboard to the outside world, right?

Perhaps it should be the default on K8s? That wouldn't expose the dashboard outside the K8s cluster, I don't think? (I should mention I know nothing about networking.)

**Comment by ZeCarlosCoutinho** [comment]
I'm inclined to say yes, it should be the default, but my knowledge about k8s is minimal :sweat_smile:
So I'd consult with someone with more knowledge than me before making the change xD
