### ISSUE TITLE
[tune] resume is not working properly

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#12389]
Hi,

My issue:
I would like to be able to resume a training run (for the time being a standard "Choice" brute force search), if the run interrupts...
but it does not work as I would expect.

In my example I started a grid search with ~450 different values via tune.Choice(). I used a cluster with roughly 50 nodes,  1 worker per node, and artificially stopped the tune run after some time. At this time, the remaining ~400 trials were not yet started. Then I try to resume the whole run by running the script again, this time with resume=True (or LOCAL/PROMPT). 
However, tune only resumes and restarts those jobs that were already running on the nodes, i.e. the 50 that have local subfolders.

How can I make tune resume ALL 450 trials that are in principle part of this Experiment?
Best,
Thorsten

_Originally posted by @thoglu in https://github.com/ray-project/ray/discussions/12265_

@richardliaw -> I was able to reproduce this after I ran:

```
#!/usr/bin/env python

import argparse
import time

import ray
from ray import tune
from ray.tune.schedulers import AsyncHyperBandScheduler


def evaluation_fn(step, width, height):
    time.sleep(0.1)
    return (0.1 + width * step / 100)**(-1) + height * 0.1


def easy_objective(config):
    # Hyperparameters
    width, height = config["width"], config["height"]

    for step in range(config["steps"]):
        # Iterative training function - can be an arbitrary training procedure
        intermediate_score = evaluation_fn(step, width, height)
        # Feed the score back back to Tune.
        import time
        time.sleep(1)
        tune.report(iterations=step, mean_loss=intermediate_score)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--smoke-test", action="store_true", help="Finish quickly for testing")
    parser.add_argument(
        "--ray-address",
        help="Address of Ray cluster for seamless distributed execution.",
        required=False)
    args, _ = parser.parse_known_args()
    ray.init(address=args.ray_address)

    # AsyncHyperBand enables aggressive early stopping of bad trials.
    # scheduler = AsyncHyperBandScheduler(grace_period=5, max_t=100)

    # 'training_iteration' is incremented every time `trainable.step` is called
    stopping_criteria = {"training_iteration": 1 if args.smoke_test else 9999}

    analysis = tune.run(
        easy_objective,
        resume=True,
        metric="mean_loss",
        mode="min",
        # scheduler=scheduler,
        stop=stopping_criteria,
        num_samples=20,
        local_dir="/root/ray_results/",
        verbose=1,
        resources_per_trial={
            "cpu": 1,
            "gpu": 0
        },
        config={  # Hyperparameter space
            "steps": 100,
            "width": tune.uniform(10, 100),
            "height": tune.uniform(0, 100),
        })
    print("Best hyperparameters found were: ", analysis.best_config)
```

and terminated the job, and reran it.

**Comment by richardliaw** [comment]
This is a duplicate issue.

**Comment by FarzanT** [comment]
@richardliaw I have a similar problem, but I can't find the other issue to comment on. I want to resume from a HyperOpt experiment with the ASHA Scheduler, and I initially set the `time_budget_s` argument to 24 hours (84000 seconds) which is the maximum allowed time on our cluster. Of course, I would like to submit a second job to the cluster to resume these trials, but Tune assumes that the experiment is done, and gives me the following:
<img width="1515" alt="image" src="https://user-images.githubusercontent.com/21085967/105749874-000f8800-5f12-11eb-84b2-1f8d62cbf25d.png">

So out of 1000 trials, it only finished 118 and doesn't want to resume them. Of course I am using the `resume=True` argument on `tune.run`. Is this issue caused by the `time_budget_s` argument that cannot be modified? I tried setting the budget higher when I want to resume, but it still gives me the same 118/1000 trials argument.
Note that I've set `grace_period` on `ASHA` to 5, but the first trial in the list above has only completed 1 `training_iteration`.

Thank you

**Comment by richardliaw** [comment]
@FarzanT could you try this with the latest master wheels? https://docs.ray.io/en/master/installation.html

This was fixed rather recently.

**Comment by FarzanT** [comment]
@richardliaw So sorry but since I'm using a PowerPC-based cluster I have to wait for IT to make wheels. Glad to hear it was fixed!
Thank you

**Comment by Numchies** [comment]
I have the same problem as @FarzanT. Issue still seems to not be fixed.

**Comment by HJasperson** [comment]
I also am experiencing this issue with ray 1.12

**Comment by aflag** [comment]
I think I'm also running into the same issue as @FarzanT in ray 1.13. It seems `time_budget_s` causes all the trials to transition to terminated, which make them not resumable.

**Comment by scottsun94** [comment]
cc: @krfricke @xwjiang2010 

It seems this issue is not fixed. Could you confirm?
