### ISSUE TITLE
[core] exit_actor() broken with async actors

### ISSUE THREAD

**Issue by PidgeyBE** [ray-project/ray#12649]
### What is the problem?

*1.0.1 and latest master

### Reproduction (REQUIRED)
```
import ray
import time

ray.init()

@ray.remote
class SomeActor():

    def function(self):
        print("Running in sync function")
        time.sleep(2)
        print("Done in sync function")

    async def function_async(self):
        print("Running in sync function")
        await asyncio.sleep(2)
        print("Done in sync function")

    def terminate(self):
        print("Self-killing")
        ray.actor.exit_actor()

for i in range(10):
    try:
        actor = SomeActor.remote()
        second = actor.function.remote()
        ray.get(actor.terminate.remote())
        print("waiting for function")
        result = ray.get(second)
        print("done")
    except Exception as e:
        print(f"raised {e}")
```
-> This script never ends.
Note the async method `function_async` is not used, only defined. Removing this method makes the script work.
So it seems that as soon as 1 async method is defined on an actor, `ray.actor.exit_actor()` is broken.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
Hi @PidgeyBE thanks for raising this. I will look into it

**Comment by simon-mo** [comment]
The reason is SystemExit (raised by exit_actor()) was raised in the asyncio loop thread, which isn't caught by Ray worker's main thread. A work-around is to use `os._exit(0)` to exit the process forcefully. But this will skip Ray worker's cleanup stack. I will continue investigate a solution for this.

**Comment by simon-mo** [comment]
@PidgeyBE this should be fixed in Ray master once the wheel is available in few hours!

**Comment by PidgeyBE** [comment]
I don't understand why the changes in the linked MR are not in ray 1.1.0, but for some reason the repro script above does not freeze anymore in ray 1.1.0.
Anyhow, the following script still freezes:
```
import ray
import time
import asyncio

ray.init()

@ray.remote
class SomeActor():

    async def function_async(self):
        print("Running in async function")
        await asyncio.sleep(2)
        print("Done in async function")

    def terminate(self):
        print("Self-killing")
        ray.actor.exit_actor()

loop = asyncio.get_event_loop()

for i in range(10):
    try:
        actor = SomeActor.remote()

        async def kill():
            actor.terminate.remote()

        async def test():
            fut = actor.function_async.remote()
            await asyncio.wait([fut, kill()])
        
        loop.run_until_complete(test())
        print("done")
    except Exception as e:
        print(f"raised {e}")
```

**Comment by simon-mo** [comment]
Thanks for reporting! Does it still freeze in master?

**Comment by PidgeyBE** [comment]
No, in master there is no issue!
