### ISSUE TITLE
[Autoscaler] Autoscaler is not setting --shm-size for docker, causing Ray to fail to start

### ISSUE THREAD

**Issue by allenyin55** [ray-project/ray#14535]
### What is the problem?
When using the Ray cluster launcher with docker, `ray start` sometimes fails because of the following error:
```
ValueError: The configured object store size exceeds the capacity of /dev/shm. This will harm performance. To proceed regardless of this warning, you can set RAY_OBJECT_STORE_ALLOW_SLOW_STORAGE=1. Consider deleting files in /dev/shm or increasing its size with --shm-size in Docker.
```

The root cause seems to be that docker shm size is calucated by the autoscaler as `0.3 * available sys mem`, and if the machine is under load during the shm size calculation, this number could be smaller than what the object store expects during the ray startup, throwing the error above.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
You should set --shm-size explicitly in docker (this is a normal error). Previously, it mean Ray would silently start with misconfigured memory storage.

Alternatively, you can set RAY_ALLOW_SLOW_STORAGE as the error message says.

**Comment by ijrsvt** [comment]
@ericl This is using `autoscaler` and is a bug where the auto detection should avoid this error from appearing!

**Comment by ericl** [comment]
Thanks @ijrsvt , I updated the title to clarify this. Note that the description of the issue is still incorrect.

**Comment by ijrsvt** [comment]
@ericl  I'll fix that as well :)

**Comment by ijrsvt** [comment]
@ericl 
We are wrong, this PR caused the problem #14345

**Comment by ijrsvt** [comment]
Fixed by #14556

**Comment by Glaucus-2G** [comment]
> You should set --shm-size explicitly in docker (this is a normal error). Previously, it mean Ray would silently start with misconfigured memory storage.
> 
> Alternatively, you can set RAY_ALLOW_SLOW_STORAGE as the error message says.

Can you tell me how to set RAY_ALLOW_SLOW_STORAGE =1 in py files? I have searched some issues but I still don't  know how to use this information.

**Comment by ijrsvt** [comment]
@Glaucus-2G You could do something like:
```
import os
os.environ["RAY_ALLOW_SLOW_STORAGE"] = "1"
import ray
# Rest of the code
```

**Comment by Glaucus-2G** [comment]
> @Glaucus-2G You could do something like:
> 
> ```
> import os
> os.environ["RAY_ALLOW_SLOW_STORAGE"] = "1"
> import ray
> # Rest of the code
> ```

Thank you for your help!

**Comment by Glaucus-2G** [comment]
> @Glaucus-2G You could do something like:
> 
> ```
> import os
> os.environ["RAY_ALLOW_SLOW_STORAGE"] = "1"
> import ray
> # Rest of the code
> ```

@ijrsvt Thank you for your help!
