### ISSUE TITLE
[RLlib nightly test] multi_gpu* tests are failing consistently

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#18499]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
nightly release

multi_gpu* tests are failing consistently

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by xwjiang2010** [comment]
Feel free to dupe it if you already have one bug opened. 

also cc @sven1977

**Comment by gjoliver** [comment]
anyscale/ray-ml:pinned-nightly-py37-gpu has been updated to use tensorflow 2.4.3
However things still seem to timeout (with a different more cryptic "Internal Server Error" this time?).

Attached to the CI session via a link found in the log.
Verified that we do have cuda 11.2 and tensorflow 2.4.3 on the head node.
Tried to use GPU via tensorflow manually. All the other libraries seem to be ok, but one of them still have issue:

```
2021-09-11 12:19:07.338191: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
```

The version of tf we have somehow is still trying to load libcusolver.so.10, and from a non-existent folder /usr/local/nvidia.
I manually created a couple of symbolic links, so this links to libcusolver.so.11.
And things started to work fine.

... Should we use a different version of tf??

**Comment by gjoliver** [comment]
reproduced this on a local workstation.
at least, tf 2.5.0 and up works with cuda 11.2 and cudnn 8.x

also, I have a feeling if we just "ln -s" create those 2 dir/files as post installation steps, this can probably work too.
hacky, but we don't have to ask product team to do another release.

**Comment by gjoliver** [comment]
Fixed by @sven1977 and @gjoliver

**Comment by jjyao** [comment]
@gjoliver seems multi_gpu_learning_tests is still failing https://buildkite.com/ray-project/periodic-ci/builds/987#71e574c7-1d54-4ead-b474-8ef349823898

**Comment by gjoliver** [comment]
ah yeah, these SAC tests requires tensorflow_probability, which requires tf 2.5.0
@sven1977 merged a PR to bump the tf version, but I think we may need to wait for product team to push a new docker image.
otherwise, we can comment out these 2 tests for now.

**Comment by jjyao** [comment]
ok, you guys can decide to do next. Do you think we should still keep it open as release blocker then?

**Comment by gjoliver** [comment]
we can leave it open for now, since learning_tests and stress tests are still green.
I need to grab simon.
this test is much easier to handle, and we can flip the switch anytimne.

**Comment by jjyao** [comment]
multi_gpu* tests passed today. https://buildkite.com/ray-project/periodic-ci/builds/1016#a94939f7-5fd8-4127-8177-d19351807b4a

**Comment by architkulkarni** [comment]
These are failing again with "Trials did not complete".  It seems to be failing consistently.

1.10.0 Release branch: https://buildkite.com/ray-project/periodic-ci/builds/2197#_
Master: https://buildkite.com/ray-project/periodic-ci/builds/2192

@gjoliver is this a release blocker for 1.10.0?

**Comment by gjoliver** [comment]
yeah, this should be a blocker. we had some updates to PG agent recently that probably broke multi-gpu training.
the real error message is:

2022-01-03 09:58:40,549	ERROR trial_runner.py:927 -- Trial PG_CartPole-v0_315ba_00013: Error processing event.
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 893, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 707, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1735, in get
    raise value
  File "python/ray/_raylet.pyx", line 770, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 591, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 733, in ray._raylet.execute_task
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::PGTrainer.__init__()[39m (pid=22268, ip=172.31.82.254)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 729, in __init__
    sync_function_tpl)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 122, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 781, in setup
    self.validate_config(self.config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 2143, in validate_config
    "Cannot use `simple_optimizer` if `num_gpus` > 1! "
ValueError: Cannot use `simple_optimizer` if `num_gpus` > 1! Consider not setting `simple_optimizer` in your config.

assigning to @sven1977. hopefully a quick fix.

**Comment by sven1977** [comment]
We should just remove PGTrainer from the multi-GPU test cases for now until we add multi-GPU support for the non-exec-plan algos (only PG right now).

**Comment by sven1977** [comment]
This PR adds the multi-gpu version of train_one_step to PGTrainer. This should fix the issue.
https://github.com/ray-project/ray/pull/21376

**Comment by zhe-thoughts** [comment]
Thanks @sven1977 @architkulkarni !

Since https://github.com/ray-project/ray/pull/21376 is merged, should this issue still be open?
