### ISSUE TITLE
[Bug] Ray Mac OSX security popups every time I run script locally

### ISSUE THREAD

**Issue by worldveil** [ray-project/ray#18730]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Monitoring & Debugging, Others

### What happened + What you expected to happen

I always see these popups.

<img width="666" alt="Screen Shot 2021-09-17 at 3 23 13 PM" src="https://user-images.githubusercontent.com/1045250/133863772-5a029076-d31c-46bb-bea6-3def02558c75.png">

They are ridiculously annoying and often keep appearing even after script is done running. 

It doesn't give me confidence in Ray.

### Reproduction script

Literally any ray example will work. 

```python
from ray import tune


def objective(step, alpha, beta):
    return (0.1 + alpha * step / 100)**(-1) + beta * 0.1


def training_function(config):
    # Hyperparameters
    alpha, beta = config["alpha"], config["beta"]
    for step in range(10):
        # Iterative training function - can be any arbitrary training procedure.
        intermediate_score = objective(step, alpha, beta)
        # Feed the score back back to Tune.
        tune.report(mean_loss=intermediate_score)


analysis = tune.run(
    training_function,
    config={
        "alpha": tune.grid_search([0.001, 0.01, 0.1]),
        "beta": tune.choice([1, 2, 3])
    })

print("Best config: ", analysis.get_best_config(
    metric="mean_loss", mode="min"))

# Get a dataframe for analyzing trial results.
df = analysis.results_df
```

should trigger this.

### Anything else

Let's figure out how to address and add to the docs.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
@ijrsvt @thomasdesr or other mac users, do you know if this is because the worker processes are binding to something like 0.0.0.0 (instead of 127.0.0.1)?

Or is OSX just complaining about any port being opened, even if it listens only internally?

**Comment by pcmoritz** [comment]
Did we try if listening on `localhost` on macOS fixes this issue as @ericl suggests above? That should fix this issue right? Is this too hard to do?

**Comment by jjyao** [comment]
I did a quick check, for grpc servers, we are listening to 0.0.0.0 and gcs server is using 192.168. Do we currently have a way to know in c++ that we are in the single node mode so we can safely use 127.0.0.1. Once we know that, the fix should be trivial. @ericl @pcmoritz?

**Comment by pcmoritz** [comment]
I don't think there is a flag/setting for single node mode currently, but I think it would be ok to add a simple helper function in C++ that checks if we are on macOS and if yes return 127.0.0.1 and else return 0.0.0.0. Later if needed we could migrate it to a flag, but I don't really see the need. I doubt we need to support macOS clusters any time soon (or ever).

**Comment by jjyao** [comment]
@worldveil it should have been fixed. Could you verify and close the issue?

**Comment by worldveil** [comment]
I still see this on `ray start --head`

<img width="1073" alt="Screen Shot 2021-11-08 at 8 55 13 PM" src="https://user-images.githubusercontent.com/1045250/140864918-5f4d3da0-5cde-466c-a266-8eae9bb95b0a.png">

**Comment by jjyao** [comment]
@worldveil Can you try it now with the latest wheel. Sorry for so many iterations.

**Comment by jjyao** [comment]
Confirmed with @worldveil that popups are gone.

**Comment by worldveil** [comment]
@jjyao I have seen it again :/ is there any reason I should be seeing this on Ray 1.9.x? any regressions?

I can try to provide a repro if needed, but it is inconsistent

**Comment by jjyao** [comment]
No, it shouldn't happen. If you can give a repro, I'm happy to debug it.

**Comment by worldveil** [comment]
Have not been able to repro! Leaving closed for now.
