### ISSUE TITLE
[Bug] ERR_EMPTY_RESPONSE when accessing the Ray dashboard in Windows

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#19480]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Dashboard

### What happened + What you expected to happen

When I run the following in Windows on the latest master in an Ipython shell:

```python
import ray
ray.init(include_dashboard=True)
```

Screenshot with additional logs:

![Screenshot 2021-10-18 134525](https://user-images.githubusercontent.com/113316/137804292-89ed3b01-b495-4482-a7db-17ded01805b8.png)

### Versions / Dependencies

Python 3.7

### Reproduction script

see description above

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pcmoritz** [comment]
If I install npm from nodejs.org/en/download and run the npm commands in https://docs.ray.io/en/latest/development.html#building-ray-on-linux-macos-full to build the dashboard, this error goes away. The PR https://github.com/ray-project/ray/pull/19489 was needed to make this work.

**Comment by pcmoritz** [comment]
fixed by https://github.com/ray-project/ray/pull/19575

**Comment by Nesqulck** [comment]
I still get this error on 1.8.0. Any ideas? I also have to manually downgrade aiohttp from 3.8.0 to 3.7.4post0 for the dashboard agent and logs to appear inside ray log folder. Otherwise the dashboard does not even start.

win10
py3.9
ray[default]==1.8.0
aiohttp==3.7.4post0

running inside virtualenv but also fails outside an env

**Comment by wayneadams** [comment]
I am seeing the `ERR_EMPTY_RESPONSE` message as well.

### What happened

When running 
```python
import ray
ray.init(include_dashboard=True)
```

in a VSCode notebook cell, I do get output that looks like a successful startup:

![image](https://github.com/user-attachments/assets/5d79b0d9-56d0-4b7a-ab70-588a198a8fda)

However, when I go to the Dashboard's link, I see this:

![image](https://github.com/user-attachments/assets/bcc4cbf4-9bac-49d6-8744-a7db7de168b1)


### Versions

#### System

I'm using Windows Server 2022 Datacenter

![image](https://github.com/user-attachments/assets/87a2897a-891d-4a19-8fcf-387767406d71)

#### What Python sees
```
platform.system()            Windows
platform.release()           10
platform.version()           10.0.20348
platform.machine()           AMD64
platform.architecture()      ('64bit', 'WindowsPE')
platform.processor()         AMD64 Family 25 Model 1 Stepping 0, AuthenticAMD
```

#### Ray packages installed
```powershell
PS C:\Users\wadams19\workspace\nt-rl-futures> conda install -c conda-forge "ray-default"
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.
```

#### Browser info
```
Microsoft Edge
Version 129.0.2792.79 (Official build) (64-bit)
```

**Comment by wayneadams** [comment]
@rynewang , do you know current reviewer would be best to take a look at this?

**Comment by rynewang** [comment]
@wayneadams can you create another issue and ping me?

**Comment by mattip** [comment]
- Do you see any error messages in the log files (in `%TEMP%/ray/`)?
- Does it all work outside a notebook environment? Perhaps you are running your notebook using a kernel on a remote host?
