### ISSUE TITLE
[Release 1.11.0] `xgboost_gpu_connect_master` failing

### ISSUE THREAD

**Issue by mwtian** [ray-project/ray#22432]
Same errors on `master` and `releases/1.11.0` branches:
```
TypeError: __init__() got an unexpected keyword argument 'qid'
```
https://buildkite.com/ray-project/periodic-ci/builds/2788#50097f7e-cc1d-443e-b4f2-c8ebee8366de/139-322
https://buildkite.com/ray-project/periodic-ci/builds/2778#04a5f326-6f4e-41d3-a0a7-61cc4e5f2249/138-331
Please advise if a fix should be made and cherry-picked, or the error can be ignored. Thanks.

**Comment by amogkam** [comment]
Should be fixed by https://github.com/ray-project/xgboost_ray/pull/193 once it's merged.

**Comment by mwtian** [comment]
Nice, rerunning the test.

**Comment by mwtian** [comment]
Still failing, but it seems this is an issue external to Ray. Downgrading to P1.

**Comment by mwtian** [comment]
Thanks Amog, The test was passing on release branch now too.
