### ISSUE TITLE
[Bug]  Dashboard broken for a node with a GPU with no utilization stats

### ISSUE THREAD

**Issue by mzakharocsc** [ray-project/ray#22954]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Dashboard

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

I have a node with an Nvidia GTX 790 GPU on Linux (Ubuntu 20.04).  When I  try to view a dashboard, containing this node, it breaks ( does not display anything but white empty page). 

Symptoms are similar to https://github.com/ray-project/ray/issues/15650.  

Inspecting dashboard_agent.log  I see 
```
Traceback (most recent call last):
  File "/home/mzakharo/.local/lib/python3.8/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 560, in _perform_iteration
    records_reported = self._record_stats(stats, cluster_stats)
  File "/home/mzakharo/.local/lib/python3.8/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 449, in _record_stats
    gpus_utilization += gpu["utilization_gpu"]
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

Output of gpustat
```
[0] NVIDIA GeForce GTX 760 | 39°C,  ?? % |   443 /  1996 MB | (Not Supported)
```

Temporary changing line 449 in reporter_agent.py to  ` gpus_utilization +=  0`  fixes the dashboard display.

This GPU is 'consumer rated', and is blocked by NVIDIA from displaying stats, Maybe we should just ignore these stats if they are not available?

  Alternatively --num-gpus=0 in 'ray start' could be made to disable GPU metrics gathering entirely.

 Can somoene please weigh in on the correct solution to this issue?

### Versions / Dependencies

ray 1.11.0

### Reproduction script

ray start --head  on a node with an Nvidia GTX 790 GPU.

### Anything else

ray start --head --num-gpus=0   does not help.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by frosk1** [comment]
why is this closed? can replicate the same on ray 1.11.0

**Comment by mwtian** [comment]
@frosk1 this is issue is not closed, only a related one. I sent out https://github.com/ray-project/ray/pull/23468 for a workaround.

**Comment by frosk1** [comment]
yes sry, I did remove my comment ;)

**Comment by mwtian** [comment]
Should be fixed on Ray nightly / `master` branch, but I do not have the environment to verify it.

**Comment by frosk1** [comment]
@mwtian unfortunately the issue is not resolved.

 **line 265, in _get_actor for process in gpu_stats.get("processes", []): TypeError: 'NoneType' object is not iterable**

**Comment by frosk1** [comment]
`gpu_stats` is a `ImmutableDict` with field prcesses seems to be None here and `not iterable`.

**Comment by mwtian** [comment]
> @iycheng @mwtian unfortunately the issue is not resolved.
> 
> **line 265, in _get_actor for process in gpu_stats.get("processes", []): TypeError: 'NoneType' object is not iterable**

Hopefully this error is fixed now. If dashboard for consumer card still does not work, we will need to find a workstation with one and fix the remaining issues.
