### ISSUE TITLE
[Dashboard] The dashboard.py process leaks memory

### ISSUE THREAD

**Issue by mihajenko** [ray-project/ray#26568]
### What happened + What you expected to happen

We have observed `RayOutOfMemoryError`s on the ray cluster head node. This failed our main Serve Deployment replica, which is running on the head node. After successfully passing short-term (few hour) stress tests, we expected the head node to be stable.

---

Logs pointed out the `dashboard.py` process might be the cause:
```
INFO 2022-06-28 08:00:23,847 controller 366 deployment_state.py:493 - Health check for replica InferenceAPI#aCylFS failed: [36mray::RayServeWrappedReplica.check_health()[39m (pid=431, ip=10.115.31.11, repr=<ray.serve.replica.InferenceAPI object at 0x7fc3ea776700>)
ray._private.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node ray-ac-ray-head-type-d2f9w is used (2.85 / 3.0 GB). The top 10 memory consumers are:

PID	MEM	COMMAND
185	1.59GiB	/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.8/site-packages/ray/dashboard/dashboard.py
```

I raised the issue [on Slack](https://ray-distributed.slack.com/archives/CP950VC76/p1656969747576429). According to @rkooo567, memory leaks surrounding the dashboard have been observed in the past. They suggested we use a workaround by setting `RAY_DISABLE_DASHBOARD_LOG_INFO=1` in the head node. This disabled the caching of logs (at least visibly), as intended. However, the memory leak persists. The only difference this made was to slow down the leakage.

After locating the leaky process and excluding other possibilities (e.g. `emptyDir` volumes), we ran a simple bash script to monitor the dashboard.py process ID memory usage on the head node. During this test, we deployed only the main Deployment replica to this test cluster. We made no real HTTP requests to it, very little interaction overall.

![Screenshot_20220714_182337](https://user-images.githubusercontent.com/2692678/179042802-f2493aaa-c49d-4555-9037-b5ada80a2ce3.png)
(unit is "kb")

The memory leak appears to have constant growth. It is only a few MB / hour, but we believe this will lead to the same failure.

We also verified it is indeed only happening on the head node, and only when the dashboard.py Python process is running. We tested this by killing the process, and the memory freed up and remained stable afterwards.

![ray-head-memory-dev-dashboard-killed](https://user-images.githubusercontent.com/2692678/179042946-a9409203-4fbb-47fa-9319-45ff5021cdb1.png)

---

This bug blocks me from completing my task. We wish to have the dashboard in production. We need the head node to be stable for at least a week due to long-running payloads behind Serve.

### Versions / Dependencies

* Python 3.8.12
* Ray 1.13.0
* Kubernetes 1.22.0
* Google Kubernetes Engine and Rancher managed k8s test instances

### Reproduction script

Run this script on the head node and collect the log file. Supply the script command with the dashboard's process ID.

```bash
#!/bin/bash

if [ -z "$1" ]; then
    echo "ERROR: must provide pid as argument"
    exit 1
fi

pidToMonitor="$1"
outFile="pid_monitor.log"

# write header
echo "VIRT RES SHR" > ${outFile}
# write values
while true; do
    cat /proc/${pidToMonitor}/statm | tr ' ' '\n' | head -n3 | xargs -I{} bash -c 'echo $(( {} * 4 ))' | tr '\n' ' ' >> ${outFile}
    echo >> ${outFile}
    sleep 30
done
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
cc @architkulkarni to investigate

**Comment by mihajenko** [comment]
@rkooo567 @architkulkarni The symptom persists on ray 2.0.0 with our setup. That is, the dashboard.py Python memory keeps growing. Although I am unsure if it only affects heap Python memory.

**Comment by architkulkarni** [comment]
Thanks for the update and sorry for the delay, we'll try to fix this soon!

**Comment by architkulkarni** [comment]
The root cause is that the Serve controller emits the following error about every 20 seconds:

`'ray::ServeController.listen_for_change() (pid=37658, ip=127.0.0.1, repr=<ray.serve.controller.ServeController object at 0x7f8f594302e0>)\n  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/concurrent/futures/_base.py", line 437, in result\n    return self.__get_result()\n  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result\n    raise self._exception\n  File "/Users/archit/ray/python/ray/serve/controller.py", line 185, in listen_for_change\n    return await (self.long_poll_host.listen_for_change(keys_to_snapshot_ids))\n  File "/Users/archit/ray/python/ray/serve/_private/long_poll.py", line 249, in listen_for_change\n    raise asyncio.TimeoutError("Polling request timed out.")\nasyncio.exceptions.TimeoutError: Polling request timed out.
`

This is expected with normal functioning of the Serve controller (@simon-mo should we change this to an INFO log instead of an error?)

The dashboard stores the last 10000 error messages in memory. (https://github.com/ray-project/ray/blob/master/dashboard/modules/node/node_consts.py#L11) 

Since this error message is about 1kb, it grows about 5 MB per hour until it reaches ~10GB.

To fix this we can
1. Limit the total size rather than the total number of error messages.  The downside is that if some error messages are really long (e.g. they contain some long traceback), fewer errors will be stored.
2. Catch the Serve controller error to prevent it propagating to the dashboard

**Comment by simon-mo** [comment]
This error can be prevented within Ray Serve. @sihanwang41 I remember you looked into changing this error before once? Was there any WIP code? Otherwise I can submit a PR.

**Comment by sihanwang41** [comment]
Hi @simon-mo , go ahead, I don't have any wip code in this issue.
IIRC https://github.com/ray-project/ray/issues/27677
we should not see this error any more since the exception log has been under DEBUG level?

**Comment by architkulkarni** [comment]
We don't see the log statement for this error in the driver anymore, but the underlying error is still being raised and being saved by the dashboard.

**Comment by mihajenko** [comment]
cc @rgiacomin

**Comment by simon-mo** [comment]
@mihajenko I have merged a change. You can use the nightly wheels to alleviate this issue. Please feel free to test it out!

**Comment by mihajenko** [comment]
@simon-mo This issue is still not resolved. We continue to observe the described linear (RSS) memory growth in `python dashboard.py` process.

We are testing with `aiohttp==3.8.3` (latest stable). We noticed that the pip's ray upgrade command bumped it to `aiohttp==4.0.0a1`. This produces a bug because aiohttp deprecated the `ClientSession`'s `loop` kwarg, so we downgraded to 3.8.3. Hopefully aiohttp 4 is not a requirement for this bug fix, otherwise the dashboard code needs an upgrade.

**Comment by architkulkarni** [comment]
Thanks, we'll look into this.  

@mihajenko What's the pip ray upgrade command that caused an incompatibility? We probably just need to pin something in `requirements.txt`.

As for the initial period of memory growth, I'm not aware of anything like that but I'll let you know if we find anything.

**Comment by mihajenko** [comment]
@architkulkarni It was `pip install -U ray[default,serve] @ (py38 nightly URL)` (following the docs).

But my observation about the aiohttp bump was probably false (since version 4.0.0a is alpha). Anyway, the memory leak is being observed on 3.8.3.

**Comment by architkulkarni** [comment]
Gotcha, yeah I ran the same command in a fresh conda env and got `aiohttp==3.8.3`.  We'll try to reproduce the memory leak.

**Comment by rkooo567** [comment]
is this closeable @architkulkarni ?

**Comment by architkulkarni** [comment]
I ran the repro in this issue for a few hours on the nightly and didn't detect any leak, so I think we can close this issue. It was likely fixed by https://github.com/ray-project/ray/pull/29187
