### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#2685]
I am still debugging this but I am posting this here to see if I can get any pointers. I also do not have a reproduction.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 17.10
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.0
- **Python version**: 3.6.3

### Describe the problem

So sometimes I run code through Ray I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/import_thread.py", line 131, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
EOFError: Ran out of input
```

And then things do not work in strange ways.

**Comment by robertnishihara** [comment]
Hmm, could you try adding a print statement right before the `function = pickle.loads(serialized_function)` line so that we can see what it's trying to deserialize? That seems really weird.

Actually, if you do

```python
r = ray.worker.global_worker.redis_client
export_keys = r.lrange('Exports', 0, -1)
items = [r.hgetall(k) for k in export_keys]
```

You can loop over `items` and try to do

```python
[ray.worker.pickle.loads(item[b'function']) for item in items]
```

or something like that and see if that causes the error.

**Comment by mitar** [comment]
Function seems to be only `b'\x80\x04'`.

**Comment by mitar** [comment]
The `[ray.worker.pickle.loads(item[b'function']) for item in items]` displays an exception though (not sure because it is pickled and it unpickles it or something), which is pointing to an issue with cloudpickle: `can't pickle _thread.lock objects`.

I think the reproduction is as follows:

* I have some global state in my modules protected with lock objects.
* I call some Ray tasks which among other set locks.
* i call more tasks which try to get pickled, but now locks are initialized, so new tasks fail to be pickled.
* This error is nowhere to be reported.
* But it fails when trying to unpickle.
* But I can see them through code above.

**Comment by mitar** [comment]
Correction, `can't pickle _thread.lock objects` seems to be there even before `EOFError: Ran out of input` starts appearing. So it looks unrelated. Also, not sure why locks are a problem because they are defined in another Python file/module. I through Ray pickles only code inside Python file/module of the function with `@ray.remote` decorator.

**Comment by mitar** [comment]
BTW, I have a pretty stable reproduction locally on my system, but I have no idea how to make a small stand-alone one.

**Comment by robertnishihara** [comment]
@mitar and I just looked into this a little more.

Interestingly, if you modify

https://github.com/ray-project/ray/blob/f4f3478b45ac047bc354470244f065f0889c4a48/python/ray/worker.py#L691-L692

to add 

```python
pickle.loads(pickled_function)
```

right after `pickle.dumps`, then it fails right there (because `pickled_function` is `b'\x80\x04'`). So the error is happening with the call to `pickle.dumps`.

If we try it in a loop, e.g.,

```python
while True:
    pickled_function = pickle.dumps(function)
    try:
        pickle.loads(pickled_function)
    except:
        print("Failed to load")
    else:
        break
```

then that seems to "fix" the issue. The call to `pickle.loads` may fail on the first try but will work in subsequent passes through the loop.

It seems like the issue must be related to some threading or something weird.

**Comment by mitar** [comment]
Any update here?

**Comment by robertnishihara** [comment]
No updates.

**Comment by suquark** [comment]
Finally, I figured out what happens here. It is a **serious** bug and it is hidden deep.

There are at least two things could happen concurrently in Ray:
* A worker is trying to export a remote function. It will use `cloudpickle` to serialize the function.
* An import thread is trying to a execute remote function, it could import a new module.

When pickling functions, `cloudpickle` will try to ensure a de-pickler imports any package child-modules that are needed by the function by iterating over `sys.modules`:
https://github.com/ray-project/ray/blob/32676769949ae8f53bbdf36e4af693e79a0f2ba1/python/ray/cloudpickle/cloudpickle.py#L435

However, an import thread will change `sys.modules` when trying to import a new module. It violates python’s assumption that a being iterated dict should not be changed, raising a `RuntimeError`.

However, `cloudpickle` just ignores(!!!) any `RuntimeError` it does not know:
https://github.com/ray-project/ray/blob/32676769949ae8f53bbdf36e4af693e79a0f2ba1/python/ray/cloudpickle/cloudpickle.py#L269-L272

So in this case, `cloudpickle` will return a byte string only with its head  `b'\x80\x04'`
Then this string will be sent to other workers through redis, causing them crash.

The solution is quite easy: make a shallow copy of `sys.modules` before iterating over them.
I feel very lucky to find this bug. It is hidden deep. We catch it because we import so many primitives and use complex functions for remote tasks.

**Comment by mitar** [comment]
This would require change to cloudpickle, no? Does Ray use upstream cloudpickle or a fork?

**Comment by robertnishihara** [comment]
Wow nice job finding that, that's really subtle.

We have a copy of cloudpickle in https://github.com/ray-project/ray/tree/master/python/ray/cloudpickle.

**Comment by mitar** [comment]
Can we then just do a PR against the copy? Should we also send PR upstream?

**Comment by robertnishihara** [comment]
The same issue has come up in cloudpickle https://github.com/cloudpipe/cloudpickle/issues/129 and looks like it has been fixed in https://github.com/cloudpipe/cloudpickle/commit/9040b162253047bb062fd77866c2a7a6aa2df5a6.

Updating cloudpickle in https://github.com/ray-project/ray/pull/2928.

**Comment by robertnishihara** [comment]
However, it's possible that there are other issues of this form that could arise from multithreading on the driver. We should be able to prevent this from happening on the workers because the workers can grab locks when doing non-thread-safe stuff, but the driver is just user code and won't grab any locks, so the longer-term solution may be to simply remove the import thread on the driver.

**Comment by robertnishihara** [comment]
@suquark great job tracking this down, that was really subtle.

**Comment by mitar** [comment]
So what is the status of this being fixed?

**Comment by robertnishihara** [comment]
There's a fix in https://github.com/ray-project/ray/pull/2928, but that seems to introduce another pickling error (described in the PR). If you or anyone have time to look into that that would be helpful.

**Comment by robertnishihara** [comment]
This should finally be fixed by #3964.

**Comment by Coder-Atul** [comment]
I still get the same error. 
Please see my code below and tell me what is my mistake.
Even though I have the latest version of pip and cloudpickle installed.

`import cloudpickle as cp
import pickle as p

file= open('file5','wb+')
book={}

bookname = ['Liot','Ravi','Kio','Hari','Minalanka','Rolce','Jimo','lina']
aut=       ['Jim','Oli' ,"Oli","kai","Lora"      ,'Oli','GArt',"Bcan"]
print('bookname:',len(bookname))
print('author:',len(aut))

for i in range(1,9):
    book[aut[i-1]]=[i,bookname[i-1]]

cp.dump(book,file)
name= input('Name of author:')
try:
    db=p.loads(file)
    for key in db:
        print(db[key])
    #if key==name:
    #    print(db[key])

except :
    print("not loaded")



file.close()`

**Comment by sameet96** [comment]
Try it with file= open('file5','rb')
