### ISSUE TITLE
Methods on actors inherited from built-in classes are not visible

### ISSUE THREAD

**Issue by rshin** [ray-project/ray#278]
For example, given

```python
import ray

ray.init()

@ray.actor
class MySet(set):
  pass
```
then `MySet.add` will not work.

**Comment by robertnishihara** [comment]
Good point, we should fix this.

At least for now it gives a reasonable error message. 

```python
AttributeError: type object 'NewClass' has no attribute 'add'
```

**Comment by ChihweiLHBird** [comment]
Is `@ray.actor` still a public API? Couldn't find in the docs.

It still doesn't work with `@ray.remote` though.

```python
import ray

ray.init()

@ray.remote
class MySet(set):
  pass

obj = MySet.remote()
obj.add.remote(1)

```

I would like to work on this issue. I am new to here, and may I have some advice about how to fix it? lol

**Comment by stephanie-wang** [comment]
As a workaround, you can create your own methods that just call the superclass method.

```python
import ray

@ray.remote
class MySet(set):
    def add(self, *args):
        return super().add(*args)


s = MySet.remote()
ray.get(s.add.remote(1))
```

**Comment by cszhu** [comment]
This P3 issue has seen no activity in the past year. It will be closed in 2 weeks as part of ongoing cleanup efforts. 
Please comment and remove the `pending-cleanup` label if you believe this issue should remain open. 
Thanks for contributing to Ray!
