### ISSUE TITLE
[Core]  dataset_shuffle_random_shuffle_1tb failed with OOM killer 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#28273]
### What happened + What you expected to happen

https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_SZHAAt92EMwZJf1ndBXfLUCS?command-history-section=command_history

Note that there was an issue with Ray OOM killer that causes the segfault, but it was fixed by @clarence-wu 

Another issue is that the fact that OOM killer was triggered means there's something wrong with the test (maybe RAM usage is too high, or we are using too small machines). It's ideal we fix this issue. 

### Versions / Dependencies

master

### Reproduction script

N/A

**Comment by clarng** [comment]
the segfault is addressed by this PR https://github.com/ray-project/ray/pull/28271

**Comment by rkooo567** [comment]
Let's close it when the segfault is addressed. According to @stephanie-wang the test itself is written in a way it triggers OOM (so that it can test app-level fault tolerance)

**Comment by stephanie-wang** [comment]
@clarng, FYI the test is still failing on a commit that includes the fix.

https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_gNAxCWnnUQrspDmJtzHawCT9?command-history-section=command_history

**Comment by stephanie-wang** [comment]
Upgrading to p0 since we no longer know the cause.

**Comment by clarng** [comment]
Actually the memory monitor is not enabled

I discovered this while trying to do release testing, but it seems the nightly build does not have the latest changes

**Comment by clarng** [comment]
<img width="1436" alt="Screen Shot 2022-09-07 at 2 32 23 PM" src="https://user-images.githubusercontent.com/22830327/188985752-6763cbf6-a2a9-4cc7-bd7f-07e3f6573652.png">

**Comment by clarng** [comment]
Since the threading issue only happens when memory monitor is enabled I think there is something else going on, I think we should file a separate issue to track it as such

**Comment by stephanie-wang** [comment]
Hmm are you sure it's not enabled in the nightly tests? I see the right error messages:
```
Shuffle Reduce:  20%|█▉        | 195/1000 [03:49<02:16,  5.88it/s](raylet, ip=172.31.70.72) [2022-09-05 16:38:36,260 E 134 182] (raylet) node_manager.cc:2963: System memory low at node with IP 172.31.70.72. Used memory (56.08GB) / total capacity (62.02GB) (0.904175) exceeds threshold 0.9, killing latest task with name reduce() and task ID ea4117e8509509f14ede7929b434b62377f0fc2102000000 to avoid running out of memory.
```

**Comment by clarng** [comment]
The shuffle test doesn't have it enabled per the logs in https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_gNAxCWnnUQrspDmJtzHawCT9?command-history-section=command_history

In another test it is enabled

https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_eerxy7PSk7y8k2xXQCFRF44Y

So two issues
* the memory monitor was not enabled when it is expected to for this test
* the test is failing even the monitor is disabled

We can keep this issue open but I'll reword since it is not related to oom killer (it is disabled)

**Comment by stephanie-wang** [comment]
Passing now.
