### ISSUE TITLE
[Ray component: Core] Returning to much data from ray remote fails with no error

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [ray-project/ray#28855]
### What happened + What you expected to happen

When using ray with multiple nodes, if too much data is returned from a ray remote command, it will silently fail. The script works if I only send about 3 MB, but never finishes if I send about 35 MB.

I would have expected either the data to be returned, or an error to be called.

Error logs:
```
r6i0n8/ray/session_2022-09-28_09-05-55_210275_199975/logs/worker-cac22fc00b6a6f07c10ed16c473cde549ea7f5f5ee260b6c0df60a9f-01000000-42749.err

:task_name:f
:task_name:f
:task_name:f
:task_name:f

r6i0n8/ray/session_2022-09-28_09-05-55_210275_199975/logs/raylet.err

[2022-09-28 09:08:54,754 I 42511 42511] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
/home/fred/miniconda3/envs/ray2/lib/python3.10/site-packages/ray/dashboard/agent.py:50: DeprecationWarning: There is no current event loop
  aiogrpc.init_grpc_aio()
/home/fred/miniconda3/envs/ray2/lib/python3.10/site-packages/ray/dashboard/agent.py:470: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
[2022-09-28 09:09:55,681 I 42749 42749] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1

r6i0n5/ray/session_2022-09-28_09-05-55_210275_199975/logs/gcs_server.err

[2022-09-28 09:05:55,395 I 199982 199982] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1

r6i0n5/ray/session_2022-09-28_09-05-55_210275_199975/logs/monitor.err

<blank>

r6i0n5/ray/session_2022-09-28_09-05-55_210275_199975/logs/ray_client_server.err

2022-09-28 09:05:57,732	INFO server.py:875 -- Starting Ray Client server on 0.0.0.0:10001

r6i0n5/ray/session_2022-09-28_09-05-55_210275_199975/logs/raylet.err

[2022-09-28 09:05:57,944 I 200051 200051] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
/home/fred/miniconda3/envs/ray2/lib/python3.10/site-packages/ray/dashboard/agent.py:50: DeprecationWarning: There is no current event loop
  aiogrpc.init_grpc_aio()
/home/fred/miniconda3/envs/ray2/lib/python3.10/site-packages/ray/dashboard/agent.py:470: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
[2022-09-28 09:09:55,394 I 200751 200751] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1

r6i0n5/ray/session_2022-09-28_09-05-55_210275_199975/logs/worker-2b96cc95c364435ffeed6d0e063c9bf739017f406eb3340831692108-01000000-200751.err

:task_name:f
:task_name:f
:task_name:f
:task_name:f
:task_name:f

r6i0n6/ray/session_2022-09-28_09-05-55_210275_199975/logs/raylet.err

[2022-09-28 09:08:46,201 I 142729 142729] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
/home/fred/miniconda3/envs/ray2/lib/python3.10/site-packages/ray/dashboard/agent.py:50: DeprecationWarning: There is no current event loop
  aiogrpc.init_grpc_aio()
/home/fred/miniconda3/envs/ray2/lib/python3.10/site-packages/ray/dashboard/agent.py:470: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
[2022-09-28 09:09:55,706 I 142952 142952] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1


r6i0n6/ray/session_2022-09-28_09-05-55_210275_199975/logs/worker-7c1fa41076c2144bc6f346fe79b34e660a50b03c0cee07b65f849af9-01000000-142952.err

:task_name:f
:task_name:f
:task_name:f
:task_name:f
:task_name:f

r6i0n7/ray/session_2022-09-28_09-05-55_210275_199975/logs/raylet.err

[2022-09-28 09:08:50,585 I 678 678] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
/home/fred/miniconda3/envs/ray2/lib/python3.10/site-packages/ray/dashboard/agent.py:50: DeprecationWarning: There is no current event loop
  aiogrpc.init_grpc_aio()
/home/fred/miniconda3/envs/ray2/lib/python3.10/site-packages/ray/dashboard/agent.py:470: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
[2022-09-28 09:09:55,705 I 934 934] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1

r6i0n7/ray/session_2022-09-28_09-05-55_210275_199975/logs/worker-583d3c201a1210ca60ad8c3c4f22bfd3ec142c274fea9994254b916f-01000000-934.err

:task_name:f
:task_name:f
:task_name:f
:task_name:f
:task_name:f
```

Example ray status:
```
======== Autoscaler status: 2022-09-28 10:07:42.414953 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_27e755084af7f73016444da0200624a76a7d9816cc043cf6156854b6
 1 node_e812a504aab06bf5b1cb806b635871150d3751053c68e64c4d5486d7
 1 node_9be56595261dbbb05d4104badaaa1e212cbd88d0bb962da0e99c1f38
 1 node_9326d17bcf82ecbc56b8a45b883add2f33cd5a62257829aae60ee90f
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/4.0 CPU
 0.00/486.155 GiB memory
 0.12/212.344 GiB object_store_memory

Demands:
 (no resource demands)

```

### Versions / Dependencies

conda list:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aiohttp                   3.8.1                    pypi_0    pypi
aiohttp-cors              0.7.0                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
blessed                   1.19.1                   pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.6.15                pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.0.4                    pypi_0    pypi
colorful                  0.5.4                    pypi_0    pypi
distlib                   0.3.5                    pypi_0    pypi
filelock                  3.8.0                    pypi_0    pypi
frozenlist                1.3.1                    pypi_0    pypi
google-api-core           2.10.0                   pypi_0    pypi
google-auth               2.11.0                   pypi_0    pypi
googleapis-common-protos  1.56.4                   pypi_0    pypi
gpustat                   1.0.0                    pypi_0    pypi
grpcio                    1.43.0                   pypi_0    pypi
idna                      3.3                      pypi_0    pypi
jsonschema                4.14.0                   pypi_0    pypi
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.39.2               h753d276_1    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
msgpack                   1.0.4                    pypi_0    pypi
multidict                 6.0.2                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.23.2                   pypi_0    pypi
nvidia-ml-py              11.495.46                pypi_0    pypi
opencensus                0.11.0                   pypi_0    pypi
opencensus-context        0.1.3                    pypi_0    pypi
openssl                   3.0.5                h166bdaf_1    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.2                    pypi_0    pypi
prometheus-client         0.13.1                   pypi_0    pypi
protobuf                  3.20.1                   pypi_0    pypi
psutil                    5.9.2                    pypi_0    pypi
py-spy                    0.3.14                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pydantic                  1.10.2                   pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
python                    3.10.6          ha86cf86_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pyyaml                    6.0                      pypi_0    pypi
ray                       2.0.0                    pypi_0    pypi
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
setuptools                65.3.0          py310hff52083_0    conda-forge
six                       1.16.0                   pypi_0    pypi
smart-open                6.1.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
typing-extensions         4.3.0                    pypi_0    pypi
tzdata                    2022c                h191b570_0    conda-forge
urllib3                   1.26.12                  pypi_0    pypi
virtualenv                20.16.3                  pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yarl                      1.8.1                    pypi_0    pypi
```

### Reproduction script

Creation of environment:
```bash
conda create --name ray2
conda activate ray2
conda install --name ray2 pip
pip install ray==2.0.*
```

Running test (note that PBS_NODEFILE is a list of nodes available to use):
```bash
source /home/fred/miniconda3/etc/profile.d/conda.sh
conda activate ray2


export RAY_BACKEND_LOG_LEVEL=debug

ray start --head --num-cpus=1 --port=0

export RAY_ADDRESS=<based on above output>

for NODE in `cat $PBS_NODEFILE | uniq`; do
    if echo $NODE | grep -q `hostname`; then
        echo skipping $NODE;
    else
       echo $NODE
       ssh $NODE /home/fred/ray_start3.sh 1 $RAY_ADDRESS
    fi
done

python ray_test7s.py
```
ray_start3.sh
```bash
#!/bin/bash

source /home/fred/miniconda3/etc/profile.d/conda.sh
conda activate ray2

NUM_CPUS=$1
HEAD_ADDRESS=$2

export RAY_BACKEND_LOG_LEVEL=debug
ray start --verbose --address=$HEAD_ADDRESS --num-cpus $NUM_CPUS
```

ray_test7s.py
```python
import ray
import time
import gc
import threading
ray.init(address='auto')

start = time.time()

class MemUser:
    def __init__(self, v):
        self.v = v
        #[0]*15*1024 takes about 10KB
        self.extra = [0]*15*1024*300
    def __str__(self):
        return f"MemUser({self.v})"

@ray.remote
def f(x):
    a = [2**2**2**2**2 for x in range(100000)]
    return MemUser(x * x)

print("starting remote functions")
futures = [f.remote(i) for i in range(19)]
print("remotes started")
left = len(futures)
needed_to_finish = len(futures)
outputs = [None]*left

lowest_running = 0
while lowest_running  < needed_to_finish:
    lowest_running = len(futures)
    for i in range(len(futures)):
        if futures[i] is not None:
            if i < lowest_running:
                lowest_running = i
            try:
                fi = futures[i]
                runReturn = ray.get(fi, timeout=1e-10)
                print(i, runReturn, left, len(gc.get_referrers(fi)))
                left += -1
                outputs[i] = runReturn
                futures[i] = None
                del fi
            except ray.exceptions.GetTimeoutError:
                pass

print(outputs) # [0, 1, 4, 9]
print(lowest_running)
end = time.time()
print("time: ",end - start)

```

The entire output of the script after running for an hour (note that it all came within the first two minutes):
```
python ray_test7s.py
2022-09-28 09:09:54,775 INFO worker.py:1223 -- Using address 10.159.20.12:34435 set in the environment variable RAY_ADDRESS
2022-09-28 09:09:54,775 INFO worker.py:1333 -- Connecting to existing Ray cluster at address: 10.159.20.12:34435...
2022-09-28 09:09:54,781 INFO worker.py:1509 -- Connected to Ray cluster. View the dashboard at 127.0.0.1:8265 
[2022-09-28 09:09:54,782 I 200719 200719] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
starting remote functions
remotes started
(raylet) [2022-09-28 09:09:55,394 I 200751 200751] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
(raylet, ip=10.159.20.16) [2022-09-28 09:09:55,705 I 934 934] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
(raylet, ip=10.159.20.18) [2022-09-28 09:09:55,681 I 42749 42749] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
(raylet, ip=10.159.20.14) [2022-09-28 09:09:55,706 I 142952 142952] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
(scheduler +12s) Tip: use `ray status` to view detailed cluster status. To disable these messages, set RAY_SCHEDULER_EVENTS=0.
0 MemUser(0) 19 2
4 MemUser(16) 18 2
8 MemUser(64) 17 2
12 MemUser(144) 16 2
16 MemUser(256) 15 2
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by hora-anyscale** [comment]
@stephanie-wang - could you confirm if this is duplicate to the OOM killer work, if so please close out.

**Comment by ericl** [comment]
I believe this issue should be fixed in 2.1 with the OOM monitor (cc @clarng)--- you should get a task killed with out of memory instead.

**Comment by hora-anyscale** [comment]
Per Triage Sync: @clarng please confirm if still an issue

**Comment by joshua-cogliati-inl** [comment]
This is still a problem in ray 2.1.  I checked with python 3.10.8 and:
```
$ pip list
Package            Version
------------------ ---------
aiosignal          1.3.1
attrs              22.1.0
certifi            2022.12.7
charset-normalizer 2.1.1
click              8.0.4
distlib            0.3.6
filelock           3.8.2
frozenlist         1.3.3
grpcio             1.51.1
idna               3.4
jsonschema         4.17.3
msgpack            1.0.4
numpy              1.23.5
packaging          22.0
pip                22.3.1
platformdirs       2.6.0
protobuf           4.21.11
pyrsistent         0.19.2
PyYAML             6.0
ray                2.1.0
requests           2.28.1
setuptools         65.5.1
six                1.16.0
urllib3            1.26.13
virtualenv         20.17.1
wheel              0.38.4
```

**Comment by cszhu** [comment]
This P2 issue has seen no activity in the past 2 years. It will be closed in 2 weeks as part of ongoing cleanup efforts.

Please comment and remove the `pending-cleanup` label if you believe this issue should remain open.

Thanks for contributing to Ray!
