### ISSUE TITLE
ray stop doesn't clear memory?

### ISSUE THREAD

**Issue by yaroslavvb** [ray-project/ray#2917]
I'm getting out of memory error when running experiment twice on the same set of machines.

My workflow for each run is:

```
ray stop
ray start ...
python my_ray_program.py
```
The second time I do ray start I see this

```
Reducing object store memory because /dev/shm has only 245919744 bytes available. You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
```

Then when running the program (a simple benchmark that adds 100MB tensors to parameter server), I get:

```
Remote function compute_gradients failed with:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 951, in _process_task
    self._store_outputs_in_objstore(return_object_ids, outputs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 879, in _store_outputs_in_objstore
    self.put_object(object_ids[i], outputs[i])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 394, in put_object
    self.store_and_register(object_id, value)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 329, in store_and_register
    self.task_driver_id))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/utils.py", line 324, in _wrapper
    return orig_attr(*args, **kwargs)
  File "pyarrow/_plasma.pyx", line 398, in pyarrow._plasma.PlasmaClient.put
  File "pyarrow/_plasma.pyx", line 302, in pyarrow._plasma.PlasmaClient.create
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.PlasmaStoreFull: object does not fit in the plasma store
```

Observed when running this benchmark: https://github.com/diux-dev/ncluster/blob/master/benchmarks/ray_two_machines.py

**Comment by robertnishihara** [comment]
Can you do `ps aux | grep plasma_store_server` to see if there is still a plasma store running? I think `ray stop` wasn't killing the plasma store, though that should have been fixed by https://github.com/ray-project/ray/pull/2850. Are you using the nightly wheels?

**Comment by yaroslavvb** [comment]
I'm using `pip install ray` which I think is 0.5.2
Indeed, after `ray stop`, I still see 3 plasma processes running

Is there a `pip install`able version of ray nightly?

**Comment by robertnishihara** [comment]
Yep see https://ray.readthedocs.io/en/latest/installation.html#trying-the-latest-version-of-ray

E.g.,

```
pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.5.2-cp36-cp36m-manylinux1_x86_64.whl
```

**Comment by yaroslavvb** [comment]
thanks, this seems fixed
