### ISSUE TITLE
[Datasets] `Dataset.limit` doesn't work with ragged tensors

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#30060]
### What happened + What you expected to happen

I tried to limit the size of my dataset so I could debug easily. I got an error instead.

> ValueError: ArrowVariableShapedTensorArray only supports heterogeneous-shaped tensor collections, not arbitrarily nested ragged tensors.

See repro.

### Versions / Dependencies

Ray: 3a77c7356be3c4b0d2d9d2112716d4b6ae22a7ec

### Reproduction script

```
>>> import ray
>>> ds = ray.data.read_images("s3://air-example-data-2/imagenet-sample-images/")
2022-11-07 10:55:22,629	INFO worker.py:1528 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
>>> ds.limit(10)
(_split_single_block pid=8869) 2022-11-07 10:55:42,076	INFO worker.py:763 -- Task failed with retryable exception: TaskID(e0dc174c83599034ffffffffffffffffffffffff01000000).
(_split_single_block pid=8869) Traceback (most recent call last):
(_split_single_block pid=8869)   File "python/ray/_raylet.pyx", line 865, in ray._raylet.execute_task
(_split_single_block pid=8869)     with ray._private.worker._changeproctitle(title, next_title):
(_split_single_block pid=8869)   File "python/ray/_raylet.pyx", line 869, in ray._raylet.execute_task
(_split_single_block pid=8869)     outputs = function_executor(*args, **kwargs)
(_split_single_block pid=8869)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/split.py", line 121, in _split_single_block
(_split_single_block pid=8869)     split_block = block_accessor.slice(prev_index, index, copy=True)
(_split_single_block pid=8869)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/arrow_block.py", line 175, in slice
(_split_single_block pid=8869)     view = _copy_table(view)
(_split_single_block pid=8869)   File "/Users/balaji/Documents/GitHub/ray/python/ray/data/_internal/arrow_block.py", line 618, in _copy_table
(_split_single_block pid=8869)     arr = _concatenate_extension_column(col)
(_split_single_block pid=8869)   File "/Users/balaji/Documents/GitHub/ray/python/ray/air/util/transform_pyarrow.py", line 34, in _concatenate_extension_column
(_split_single_block pid=8869)     return ArrowTensorArray._concat_same_type(ca.chunks)
(_split_single_block pid=8869)   File "/Users/balaji/Documents/GitHub/ray/python/ray/air/util/tensor_extensions/arrow.py", line 306, in _concat_same_type
(_split_single_block pid=8869)     return ArrowVariableShapedTensorArray.from_numpy(
(_split_single_block pid=8869)   File "/Users/balaji/Documents/GitHub/ray/python/ray/air/util/tensor_extensions/arrow.py", line 562, in from_numpy
(_split_single_block pid=8869)     raise ValueError(
(_split_single_block pid=8869) ValueError: ArrowVariableShapedTensorArray only supports heterogeneous-shaped tensor collections, not arbitrarily nested ragged tensors. Got: [array([[[65, 81, 78],

...
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by clarkzinzow** [comment]
Fixed by https://github.com/ray-project/ray/pull/30080

**Comment by hanweidong** [comment]
Hello：
        I tried to use dataset.map_batches method to process numpy to get ArrowTensorType in version 2.2. But the problem still occurs: "ValueError: ArrowVariableShapedTensorArray only supports heterogeneous-shaped tensor collections, not arbitrarily nested ragged tensors."

**Comment by bveeramani** [comment]
Hey @hanweidong, could you create a new issue with a repro script?
