### ISSUE TITLE
[Test] gcs_placement_group_manager_test flaky in the master 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#30573]
### What happened + What you expected to happen

<img width="675" alt="Screen Shot 2022-11-21 at 9 14 14 PM" src="https://user-images.githubusercontent.com/18510752/203227454-0fa0f4b1-f8b3-4019-9dfc-e88a354229b3.png">

After merging this PR, `test_placement_group` became flaky. We should investigate and fix it. 

cc @xwjiang2010 I will mark it as a release blocker until we find the root cause. 

cc @larrylian 

### Versions / Dependencies

master

### Reproduction script

n/a

**Comment by larrylian** [comment]
I will look at this issue. It should be the issue introduced by #24875 PR. Now it may be related to multi-threaded execution.

**Comment by larrylian** [comment]
#30577    I have fix this case,  I will see if this use case CI can run successfully tomorrow.

**Comment by cadedaniel** [comment]
I don't understand if #30577 fixes the root cause or not but FYI `TestRemovingLeasingPlacementGroup` recently failed due to threading issues, if they're related then we should fix the root problem (multithreaded usage on a non-thread-safe class). I'm happy to help with that if it's a release blocker.

The hacky fix for `TestRemovingLeasingPlacementGroup` was to sleep to avoid a race https://github.com/ray-project/ray/pull/29694

**Comment by rkooo567** [comment]
We merged the PR. Let's see if it becomes unflaky after that

**Comment by rkooo567** [comment]
I will also add more tests as a follow up. So we shouldn't close this (but just downgrade the priority)

**Comment by xwjiang2010** [comment]
Sounds good, dropping release-blocking. Just FYI, still happens from time to time on release branch: https://buildkite.com/ray-project/oss-ci-build-branch/builds/1306#0184c0a2-9b0c-4ce7-905c-bb016a34d56d

**Comment by xwjiang2010** [comment]
Just confirming is this still release blocking or we can drop it?

**Comment by rkooo567** [comment]
Can you give me one more day for this? I will sort that out by today.

**Comment by rkooo567** [comment]
(is this the last blocker?)

**Comment by larrylian** [comment]
> Hmm I guess this is not fixed by that PR... Let me take a look tomorrow.

I looked at the few flakey's, maybe the branch code is relatively old and didn't bring my fix PR.
