### ISSUE TITLE
[dashboard] Dashboard showing empty screen 

### ISSUE THREAD

**Issue by davzaman** [ray-project/ray#31907]
### What happened + What you expected to happen

Similar bug to #15650 and others.

After spinning up ray in python with `ray.init(include_dashboard=True, logging_level=logging.DEBUG)`, I successfully get the following line: `2023-01-24 14:10:49,581 INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 `.
If I navigate to that link, the dashboard appears for less than a second and then disappears. I can't mess with the url to get any other outcome except to get 404 not found.

<details>
<summary>If I inspect the page and view the console I see the following output (expand)</summary>

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
32react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'find')
    at GRAMColumn.tsx:43:37
    at Array.map (<anonymous>)
    at ee (GRAMColumn.tsx:42:6)
    at oo (react-dom.production.min.js:157:137)
    at Ws (react-dom.production.min.js:267:460)
    at xl (react-dom.production.min.js:250:347)
    at Il (react-dom.production.min.js:250:278)
    at Ol (react-dom.production.min.js:250:138)
    at hl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
us @ react-dom.production.min.js:216
GRAMColumn.tsx:43 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'find')
    at GRAMColumn.tsx:43:37
    at Array.map (<anonymous>)
    at ee (GRAMColumn.tsx:42:6)
    at oo (react-dom.production.min.js:157:137)
    at Ws (react-dom.production.min.js:267:460)
    at xl (react-dom.production.min.js:250:347)
    at Il (react-dom.production.min.js:250:278)
    at Ol (react-dom.production.min.js:250:138)
    at hl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
```
</details>

<details>
<summary>If I dig into the javascript I see the relevant lines are: </summary>

```javascript
export const WorkerGRAM = ({
  worker,
  node,
}: {
  worker: Worker;
  node: NodeDetail;
}) => {
  const workerGRAMEntries = (node.gpus ?? [])
    .map((gpu, i) => {
      const process = gpu.processes.find(
        (process) => process.pid === worker.pid,
      );
```
</details>

Meaning `gpu.processes` is `null` for some reason.

The logs don't tell me anything interesting:

<details>
<summary>`$ cat  /tmp/ray/session_latest/logs/dashboard_agent.log`</summary>

```shell
2023-01-24 14:19:20,104 INFO agent.py:105 -- Parent pid is 31319
2023-01-24 14:19:20,105 INFO agent.py:131 -- Dashboard agent grpc address: 0.0.0.0:35070
2023-01-24 14:19:20,108 INFO utils.py:112 -- Get all modules by type: DashboardAgentModule
2023-01-24 14:19:20,432 INFO utils.py:145 -- Available modules: [<class 'ray.dashboard.modules.event.event_agent.EventAgent'>, <class 'ray.dashboard.modules.healthz.healthz_agent.HealthzAgent'>, <class 'ray.dashboard.modules.job.job_agent.JobAgent'>, <class 'ray.dashboard.modules.log.log_agent.LogAgent'>, <class 'ray.dashboard.modules.log.log_agent.LogAgentV1Grpc'>, <class 'ray.dashboard.modules.reporter.reporter_agent.ReporterAgent'>, <class 'ray.dashboard.modules.runtime_env.runtime_env_agent.RuntimeEnvAgent'>, <class 'ray.dashboard.modules.serve.serve_agent.ServeAgent'>]
2023-01-24 14:19:20,433 INFO agent.py:160 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.event.event_agent.EventAgent'>
2023-01-24 14:19:20,433 INFO event_agent.py:38 -- Event agent cache buffer size: 10240
2023-01-24 14:19:20,433 INFO agent.py:160 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.healthz.healthz_agent.HealthzAgent'>
2023-01-24 14:19:20,433 INFO agent.py:160 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.job.job_agent.JobAgent'>
2023-01-24 14:19:20,433 INFO agent.py:160 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.log.log_agent.LogAgent'>
2023-01-24 14:19:20,435 INFO agent.py:160 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.log.log_agent.LogAgentV1Grpc'>
2023-01-24 14:19:20,435 INFO agent.py:160 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.reporter.reporter_agent.ReporterAgent'>
2023-01-24 14:19:20,438 INFO agent.py:160 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.runtime_env.runtime_env_agent.RuntimeEnvAgent'>
2023-01-24 14:19:20,438 INFO agent.py:160 -- Loading DashboardAgentModule: <class 'ray.dashboard.modules.serve.serve_agent.ServeAgent'>
2023-01-24 14:19:20,438 INFO agent.py:165 -- Loaded 8 modules.
2023-01-24 14:19:20,441 INFO http_server_agent.py:74 -- Dashboard agent http address: 0.0.0.0:52365
2023-01-24 14:19:20,441 INFO http_server_agent.py:81 -- <ResourceRoute [GET] <PlainResource  /api/local_raylet_healthz> -> <function HealthzAgent.health_check at 0x7f0227a293a0>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [OPTIONS] <PlainResource  /api/local_raylet_healthz> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7f034069e070>>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [POST] <PlainResource  /api/job_agent/jobs/> -> <function JobAgent.submit_job at 0x7f02279c8b80>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [OPTIONS] <PlainResource  /api/job_agent/jobs/> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7f034069e070>>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [POST] <DynamicResource  /api/job_agent/jobs/{job_or_submission_id}/stop> -> <function JobAgent.stop_job at 0x7f02279dfe50>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [OPTIONS] <DynamicResource  /api/job_agent/jobs/{job_or_submission_id}/stop> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7f034069e070>>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [DELETE] <DynamicResource  /api/job_agent/jobs/{job_or_submission_id}> -> <function JobAgent.delete_job at 0x7f02279e2040>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [OPTIONS] <DynamicResource  /api/job_agent/jobs/{job_or_submission_id}> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7f034069e070>>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [GET] <DynamicResource  /api/job_agent/jobs/{job_or_submission_id}/logs> -> <function JobAgent.get_job_logs at 0x7f02279e21f0>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [OPTIONS] <DynamicResource  /api/job_agent/jobs/{job_or_submission_id}/logs> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7f034069e070>>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [GET] <DynamicResource  /api/job_agent/jobs/{job_or_submission_id}/logs/tail> -> <function JobAgent.tail_job_logs at 0x7f02279e23a0>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [OPTIONS] <DynamicResource  /api/job_agent/jobs/{job_or_submission_id}/logs/tail> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7f034069e070>>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [GET] <PlainResource  /api/ray/version> -> <function ServeAgent.get_version at 0x7f034092f160>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [OPTIONS] <PlainResource  /api/ray/version> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7f034069e070>>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [GET] <PlainResource  /api/serve/deployments/> -> <function ServeAgent.get_all_deployments at 0x7f034092f1f0>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [OPTIONS] <PlainResource  /api/serve/deployments/> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7f034069e070>>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [GET] <PlainResource  /api/serve/deployments/status> -> <function ServeAgent.get_all_deployment_statuses at 0x7f034092f3a0>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [OPTIONS] <PlainResource  /api/serve/deployments/status> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7f034069e070>>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [DELETE] <PlainResource  /api/serve/deployments/> -> <function ServeAgent.delete_serve_application at 0x7f034092f550>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [PUT] <PlainResource  /api/serve/deployments/> -> <function ServeAgent.put_all_deployments at 0x7f034092f700>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [OPTIONS] <PlainResource  /api/serve/deployments/> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7f034069e070>>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [GET] <StaticResource  /logs -> PosixPath('/tmp/ray/session_2023-01-24_14-19-17_229506_31133/logs')> -> <bound method StaticResource._handle of <StaticResource  /logs -> PosixPath('/tmp/ray/session_2023-01-24_14-19-17_229506_31133/logs')>>
2023-01-24 14:19:20,442 INFO http_server_agent.py:81 -- <ResourceRoute [OPTIONS] <StaticResource  /logs -> PosixPath('/tmp/ray/session_2023-01-24_14-19-17_229506_31133/logs')> -> <bound method _PreflightHandler._preflight_handler of <aiohttp_cors.cors_config._CorsConfigImpl object at 0x7f034069e070>>
2023-01-24 14:19:20,442 INFO http_server_agent.py:82 -- Registered 23 routes.
2023-01-24 14:19:20,446 INFO event_agent.py:56 -- Report events to 131.179.80.122:33993
2023-01-24 14:19:20,447 INFO event_utils.py:131 -- Monitor events logs modified after 1674596960.357188 on /tmp/ray/session_2023-01-24_14-19-17_229506_31133/logs/events, the source types are all.
2023-01-24 14:19:38,424 INFO runtime_env_agent.py:324 -- Creating runtime env: {"env_vars": {"PL_DISABLE_FORK": "1"}} with timeout 600 seconds.
2023-01-24 14:19:38,425 INFO runtime_env_agent.py:375 -- Successfully created runtime env: {"env_vars": {"PL_DISABLE_FORK": "1"}}, the context: {"command_prefix": [], "env_vars": {"PL_DISABLE_FORK": "1"}, "py_executable": "/home/davina/mambaforge/envs/ap/bin/python", "resources_dir": null, "container": {}, "java_jars": []}
2023-01-24 14:19:42,124 INFO runtime_env_agent.py:411 -- Runtime env already created successfully. Env: {"env_vars": {"PL_DISABLE_FORK": "1"}}, context: {"command_prefix": [], "env_vars": {"PL_DISABLE_FORK": "1"}, "py_executable": "/home/davina/mambaforge/envs/ap/bin/python", "resources_dir": null, "container": {}, "java_jars": []}
2023-01-24 14:19:42,125 INFO runtime_env_agent.py:411 -- Runtime env already created successfully. Env: {"env_vars": {"PL_DISABLE_FORK": "1"}}, context: {"command_prefix": [], "env_vars": {"PL_DISABLE_FORK": "1"}, "py_executable": "/home/davina/mambaforge/envs/ap/bin/python", "resources_dir": null, "container": {}, "java_jars": []}
2023-01-24 14:19:44,055 INFO runtime_env_agent.py:411 -- Runtime env already created successfully. Env: {"env_vars": {"PL_DISABLE_FORK": "1"}}, context: {"command_prefix": [], "env_vars": {"PL_DISABLE_FORK": "1"}, "py_executable": "/home/davina/mambaforge/envs/ap/bin/python", "resources_dir": null, "container": {}, "java_jars": []}
2023-01-24 14:21:40,586 INFO metrics_agent.py:244 -- Metrics from a worker (5aa6704ca580326d1ba89580527efc4b5693fa2442d3b1485bd662f7) is cleaned up due to timeout. Time since last report 121.30313374008983s
2023-01-24 14:21:43,429 INFO metrics_agent.py:244 -- Metrics from a worker (937be1203dbabe82d0f11780c3575aa7f7d13bc03a77995cc4cc0bab) is cleaned up due to timeout. Time since last report 120.54486069642007s
2023-01-24 14:21:43,429 INFO metrics_agent.py:244 -- Metrics from a worker (ebd5c453e0e6eb84fa1b5e78d7b515b7baf9df4a66365c8f5a5323f4) is cleaned up due to timeout. Time since last report 120.34467712324113s
2023-01-24 14:21:46,257 INFO metrics_agent.py:244 -- Metrics from a worker (5103f102f37f0ea584923223be9211dfef7227f6a49c02608703249a) is cleaned up due to timeout. Time since last report 121.37102895695716s
```
</details>

<details>
<summary>`$ cat  /tmp/ray/session_latest/logs/dashboard.log`</summary>

```shell
2023-01-24 14:19:18,792 INFO head.py:128 -- Dashboard head grpc address: 0.0.0.0:33993
2023-01-24 14:19:18,794 INFO head.py:232 -- Starting dashboard metrics server on port 44227
2023-01-24 14:19:18,796 INFO utils.py:112 -- Get all modules by type: DashboardHeadModule
2023-01-24 14:19:18,975 INFO utils.py:145 -- Available modules: [<class 'ray.dashboard.modules.actor.actor_head.ActorHead'>, <class 'ray.dashboard.modules.event.event_head.EventHead'>, <class 'ray.dashboard.modules.healthz.healthz_head.HealthzHead'>, <class 'ray.dashboard.modules.job.job_head.JobHead'>, <class 'ray.dashboard.modules.log.log_head.LogHead'>, <class 'ray.dashboard.modules.metrics.metrics_head.MetricsHead'>, <class 'ray.dashboard.modules.node.node_head.NodeHead'>, <class 'ray.dashboard.modules.reporter.reporter_head.ReportHead'>, <class 'ray.dashboard.modules.snapshot.snapshot_head.APIHead'>, <class 'ray.dashboard.modules.state.state_head.StateHead'>, <class 'ray.dashboard.modules.usage_stats.usage_stats_head.UsageStatsHead'>]
2023-01-24 14:19:18,975 INFO head.py:201 -- Modules to load: {'JobHead', 'EventHead', 'StateHead', 'LogHead', 'ActorHead', 'UsageStatsHead', 'APIHead', 'MetricsHead', 'HealthzHead', 'NodeHead', 'ReportHead'}
2023-01-24 14:19:18,975 INFO head.py:204 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.actor.actor_head.ActorHead'>
2023-01-24 14:19:18,975 INFO head.py:204 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.event.event_head.EventHead'>
2023-01-24 14:19:18,975 INFO head.py:204 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.healthz.healthz_head.HealthzHead'>
2023-01-24 14:19:18,975 INFO head.py:204 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.job.job_head.JobHead'>
2023-01-24 14:19:18,975 INFO head.py:204 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.log.log_head.LogHead'>
2023-01-24 14:19:18,976 INFO head.py:204 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.metrics.metrics_head.MetricsHead'>
2023-01-24 14:19:18,976 INFO head.py:204 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.node.node_head.NodeHead'>
2023-01-24 14:19:18,977 INFO head.py:204 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.reporter.reporter_head.ReportHead'>
2023-01-24 14:19:18,977 INFO head.py:204 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.snapshot.snapshot_head.APIHead'>
2023-01-24 14:19:18,977 INFO head.py:204 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.state.state_head.StateHead'>
2023-01-24 14:19:18,977 INFO head.py:204 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.usage_stats.usage_stats_head.UsageStatsHead'>
2023-01-24 14:19:18,977 INFO head.py:217 -- Loaded 11 modules. [<ray.dashboard.modules.actor.actor_head.ActorHead object at 0x7f0f48e08a00>, <ray.dashboard.modules.event.event_head.EventHead object at 0x7f0f48e08970>, <ray.dashboard.modules.healthz.healthz_head.HealthzHead object at 0x7f0f48e08c40>, <ray.dashboard.modules.job.job_head.JobHead object at 0x7f1052e7e970>, <ray.dashboard.modules.log.log_head.LogHead object at 0x7f1052e7e9d0>, <ray.dashboard.modules.metrics.metrics_head.MetricsHead object at 0x7f1052e7ea60>, <ray.dashboard.modules.node.node_head.NodeHead object at 0x7f1052e7ef40>, <ray.dashboard.modules.reporter.reporter_head.ReportHead object at 0x7f1052e7ef10>, <ray.dashboard.modules.snapshot.snapshot_head.APIHead object at 0x7f1052ba41f0>, <ray.dashboard.modules.state.state_head.StateHead object at 0x7f1052ba4220>, <ray.dashboard.modules.usage_stats.usage_stats_head.UsageStatsHead object at 0x7f1052ba4370>]
2023-01-24 14:19:18,977 INFO http_server_head.py:85 -- Setup static dir for dashboard: /home/davina/mambaforge/envs/ap/lib/python3.9/site-packages/ray/dashboard/client/build
2023-01-24 14:19:18,980 INFO http_server_head.py:204 -- Dashboard head http address: 127.0.0.1:8265
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /logical/actors> -> <function ActorHead.get_all_actors[cache ttl=2, max_size=128] at 0x7f0f4519daf0>
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /events> -> <function EventHead.get_event[cache ttl=2, max_size=128] at 0x7f0f4451b310>
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/gcs_healthz> -> <function HealthzHead.health_check at 0x7f0f4451bd30>
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/version> -> <function JobHead.get_version at 0x7f0f444e0700>
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [GET] <DynamicResource  /api/packages/{protocol}/{package_name}> -> <function JobHead.get_package at 0x7f0f444e0820>
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [PUT] <DynamicResource  /api/packages/{protocol}/{package_name}> -> <function JobHead.upload_package at 0x7f0f444e0940>
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [POST] <PlainResource  /api/jobs/> -> <function JobHead.submit_job at 0x7f0f444e0a60>
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [POST] <DynamicResource  /api/jobs/{job_or_submission_id}/stop> -> <function JobHead.stop_job at 0x7f0f444e0b80>
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [DELETE] <DynamicResource  /api/jobs/{job_or_submission_id}> -> <function JobHead.delete_job at 0x7f0f444e0ca0>
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [GET] <DynamicResource  /api/jobs/{job_or_submission_id}> -> <function JobHead.get_job_info at 0x7f0f444e0dc0>
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/jobs/> -> <function JobHead.list_jobs at 0x7f0f444e0ee0>
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [GET] <DynamicResource  /api/jobs/{job_or_submission_id}/logs> -> <function JobHead.get_job_logs at 0x7f0f444df040>
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [GET] <DynamicResource  /api/jobs/{job_or_submission_id}/logs/tail> -> <function JobHead.tail_job_logs at 0x7f0f444df160>
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /log_index> -> <function LogHead.get_log_index at 0x7f0f444ef5e0>
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /log_proxy> -> <function LogHead.get_log_from_proxy at 0x7f0f444ef700>
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/grafana_health> -> <function MetricsHead.grafana_health at 0x7f0f4445f3a0>
2023-01-24 14:19:18,980 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/prometheus_health> -> <function MetricsHead.prometheus_health at 0x7f0f4445f4c0>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/progress> -> <function MetricsHead.get_progress at 0x7f0f4445f5e0>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/progress_by_task_name> -> <function MetricsHead.get_progress_by_task_name at 0x7f0f4445f700>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /internal/node_module> -> <function NodeHead.get_node_module_internal_state at 0x7f0f4446d3a0>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /nodes> -> <function NodeHead.get_all_nodes[cache ttl=2, max_size=128] at 0x7f0f4446d4c0>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <DynamicResource  /nodes/{node_id}> -> <function NodeHead.get_node[cache ttl=2, max_size=128] at 0x7f0f4446d670>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/cluster_status> -> <function ReportHead.get_cluster_status at 0x7f0f44200790>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /worker/traceback> -> <function ReportHead.get_traceback at 0x7f0f442008b0>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /worker/cpu_profile> -> <function ReportHead.cpu_profile at 0x7f0f442009d0>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/actors/kill> -> <function APIHead.kill_actor_gcs at 0x7f1052e51670>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/snapshot> -> <function APIHead.snapshot at 0x7f1052e51790>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/component_activities> -> <function APIHead.get_component_activities at 0x7f1052e518b0>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/v0/actors> -> <function RateLimitedModule.enforce_max_concurrent_calls.<locals>.async_wrapper at 0x7f1052e6a700>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/v0/jobs> -> <function RateLimitedModule.enforce_max_concurrent_calls.<locals>.async_wrapper at 0x7f1052e6a8b0>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/v0/nodes> -> <function RateLimitedModule.enforce_max_concurrent_calls.<locals>.async_wrapper at 0x7f1052e6aa60>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/v0/placement_groups> -> <function RateLimitedModule.enforce_max_concurrent_calls.<locals>.async_wrapper at 0x7f1052e6ac10>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/v0/workers> -> <function RateLimitedModule.enforce_max_concurrent_calls.<locals>.async_wrapper at 0x7f1052e6adc0>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/v0/tasks> -> <function RateLimitedModule.enforce_max_concurrent_calls.<locals>.async_wrapper at 0x7f1052e6af70>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/v0/objects> -> <function RateLimitedModule.enforce_max_concurrent_calls.<locals>.async_wrapper at 0x7f1052e6e160>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/v0/runtime_envs> -> <function RateLimitedModule.enforce_max_concurrent_calls.<locals>.async_wrapper at 0x7f1052e6e310>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/v0/cluster_events> -> <function RateLimitedModule.enforce_max_concurrent_calls.<locals>.async_wrapper at 0x7f1052e6e4c0>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/v0/logs> -> <function RateLimitedModule.enforce_max_concurrent_calls.<locals>.async_wrapper at 0x7f1052e6e670>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <DynamicResource  /api/v0/logs/{media_type}> -> <function RateLimitedModule.enforce_max_concurrent_calls.<locals>.async_wrapper at 0x7f1052e6e820>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/v0/tasks/summarize> -> <function RateLimitedModule.enforce_max_concurrent_calls.<locals>.async_wrapper at 0x7f1052e6ea60>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/v0/actors/summarize> -> <function RateLimitedModule.enforce_max_concurrent_calls.<locals>.async_wrapper at 0x7f1052e6ec10>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /api/v0/objects/summarize> -> <function RateLimitedModule.enforce_max_concurrent_calls.<locals>.async_wrapper at 0x7f1052e6edc0>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <DynamicResource  /api/v0/delay/{delay_s}> -> <function StateHead.delayed_response at 0x7f1052e6eee0>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /usage_stats_enabled> -> <function UsageStatsHead.get_usage_stats_enabled at 0x7f1052e7c9d0>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <StaticResource  /logs -> PosixPath('/tmp/ray/session_2023-01-24_14-19-17_229506_31133/logs')> -> <bound method StaticResource._handle of <StaticResource  /logs -> PosixPath('/tmp/ray/session_2023-01-24_14-19-17_229506_31133/logs')>>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /> -> <function HttpServerDashboardHead.get_index at 0x7f1052baa160>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <PlainResource  /favicon.ico> -> <function HttpServerDashboardHead.get_favicon at 0x7f1052baa280>
2023-01-24 14:19:18,981 INFO http_server_head.py:210 -- <ResourceRoute [GET] <StaticResource  /static -> PosixPath('/home/davina/mambaforge/envs/ap/lib/python3.9/site-packages/ray/dashboard/client/build/static')> -> <bound method StaticResource._handle of <StaticResource  /static -> PosixPath('/home/davina/mambaforge/envs/ap/lib/python3.9/site-packages/ray/dashboard/client/build/static')>>
2023-01-24 14:19:18,982 INFO http_server_head.py:211 -- Registered 48 routes.
2023-01-24 14:19:18,983 INFO event_utils.py:131 -- Monitor events logs modified after 1674596958.9255528 on /tmp/ray/session_2023-01-24_14-19-17_229506_31133/logs/events, the source types are all.
2023-01-24 14:19:18,988 INFO usage_stats_head.py:168 -- Usage reporting is disabled.
2023-01-24 14:19:18,988 INFO actor_head.py:102 -- Getting all actor info from GCS.
2023-01-24 14:19:18,995 INFO actor_head.py:124 -- Received 0 actor info from GCS.
2023-01-24 14:20:04,175 INFO web_log.py:206 -- 127.0.0.1 [24/Jan/2023:22:20:04 +0000] 'GET /nodes?view=summary HTTP/1.1' 200 26457 bytes 4779 us 'http://localhost:8265/' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
2023-01-24 14:20:04,177 INFO web_log.py:206 -- 127.0.0.1 [24/Jan/2023:22:20:04 +0000] 'GET /api/grafana_health HTTP/1.1' 500 348 bytes 6909 us 'http://localhost:8265/' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
2023-01-24 14:20:04,287 INFO web_log.py:206 -- 127.0.0.1 [24/Jan/2023:22:20:04 +0000] 'GET /usage_stats_enabled HTTP/1.1' 200 283 bytes 1079 us 'http://localhost:8265/' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
2023-01-24 14:20:04,288 INFO web_log.py:206 -- 127.0.0.1 [24/Jan/2023:22:20:04 +0000] 'GET /nodes?view=summary HTTP/1.1' 200 26457 bytes 571 us 'http://localhost:8265/' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
2023-01-24 14:20:04,379 INFO web_log.py:206 -- 127.0.0.1 [24/Jan/2023:22:20:04 +0000] 'GET /nodes/ab780f500a245a74f71d5b6dac329c1f20f42c65686b9a632305b6d3 HTTP/1.1' 200 123398 bytes 7876 us 'http://localhost:8265/' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
2023-01-24 14:20:13,887 INFO web_log.py:206 -- 127.0.0.1 [24/Jan/2023:22:20:13 +0000] 'GET /static/js/main.c6b6ee47.js.map HTTP/1.1' 200 256 bytes 25715 us '-' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
2023-01-24 14:20:13,893 INFO web_log.py:206 -- 127.0.0.1 [24/Jan/2023:22:20:13 +0000] 'GET /static/js/60.19a35766.chunk.js.map HTTP/1.1' 200 252 bytes 10164 us '-' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
2023-01-24 14:20:13,893 INFO web_log.py:206 -- 127.0.0.1 [24/Jan/2023:22:20:13 +0000] 'GET /static/js/291.c0a29095.chunk.js.map HTTP/1.1' 200 253 bytes 10546 us '-' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
2023-01-24 14:20:13,893 INFO web_log.py:206 -- 127.0.0.1 [24/Jan/2023:22:20:13 +0000] 'GET /static/js/494.e4d9e2dc.chunk.js.map HTTP/1.1' 200 252 bytes 10738 us '-' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
2023-01-24 14:20:13,893 INFO web_log.py:206 -- 127.0.0.1 [24/Jan/2023:22:20:13 +0000] 'GET /static/js/643.e6471be1.chunk.js.map HTTP/1.1' 200 252 bytes 10929 us '-' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
2023-01-24 14:20:14,314 INFO web_log.py:206 -- 127.0.0.1 [24/Jan/2023:22:20:14 +0000] 'GET /static/css/main.388a904b.css.map HTTP/1.1' 200 251 bytes 2942 us '-' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
2023-01-24 14:20:14,825 INFO web_log.py:206 -- 127.0.0.1 [24/Jan/2023:22:20:14 +0000] 'GET /static/js/185.72ddb488.chunk.js.map HTTP/1.1' 200 252 bytes 6897 us '-' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
```
</details>

Then there's the matter of the `[DEBUG]` lines printed out from ray.
<details>
<summary>Some relevant output:</summary>

```shell
2023-01-24 14:10:47,586 DEBUG gcs_utils.py:187 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1674598247.586235900","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3217,"referenced_errors":[{"created":"@1674598247.586233791","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":165,"grpc_status":14}]}"
>
2023-01-24 14:10:48,588 DEBUG gcs_utils.py:291 -- internal_kv_put b'CLUSTER_METADATA' b'{"ray_version": "2.2.0", "python_version": "3.9.15"}' True b'cluster'
2023-01-24 14:10:48,768 DEBUG gcs_utils.py:269 -- internal_kv_get b'dashboard' b'dashboard'
023-01-24 14:10:49,377 DEBUG gcs_utils.py:291 -- internal_kv_put b'webui:url' b'127.0.0.1:8265' True b'dashboard'
```
</details>
This is the only error message that may mean anything useful.

### Versions / Dependencies

Ray versions (installed with mamba)
```
ray-core                  2.2.0            py39h4d85f9a_1    conda-forge
ray-dashboard             2.2.0            py39h9a2ef2b_1    conda-forge
ray-default               2.2.0            py39hf3d152e_1    conda-forge
ray-tune                  2.2.0            py39hf3d152e_1    conda-forge
```

Python 3.9.15

OS:  Ubuntu 18.04.4 LTS (Bionic Beaver)

Other relevant information:
cudatoolkit=10.2
pytorch=1.12.1
pytorch-lightning=1.6.5
cudnn=7.6.5

Specs:
4 GeForce RTX 2080 Ti's
32 CPUs (x86_64)

### Reproduction script

```python
import ray

if __name__ == "__main__":
    ray.init(include_dashboard=True)
    input("Enter to exit.")
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by rkooo567** [comment]
cc @alanwguo seems to be a bug from the frontend?

**Comment by alanwguo** [comment]
@davzaman , thanks for the detailed bug report! 

This is already fixed and will be available in ray 2.3: https://github.com/ray-project/ray/pull/30874

**Comment by davzaman** [comment]
Gotcha, didn't see that! Thank you.

**Comment by narendranathchalla** [comment]
this is still happening in 2.5.1 in aws cluster launcher
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

```
Failed to load resource: the server responded with a status of 500 (Cannot connect to host localhost:9090 ssl:default [Connect call failed ('127.0.0.1', 9090)])
```

cluster.yaml 
```
cluster_name: ray-test

max_workers: 2

upscaling_speed: 1.0

docker:
    image: " acct.dkr.ecr.us-west-2.amazonaws.com/ray:ray2.5.1-py38-cu118-pytorch2.0.1" # You can change this to latest-cpu if you don't need GPU support and want a faster startup
    container_name: "ray_nvidia_docker"
    pull_before_run: True
    run_options:
        - --ulimit nofile=65536:65536

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 5

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a,us-west-2b
    cache_stopped_nodes: False
    use_internal_ips: true
    cloudwatch:
        agent:
            config: "example-cloudwatch-agent-config.json"
        dashboard:
            name: "ray-dashboard"
            config: "example-cloudwatch-dashboard-config.json"

auth:
    ssh_user: ubuntu

available_node_types:
    ray.head.cpu:
        resources: {}
        node_config:
            InstanceType: m6i.4xlarge
            ImageId: ami-0d88d9cbe28fac870
            SubnetIds: ["subnet-0bc2fab"]
            SecurityGroupIds: ["sg-0638952"]
            KeyName: "cloud"
            IamInstanceProfile:
                Name: dataset-access
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 2000
                      VolumeType: gp3
    ray.worker.gpu:
        min_workers: 0
        max_workers: 2
        resources: {}
        node_config:
            InstanceType: g5.48xlarge
            ImageId: ami-0d88d9cbe28fac870
            SubnetIds: ["subnet-0ab"]
            SecurityGroupIds: ["sg-0952"]
            KeyName: "cloud"
            IamInstanceProfile:
                Name: dataset-access
            InstanceMarketOptions:
                MarketType: on-demand
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 2000
                      VolumeType: gp3

head_node_type: ray.head.cpu

file_mounts: {}

cluster_synced_files: []

file_mounts_sync_continuously: False

rsync_exclude:
    - "**/.git"
    - "**/.git/**"
    - "**/.gitignore"
rsync_filter:
    - ".gitignore"

initialization_commands: 
- curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
- unzip awscliv2.zip
- sudo ./aws/install
- aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin acct.dkr.ecr.us-west-2.amazonaws.com

# List of shell commands to run to set up nodes.
setup_commands: []

# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []
#- aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin acct.dkr.ecr.us-west-2.amazonaws.com

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host=0.0.0.0 --num-cpus=0

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076
```

**Comment by Johnnykoch02** [comment]
For me, I'm running Ubuntu 22.04 with Python 3.13 and had this issue with my kubernetes deployment. I fix it with kind of a hack, but a hack that seems to work pretty well :D 

Just add this to a startup script or run this in a shell before starting the ray dashboard. I trigger it on lifecycle postStart. 

`sed -i 's/pathlib.posixpath.realpath/os.path.realpath/g' /usr/local/lib/python3.13/site-packages/ray/dashboard/http_server_head.py && \
                    sed -i '1i import os' /usr/local/lib/python3.13/site-packages/ray/dashboard/http_server_head.py`

Ray team please fix this issue, its silly that this was shipped into production code, making it very annoying to deal with.
