### ISSUE TITLE
[data] [streaming] The transformation changes the size of the block, and spilled to disk

### ISSUE THREAD

**Issue by v4if** [ray-project/ray#34041]
### What happened + What you expected to happen

With datasets streaming execution, the transformation changes the size of the block, object_store_memory will grow beyond the set value, and spilled to disk.
```text
2023-04-04 15:36:14,418	INFO streaming_executor.py:83 -- Executing DAG InputDataBuffer[Input] -> TaskPoolMapOperator[ReadRange] -> ActorPoolMapOperator[MapBatches(TestFast)] -> ActorPoolMapOperator[MapBatches(TestSlow)]
Resource usage vs limits 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]2023-04-04 15:36:14,432	INFO actor_pool_map_operator.py:100 -- MapBatches(TestFast): Waiting for 10 pool actors to start...
2023-04-04 15:36:15,969	INFO actor_pool_map_operator.py:100 -- MapBatches(TestSlow): Waiting for 2 pool actors to start...
(raylet, ip=172.16.0.67) Spilled 16584 MiB, 257 objects, write throughput 309 MiB/s.
Resource usage vs limits: 2.0/16.0 CPU, 0.0/1.0 GPU, 14.39 GiB/4.44 GiB object_store_memory 0:   0%|                                    | 0/1 [01:06<?, ?it/s^@eadRange: 0 active, 867 queued, 0.0 MiB objects 1:  13%|████████▊                                                         | 133/1000 [00:17<00:09, 92.21it/s]
MapBatches(TestFast): 12 active, 22 queued, 288.0 MiB objects, 10 actors [all objects local] 2:  10%|██▎                    | 99/1000 [01:03<15:38,  1.04s/it]
MapBatches(TestSlow): 8 active, 79 queued, 1.56 GiB objects, 2 actors [all objects local] 3:   1%|▎                       | 12/1000 [01:03<1:20:38,  4.90s/it]
output: 0 queued 4:   1%|█▏                                                                                               | 12/1000 [01:03<1:20:54,  4.91s/it]

```

### Versions / Dependencies

ray, version 3.0.0.dev0
nightly build

### Reproduction script

```python
import ray
import time
import numpy as np

assert (
    ray.__version__ >= "2.3.0"
), f"The version of ray must be greater than 2.3.0, the current version is {ray.__version__}"

ray.init()

ctx = ray.data.context.DatasetContext.get_current()
ctx.use_streaming_executor = True
ctx.execution_options.preserve_order = False


class TestSlow:
    def __call__(self, df: np.ndarray):
        time.sleep(2)
        return np.random.randn(1,20,1024,1024)


class TestFast:
    def __call__(self, df: np.ndarray):
        time.sleep(0.1)
        return np.random.randn(1,20,1024,1024)


ds = ray.data.range_tensor(1000, shape=(3, 1024, 1024), parallelism=1000)

pipe = ds.map_batches(
    TestFast,
    batch_size=1,
    num_cpus=0.1,
    compute=ray.data.ActorPoolStrategy(10, 10),
).map_batches(
    TestSlow,
    batch_size=1,
    num_cpus=0.5,
    compute=ray.data.ActorPoolStrategy(2, 2),
)

for batch in pipe.iter_batches(batch_size=1):
    ...
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by ericl** [comment]
@v4if thanks for reporting. Indeed this is a bug triggered by the output batch size being much larger than the input. This patch should resolve the problem, can you try it out? https://github.com/ray-project/ray/pull/34254

**Comment by v4if** [comment]
How to use this patch, is there no merge to master nightly build version, I still have this problem when using nightly build

**Comment by clarng** [comment]
> How to use this patch, is there no merge to master nightly build version, I still have this problem when using nightly build

You can try one of the wheels produced here that contains the fix:  https://buildkite.com/ray-project/oss-ci-build-pr/builds/18252#01877349-179e-4f2f-a91a-ddc2e4be36c5

They are under the artifacts tab
