### ISSUE TITLE
[Tune] Configuring Tune with Oracle Cloud S3-like object storage fails to upload empty marker files

### ISSUE THREAD

**Issue by logannas** [ray-project/ray#34489]
### What happened + What you expected to happen

I'm using a non-AWS s3 storage to save the training outputs, so in the SyncConfig configuration it's necessary to pass the endpoint_override in the upload_dir:

```
        run_config=air.RunConfig(
            local_dir='checkpoint',
            sync_config=tune.SyncConfig(
                upload_dir='s3://bucket-test/ray/tune/checkpoints/test?scheme=http&endpoint_override=localhost:9000',
                syncer='auto'
            ),
            stop={"training_iteration": 10}
        ),
```
The problem is that when saving the checkpoints, the endpoint_override settings are not maintained, returning the error:

```
(Classification pid=30834) Exception in thread Thread-3 (_try_fn):
(Classification pid=30834) Traceback (most recent call last):
(Classification pid=30834)   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
(Classification pid=30834)     self.run()
(Classification pid=30834)   File "/usr/local/lib/python3.10/threading.py", line 953, in run
(Classification pid=30834)     self._target(*self._args, **self._kwargs)
(Classification pid=30834)   File "/home/vscode/.local/lib/python3.10/site-packages/ray/tune/utils/util.py", line 138, in _try_fn
(Classification pid=30834)     fn()
(Classification pid=30834)   File "/home/vscode/.local/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 589, in <lambda>
(Classification pid=30834)     lambda: checkpoint.to_uri(checkpoint_uri),
(Classification pid=30834)   File "/home/vscode/.local/lib/python3.10/site-packages/ray/air/checkpoint.py", line 714, in to_uri
(Classification pid=30834)     upload_to_uri(local_path=local_path, uri=uri)
(Classification pid=30834)   File "/home/vscode/.local/lib/python3.10/site-packages/ray/air/_internal/remote_storage.py", line 220, in upload_to_uri
(Classification pid=30834)     pyarrow.fs.copy_files(local_path, bucket_path, destination_filesystem=fs)
(Classification pid=30834)   File "/home/vscode/.local/lib/python3.10/site-packages/pyarrow/fs.py", line 267, in copy_files
(Classification pid=30834)     _copy_files_selector(source_fs, source_sel,
(Classification pid=30834)   File "pyarrow/_fs.pyx", line 1619, in pyarrow._fs._copy_files_selector
(Classification pid=30834)   File "pyarrow/error.pxi", line 115, in pyarrow.lib.check_status
(Classification pid=30834) OSError: When initiating multiple part upload for key 'ray/tune/checkpoints/test/.is_checkpoint' in bucket 'bucket-test': AWS Error NO_SUCH_BUCKET during CreateMultipartUpload operation: The specified bucket does not exist
```
The problem of uploading can be solved with the sync_up function of the custom Syncer, but even with the sync_down function it's not possible to resume an experiment, the same endpoint_override problem happens, where an attempt is made to connect the storage to the amazonaws URL .

I think this question may be related to: https://github.com/ray-project/ray/issues/29845 and https://github.com/ray-project/ray/pull/30125.

### Versions / Dependencies

ray==2.3.1
pyarrow==11.0.0

### Reproduction script

I used as a test an image from minio quay.io/minio/minio (https://min.io/docs/minio/container/index.html)

```
 tuner = tune.Tuner(
        tune.with_resources(
            tune.with_parameters(Classification),
            resources={"cpu": 2, "gpu": gpus_per_trial}
        ),
        run_config=air.RunConfig(
            local_dir='checkpoint',
            sync_config=tune.SyncConfig(
                upload_dir=f's3://bucket-test/ray/tune/checkpoints/test?scheme=http&endpoint_override=localhost:9000',
                syncer=CustomSyncer()
            ),
            stop={"training_iteration": 10}
        ),
        tune_config=tune.TuneConfig(
            metric="loss",
            mode="min",
            scheduler=scheduler,
            num_samples=num_samples,
        ),
        param_space=config,
    )
    results = tuner.fit()
```
Resume an experiment:
```
from ray import tune
tuner = tune.Tuner.restore(
    "s3://bucket-test/ray/tune/checkpoints/test?scheme=http&endpoint_override=localhost:9000",
    resume_errored=True
)
tuner.fit()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by justinvyu** [comment]
Hi @logannas,

This was fixed by this PR https://github.com/ray-project/ray/pull/32576 (which didn't make it on the 2.3.1 release)!

Please try running with `ray-nightly`. See [here for instructions](https://docs.ray.io/en/latest/ray-overview/installation.html#daily-releases-nightlies). I'll close the issue for now, but feel free to re-open if it doesn't work for you!

**Comment by logannas** [comment]
It still doesn't seem to work well, there is always an error when uploading checkpoint files, so the model.pth is not sent to storage, but the other files are all sent normally.

```
(ObjectDetection pid=13508) 2023-04-18 13:48:58,003     ERROR syncer.py:437 -- Caught sync error: Sync process failed: When initiating multiple part upload for key 'ray/tune/checkpoints/ObjectDetection_2023-04-18_13-48-07/ObjectDetection_a89dd_00000_0_2023-04-18_13-48-11/checkpoint_000001/.is_checkpoint' in bucket 'bucket-test': AWS Error INVALID_ACCESS_KEY_ID during CreateMultipartUpload operation: The Access Key Id you provided does not exist in our records.. Retrying after sleeping for 1.0 seconds...
(ObjectDetection pid=13508) 2023-04-18 13:48:59,015     ERROR syncer.py:437 -- Caught sync error: Sync process failed: When initiating multiple part upload for key 'ray/tune/checkpoints/ObjectDetection_2023-04-18_13-48-07/ObjectDetection_a89dd_00000_0_2023-04-18_13-48-11/checkpoint_000001/.is_checkpoint' in bucket 'bucket-test': AWS Error INVALID_ACCESS_KEY_ID during CreateMultipartUpload operation: The Access Key Id you provided does not exist in our records.. Retrying after sleeping for 1.0 seconds...
(ObjectDetection pid=13508) 2023-04-18 13:49:00,021     ERROR syncer.py:437 -- Caught sync error: Sync process failed: When initiating multiple part upload for key 'ray/tune/checkpoints/ObjectDetection_2023-04-18_13-48-07/ObjectDetection_a89dd_00000_0_2023-04-18_13-48-11/checkpoint_000001/.is_checkpoint' in bucket 'bucket-test': AWS Error INVALID_ACCESS_KEY_ID during CreateMultipartUpload operation: The Access Key Id you provided does not exist in our records.. Retrying after sleeping for 1.0 seconds...
(ObjectDetection pid=13508) 2023-04-18 13:49:01,027     ERROR trainable.py:669 -- Could not upload checkpoint to s3://bucket-test/ray/tune/checkpoints/ObjectDetection_2023-04-18_13-48-07/ObjectDetection_a89dd_00000_0_2023-04-18_13-48-11/checkpoint_000001?endpoint_override=http://host.docker.internal:9000 even after 3 retries.Please check if the credentials expired and that the remote filesystem is supported. For large checkpoints or artifacts, consider increasing `SyncConfig(sync_timeout)` (current value: 15000 seconds).
```

**Comment by justinvyu** [comment]
@logannas This looks like an AWS credentials error - did you authenticate with your AWS account on **all** nodes in the Ray cluster? Individual trials (running on worker nodes) will attempt to upload their checkpoints to cloud directly.

You can configure the "command line access" environment variables in a Ray runtime environment as a quick fix to the issue. This will ship the environment variables to all actors/tasks running in the cluster.

```python
runtime_env = {"env_vars": {"AWS_ACCESS_KEY_ID": "<fill>", "AWS_SECRET_ACCESS_KEY": "<fill>", "AWS_SESSION_TOKEN": "<fill>"}}
ray.init(runtime_env=runtime_env)
```

Re-opening for now. Let me know how this goes!

**Comment by logannas** [comment]
Now this error is happening, in the same file (.is_checkpoint). The checkpoint folder is the only one that is not synchronizing, I can see all the other files in the bucket correctly.

```
(ObjectDetection pid=18643) /arrow/cpp/src/arrow/io/interfaces.cc:287: Error ignored when destroying file of type N5arrow2fs12_GLOBAL__N_118ObjectOutputStreamE: IOError: When uploading part for key 'ray/tune/checkpoints/ObjectDetection_2023-04-18_17-55-44/ObjectDetection_40448_00000_0_2023-04-18_17-55-49/checkpoint_000001/.is_checkpoint' in bucket 'bucket-test': AWS Error UNKNOWN (HTTP status 411) during UploadPart operation: Unable to parse ExceptionName: MissingContentLength Message: The Content-Length must be greater than or equal to 1 (it was '0')
(ObjectDetection pid=18643) 2023-04-18 17:56:53,302     ERROR syncer.py:437 -- Caught sync error: Sync process failed: When uploading part for key 'ray/tune/checkpoints/ObjectDetection_2023-04-18_17-55-44/ObjectDetection_40448_00000_0_2023-04-18_17-55-49/checkpoint_000001/.is_checkpoint' in bucket 'bucket-test': AWS Error UNKNOWN (HTTP status 411) during UploadPart operation: Unable to parse ExceptionName: MissingContentLength Message: The Content-Length must be greater than or equal to 1 (it was '0'). Retrying after sleeping for 1.0 seconds...
(ObjectDetection pid=18643) /arrow/cpp/src/arrow/io/interfaces.cc:287: Error ignored when destroying file of type N5arrow2fs12_GLOBAL__N_118ObjectOutputStreamE: IOError: When uploading part for key 'ray/tune/checkpoints/ObjectDetection_2023-04-18_17-55-44/ObjectDetection_40448_00000_0_2023-04-18_17-55-49/checkpoint_000001/.is_checkpoint' in bucket 'bucket-test': AWS Error UNKNOWN (HTTP status 411) during UploadPart operation: Unable to parse ExceptionName: MissingContentLength Message: The Content-Length must be greater than or equal to 1 (it was '0')
(ObjectDetection pid=18643) 2023-04-18 17:56:55,204     ERROR syncer.py:437 -- Caught sync error: Sync process failed: When uploading part for key 'ray/tune/checkpoints/ObjectDetection_2023-04-18_17-55-44/ObjectDetection_40448_00000_0_2023-04-18_17-55-49/checkpoint_000001/.is_checkpoint' in bucket 'bucket-test': AWS Error UNKNOWN (HTTP status 411) during UploadPart operation: Unable to parse ExceptionName: MissingContentLength Message: The Content-Length must be greater than or equal to 1 (it was '0'). Retrying after sleeping for 1.0 seconds...
```

**Comment by justinvyu** [comment]
Ah, got it. Which "non-AWS s3 storage" are you using? Something like minio? Do you have a reproduction script that I can run?

**Comment by logannas** [comment]
I'm currently using Oracle Cloud, but I also did tests using the minio docker image (https://min.io/docs/minio/container/index.html).

```
        tuner = tune.Tuner(
            tune.with_resources(ObjectDetection, tune.PlacementGroupFactory([
                {"CPU": config['resources']['cpus_per_trial'], "GPU": config['resources']['gpus_per_trial']},
            ])),
            param_space=config,
            run_config=air.RunConfig(
                storage_path = f's3://{BUCKET}/ray/tune/checkpoints?endpoint_override=https://<url>',
                sync_config=tune.SyncConfig(
                    sync_timeout=15000
                ),
                stop={"training_iteration": 5 if args.smoke_test else config['training_iteration']},
                checkpoint_config=air.CheckpointConfig(checkpoint_frequency=1, checkpoint_at_end=True),
                failure_config=air.FailureConfig(max_failures=5)
            ),
            tune_config=tune.TuneConfig(
                metric=config['searcher']['metric'],
                mode=config['searcher']['mode'],
                num_samples=int(config['num_samples']),
                scheduler=scheduler,
            ),
        )
```

**Comment by justinvyu** [comment]
Could you also share the skeleton of your `ObjectDetection` trainable? Mostly, how are you creating the checkpoint (your implementation of `save_checkpoint`, or, what you pass to `session.report` depending on the `Trainable` type)?

Thanks for sending over the configs -- I will try to reproduce on my end.

**Comment by justinvyu** [comment]
Hi @logannas,

I tested with minio s3, and it was working for me. When you tested with minio, did it fail with the same error?

Could you try running with my setup? I have the relevant dependency versions + docker setup yml + run instructions at this repo: https://github.com/justinvyu/ray-minio-example

Checking your `pyarrow` version is a good first step, as this doesn't seem like an issue with Ray itself. Let me know how it goes.

**Comment by justinvyu** [comment]
I also noticed you have a `CustomSyncer`. Could you provide that (or just describe what it does compared to the default one that uses pyarrow provided by Tune)?

**Comment by logannas** [comment]
Yes, I created a CustomSyncer using boto3 to upload my files to the storage, just listing all the files from local_dir to my remote storage, but in these tests that I put here, the CustomSyncer is not used.

```
class CustomSyncer(Syncer):
    def sync_up(
        self, local_dir: str, remote_dir: str, exclude: list = None
    ) -> bool:
        s3_client = boto3.client('s3',
                        aws_access_key_id=KEY_ID,
                        aws_secret_access_key=SECRET_KEY,
                        endpoint_url=ENDPOINT_URL
            )

        subdirectories = glob(f'{local_dir}/**/*.*', recursive=True)

        for directory in subdirectories:
            experiment_path = directory.split('ray_results/')[1]
            path = f'ray/tune/checkpoints/{experiment_path}'

            s3_client.upload_file(directory, BUCKET, path)
```

**Comment by logannas** [comment]
I tested the code and it actually works, I have an idea of what might be happening on Oracle Cloud, the ".is_checkpoint" file is empty (0.0B) and that's exactly the error that is returning. Maybe there is some limitation of uploading empty files, is it possible to avoid this?

```
(ObjectDetection pid=18643) /arrow/cpp/src/arrow/io/interfaces.cc:287: Error ignored when destroying file of type N5arrow2fs12_GLOBAL__N_118ObjectOutputStreamE: IOError: When uploading part for key 'ray/tune/checkpoints/ObjectDetection_2023-04-18_17-55-44/ObjectDetection_40448_00000_0_2023-04-18_17-55-49/checkpoint_000001/.is_checkpoint' in bucket 'bucket-test': AWS Error UNKNOWN (HTTP status 411) during UploadPart operation: Unable to parse ExceptionName: MissingContentLength Message: The Content-Length must be greater than or equal to 1 (it was '0')
(ObjectDetection pid=18643) 2023-04-18 17:56:53,302     ERROR syncer.py:437 -- Caught sync error: Sync process failed: When uploading part for key 'ray/tune/checkpoints/ObjectDetection_2023-04-18_17-55-44/ObjectDetection_40448_00000_0_2023-04-18_17-55-49/checkpoint_000001/.is_checkpoint' in bucket 'bucket-test': AWS Error UNKNOWN (HTTP status 411) during UploadPart operation: Unable to parse ExceptionName: MissingContentLength Message: The Content-Length must be greater than or equal to 1 (it was '0'). Retrying after sleeping for 1.0 seconds...
(ObjectDetection pid=18643) /arrow/cpp/src/arrow/io/interfaces.cc:287: Error ignored when destroying file of type N5arrow2fs12_GLOBAL__N_118ObjectOutputStreamE: IOError: When uploading part for key 'ray/tune/checkpoints/ObjectDetection_2023-04-18_17-55-44/ObjectDetection_40448_00000_0_2023-04-18_17-55-49/checkpoint_000001/.is_checkpoint' in bucket 'bucket-test': AWS Error UNKNOWN (HTTP status 411) during UploadPart operation: Unable to parse ExceptionName: MissingContentLength Message: The Content-Length must be greater than or equal to 1 (it was '0')
(ObjectDetection pid=18643) 2023-04-18 17:56:55,204     ERROR syncer.py:437 -- Caught sync error: Sync process failed: When uploading part for key 'ray/tune/checkpoints/ObjectDetection_2023-04-18_17-55-44/ObjectDetection_40448_00000_0_2023-04-18_17-55-49/checkpoint_000001/.is_checkpoint' in bucket 'bucket-test': AWS Error UNKNOWN (HTTP status 411) during UploadPart operation: Unable to parse ExceptionName: MissingContentLength Message: The Content-Length must be greater than or equal to 1 (it was '0'). Retrying after sleeping for 1.0 seconds...
```
![image](https://user-images.githubusercontent.com/38084420/233195697-95640351-3937-448e-8908-ff436dc7a400.png)

**Comment by justinvyu** [comment]
Got it. This does seem to be an Oracle Cloud issue, specifically in the way pyarrow interacts with it. Pyarrow creates this 0-length upload operation, which works for actual AWS/minio/moto, but not for Oracle Cloud it seems. Then, this error we're seeing is the caught error within pyarrow.

I have a couple of ideas in mind to remove the need for this empty marker file on Tune's side, but this may not be implemented/fixed for some time.

### Workaround

Here is a workaround you could try for now (I don't have very immediate access to testing on Oracle Cloud) to get around using pyarrow:

1. Use a custom command line syncer. See here for an example of AWS/GS: https://docs.ray.io/en/latest/tune/faq.html#how-can-i-use-the-awscli-or-gsutil-command-line-commands-for-syncing
2. Replace the commands with the Oracle Cloud CLI equivalents: https://docs.oracle.com/en-us/iaas/tools/oci-cli/3.25.3/oci_cli_docs/cmdref/os.html
3. Make sure the Oracle Cloud CLI is available on all nodes.

Let me know if you have any questions about that suggestion.

**Comment by logannas** [comment]
I made a Syncer using boto3 to sync_up and sync_down of the outputs and it worked. Do you have a date for these storage changes that are in the nightly version to be released?

Thank you for your attention and help!

**Comment by justinvyu** [comment]
Great to hear! It should be packaged with Ray 2.4, which should be released very soon (within 1 week)!

I will leave this thread open for now, since the underlying issue is not fixed yet.

**Comment by justinvyu** [comment]
Checkpoints no longer contain this empty marker file. Closing as the remaining issue -- feel free to create a new issue if Oracle cloud is still not working properly with the new persistence implementation in Ray 2.7+.
