### ISSUE TITLE
[Datasets] Dataset logger overrides other loggers

### ISSUE THREAD

**Issue by GokuMohandas** [ray-project/ray#34848]
Datasets logger produces lots of `INFO` log messages and overrides other loggers and also not sure if many of the INFO logs from Ray are needed to be seen by default.

![Image](https://user-images.githubusercontent.com/8000987/235029959-a369cda9-0643-45c0-a023-8fe6a7f90935.png)

Additional context from @matthewdeng:

"""
Oh nice investigation, it does look like this is actually happening because of Datasets logging! [https://github.com/ray-project/ray/blob/master/python/ray/data/_internal/dataset_logger.py#L48-L51](https://www.google.com/url?q=https://github.com/ray-project/ray/blob/master/python/ray/data/_internal/dataset_logger.py%23L48-L51&sa=D&source=docs&ust=1682647508563527&usg=AOvVaw2e0yL2XwBkSqqghOnVRLu9)

Interestingly, it looks like Ray's default logging level is INFO, but this logic is setting it globally. I will follow up with folks on Data/Observability to understand the intended behavior around the following:

1. Whether the default should be INFO or WARNING
2. Whether the default should apply to the driver or only Actors/Tasks
3. Whether the default should apply to Ray code or all code

"""

**Comment by matthewdeng** [comment]
Ah I believe this should be fixed by https://github.com/ray-project/ray/pull/34347. Can you confirm if https://github.com/ray-project/ray/issues/34298 captures the problem correctly, or if this issue is referring to too many `INFO` logs _produced by Data_?

**Comment by GokuMohandas** [comment]
Hmm I still see some loggers (ex. copying or creating files) which aren't displayed normally. But if I interact with Dataset, then they all appear.

![image](https://user-images.githubusercontent.com/8000987/235066246-30497a69-f89f-4328-a504-2bbe3dde6731.png)

Note the additional log in red (INFO file_util.py:190 -- moving file_1 -> dir_2) for the same operations as the first cell.

Here's the code to try:
```python
! touch file_1
! mkdir dir_2
from distutils import file_util
file_util.move_file(src="file_1", dst="dir_2", verbose=1)
```
```python
import ray
ds = ray.data.from_items(range(100))
ds.take(1)
```
```python
! touch file_1
! mkdir dir_2
from distutils import file_util
file_util.move_file(src="file_1", dst="dir_2", verbose=1)
```

and when training/tuning, we have a lot of these operations (+ others):

![image](https://user-images.githubusercontent.com/8000987/235065741-754df72c-e9f3-4257-b35f-7bc7526bc4b7.png)

**Comment by matthewdeng** [comment]
What version/commit of Ray is this on?

**Comment by GokuMohandas** [comment]
This is Ray 2.4.0 on Python 3.9.1

**Comment by matthewdeng** [comment]
Ah unfortunately this commit doesn't seem to have been included in 2.4, can you try with a nightly wheel?

**Comment by GokuMohandas** [comment]
Excellent I see it fixed on nightly! Do you know if this will be incorporated by the 2.5 release?

**Comment by matthewdeng** [comment]
Yes it will!
