### ISSUE TITLE
[serve] Error when shutting down non-detached serve instance

### ISSUE THREAD

**Issue by zcin** [ray-project/ray#35114]
### What happened + What you expected to happen

When running a script that has a non-detached serve instance, when the python script is exiting it tries to shutdown serve but then gets an error:
```
2023-05-06 10:58:19,018	INFO worker.py:1432 -- Connecting to existing Ray cluster at address: 192.168.0.141:6379...
2023-05-06 10:58:19,022	INFO worker.py:1607 -- Connected to Ray cluster. View the dashboard at http://127.0.0.1:8265
The new client HTTP config differs from the existing one in the following fields: ['location']. The new HTTP config is ignored.
(ServeController pid=69690) INFO 2023-05-06 10:58:20,474 controller 69690 deployment_state.py:1205 - Deploying new version of deployment default_B.
(ServeController pid=69690) INFO 2023-05-06 10:58:20,475 controller 69690 deployment_state.py:1444 - Adding 1 replica to deployment default_B.
(HTTPProxyActor pid=69692) INFO:     Started server process [69692]
(ServeController pid=69690) INFO 2023-05-06 10:58:21,499 controller 69690 deployment_state.py:1171 - Deleting deployment default_B.
(ServeController pid=69690) INFO 2023-05-06 10:58:21,508 controller 69690 deployment_state.py:1470 - Removing 1 replica from deployment 'default_B'.
Exception ignored in: <function ServeControllerClient.__del__ at 0x127805820>
Traceback (most recent call last):
  File "/Users/cindyz/ray/python/ray/serve/_private/client.py", line 91, in __del__
  File "/Users/cindyz/ray/python/ray/serve/_private/client.py", line 108, in shutdown
  File "/Users/cindyz/ray/python/ray/_private/client_mode_hook.py", line 98, in wrapper
ImportError: sys.meta_path is None, Python is likely shutting down
```

### Versions / Dependencies

master(0e0e85b93f1c31c1d4926668c41179d648a576b4)

### Reproduction script

Run with `python demo.py`:
```
from ray import serve

serve.start()
@serve.deployment
class B:
    def __call__(self):
        return "Hello B"

app = B.bind()
if __name__ == "__main__":
    serve.run(app)
```

### Issue Severity

None

**Comment by sihanwang41** [comment]
Hi @zcin, Is this consistently happening? 
I leave this bug to you :)

**Comment by zcin** [comment]
@raulchen I saw that you made a change to the `client_mode_hook` code recently, do you have any insight?

**Comment by raulchen** [comment]
@zcin This bug should be fixed by #35011. Could you try the latest master?

**Comment by zcin** [comment]
@raulchen Hmm, I just pulled and re-compiled, still seeing the error unfortunately.

**Comment by raulchen** [comment]
oh, this is a different place. I don't know the root cause yet. But the quickest workaround is to also add the following to `ServeControllerClient.__del__`. 
```
        if sys.meta_path is None:
             return
```

@ericl do you know why this bug is happening?

**Comment by zcin** [comment]
For context, when a python script runs with an attached serve instance (example is the repro script I included in the issue), when the python file exits it will shutdown Serve, by calling `ServeControllerClient.shutdown()` in `ServeControllerClient.__del__`. However I think `ServeControllerClient.shutdown()` runs into some sort of error when checking `ray.is_initialized()`.

**Comment by raulchen** [comment]
#35304 should fix this issue. But I think this bug should be existing before. Don't know why it didn't surface before.
