### ISSUE TITLE
Release test tune_cloud_durable_upload.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#38493]
Release test **tune_cloud_durable_upload.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2051#0189fd8d-665a-4ac3-80fb-820482e63380 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by justinvyu** [comment]
This is caused by https://github.com/ray-project/ray/pull/38165, the `TrialStub` still expects a `last_result` property on the trial, but that's now in `run_metadata`. @krfricke lmk if you want to take this or if I should fix.

**Comment by justinvyu** [comment]
This was fixed by https://github.com/ray-project/ray/pull/38478

See passing run here: https://buildkite.com/ray-project/release-tests-pr/builds/49493#018a04ec-d583-4c3f-a4fa-9dcf0e403145

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2094#018a4064-cb78-4335-a0a4-0dd7bd1dd314

**Comment by krfricke** [comment]
Taking a look today

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2104#018a4905-d76d-499a-968e-d1b6a2f0a95d

**Comment by can-anyscale** [comment]
I think the fix is there, just need to wait for nightly to catch up

**Comment by GeneDer** [comment]
@krfricke just a reminder to create a cherry-pick PR to get it into the release branch as well :)

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2109#018a4aa4-2145-4456-aeb6-69c99b939d5c
