### ISSUE TITLE
[Service] DNS resolution failed error on gRPC Anyscale Services

### ISSUE THREAD

**Issue by GeneDer** [ray-project/ray#38755]
### Description

Re: https://docs.google.com/document/d/1xIjjTJ80-IV7r6NbAIx-ulysgT3FNozIcZ_BcpXuucQ/edit#bookmark=id.vbcucio011kr
Re: https://docs.google.com/document/d/1xIjjTJ80-IV7r6NbAIx-ulysgT3FNozIcZ_BcpXuucQ/edit#bookmark=id.35xnc72o740x

Wrong url or token will result in `DNS resolution failed` error message. Let's provide better error messages for gRPC requests

**Comment by akshay-anyscale** [comment]
Can this be resolved now @GeneDer

**Comment by GeneDer** [comment]
Just tested those still existing. I think we need some kinda of default response in order to resolve those. Still think it's lower priority as of now.
