### ISSUE TITLE
Release test read_images_train_16_gpu.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#39308]
Release test **read_images_train_16_gpu.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2129#018a69f3-7814-429b-bc35-7cfdcb85e137 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by bveeramani** [comment]
Should be fixed by https://github.com/ray-project/ray/pull/39276, which was merged yesterday. Will monitor to see if the issue persists

**Comment by bveeramani** [comment]
Closing issue so test will run

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2183#018aa74b-1726-4d9a-8ff4-d3a8d4e93be0

**Comment by bveeramani** [comment]
Should be fixed by https://github.com/ray-project/ray/pull/39752

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2188#018ab8e5-a386-4dbc-9921-0126c198c090

**Comment by scottjlee** [comment]
Potential fix with https://github.com/ray-project/ray/pull/39805, closing to run the test (seems that re-opening this issue when it was at jailed state immediately puts it back into jailed state, so it is not included in the nightly release test run).

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2192#018acb75-b2ab-4b2a-a7ed-70ffdb5db698
