### ISSUE TITLE
Release test read_images_train_16_gpu_preserve_order.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#39309]
Release test **read_images_train_16_gpu_preserve_order.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2129#018a69f3-0ddf-46d9-b38c-ecd06eea7fce for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Also CC: @brucez-anyscale , @hanming-lu since the stack trace comes from auto-scaler

```
(autoscaler +31m25s) Cluster is terminating (reason: production job/service complete).
[2023-09-06 03:40:42,465 E 3744 3872] core_worker.cc:589: :info_message: Attempting to recover 4 lost objects by resubmitting their tasks. To disable object reconstruction, set @ray.remote(max_retries=0).
*** SIGTERM received at time=1693996843 on cpu 14 ***
PC: @     0x7fe09318a7d1  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
    @     0x7fe09318f420  (unknown)  (unknown)
    @ ... and at least 1 more frames
```

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by hanming-lu** [comment]
@raulchen @c21 what does this test do? It seems to be sending infeasible gang resource requests:
```
(autoscaler +29s) [autoscaler] Current infeasible gang resource requests: {"requests":[{"resourcesBundle":{"CPU":1}, "placementConstraints":[{"antiAffinity":{"labelName":"_PG_7df29998785b117ddc8ce708213502000000"}}]}, {"resourcesBundle":{"CPU":1}, "placementConstraints":[{"antiAffinity":{"labelName":"_PG_7df29998785b117ddc8ce708213502000000"}}]}, {"resourcesBundle":{"CPU":1}, "placementConstraints":[{"antiAffinity":{"labelName":"_PG_7df29998785b117ddc8ce708213502000000"}}]}, {"resourcesBundle":{"CPU":1}, "placementConstraints":[{"antiAffinity":{"labelName":"_PG_7df29998785b117ddc8ce708213502000000"}}]}, {"resourcesBundle":{"CPU":1}, "placementConstraints":[{"antiAffinity":{"labelName":"_PG_7df29998785b117ddc8ce708213502000000"}}]}, {"resourcesBundle":{"CPU":1}, "placementConstraints":[{"antiAffinity":{"labelName":"_PG_7df29998785b117ddc8ce708213502000000"}}]}, {"resourcesBundle":{"CPU":1}, "placementConstraints":[{"antiAffinity":{"labelName":"_PG_7df29998785b117ddc8ce708213502000000"}}]}, {"resourcesBundle":{"CPU":1}, "placementConstraints":[{"antiAffinity":{"labelName":"_PG_7df29998785b117ddc8ce708213502000000"}}]}, {"resourcesBundle":{"CPU":1}, "placementConstraints":[{"antiAffinity":{"labelName":"_PG_7df29998785b117ddc8ce708213502000000"}}]}, {"resourcesBundle":{"CPU":1}, "placementConstraints":[{"antiAffinity":{"labelName":"_PG_7df29998785b117ddc8ce708213502000000"}}]}, {"resourcesBundle":{"CPU":1}, "placementConstraints":[{"antiAffinity":{"labelName":"_PG_7df29998785b117ddc8ce708213502000000"}}]}, {"resourcesBundle":{"CPU":1}, "placementConstraints":[{"antiAffinity":{"labelName":"_PG_7df29998785b117ddc8ce708213502000000"}}]}, {"resourcesBundle":{"CPU":1}, "placementConstraints":[{"antiAffinity":{"labelName":"_PG_7df29998785b117ddc8ce708213502000000"}}]}, {"resourcesBundle":{"CPU":1}, "placementConstraints":[{"antiAffinity":{"labelName":"_PG_7df29998785b117ddc8ce708213502000000"}}]}, {"resourcesBundle":{"CPU":1}, "placementConstraints":[{"antiAffinity":{"labelName":"_PG_7df29998785b117ddc8ce708213502000000"}}]}, {"resourcesBundle":{"CPU":1}, "placementConstraints":[{"antiAffinity":{"labelName":"_PG_7df29998785b117ddc8ce708213502000000"}}]}], "details":"7df29998785b117ddc8ce708213502000000:STRICT_SPREAD|PENDING"}
```

**Comment by bveeramani** [comment]
Should be fixed by https://github.com/ray-project/ray/pull/39752

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2188#018ab8eb-002e-425e-972d-197b2e8bd85b

**Comment by scottjlee** [comment]
Potential fix with https://github.com/ray-project/ray/pull/39805, closing to run the test (seems that re-opening this issue when it was at jailed state immediately puts it back into jailed state, so it is not included in the nightly release test run).
