### ISSUE TITLE
Release test read_parquet_train_16_gpu.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#39310]
Release test **read_parquet_train_16_gpu.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2129#018a69fb-9263-473a-9d2d-c5389ba8d1ff for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by bveeramani** [comment]
Should be fixed by https://github.com/ray-project/ray/pull/39276, which was merged yesterday. Will monitor to see if the issue persists

**Comment by bveeramani** [comment]
Closing issue so test will run

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2183#018aa74f-d3b9-4e88-991e-0e805f14b94c

**Comment by bveeramani** [comment]
Should be fixed by https://github.com/ray-project/ray/pull/39752

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2188#018ab8f0-1fd9-4fbd-a947-5ad7d5dff24f

**Comment by scottjlee** [comment]
Potential fix with https://github.com/ray-project/ray/pull/39805, closing to run the test (seems that re-opening this issue when it was at jailed state immediately puts it back into jailed state, so it is not included in the nightly release test run).

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2192#018acb75-b2b5-49a7-9e9c-2b90d30a11c3
