### ISSUE TITLE
Release test read_parquet_train_4_gpu.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#39331]
Release test **read_parquet_train_4_gpu.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2129#018a6b5c-51a5-4087-bbaf-1ec9747152ef for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by bveeramani** [comment]
Should be fixed by https://github.com/ray-project/ray/pull/39276, which was merged yesterday. Will monitor to see if the issue persists

**Comment by can-anyscale** [comment]
Oh, we need to close the issue, otherwise the tests won't run nightly. I'll close this one then. The bot will reopen the issue if the test fails tonight.

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2183#018aa737-93eb-43a0-a7b8-36ff315fce70

**Comment by bveeramani** [comment]
Should be fixed by https://github.com/ray-project/ray/pull/39752

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2188#018ab8d5-904a-4cf4-b57c-96ba3af490ea

**Comment by bveeramani** [comment]
cc @scottjlee

**Comment by scottjlee** [comment]
Potential fix with https://github.com/ray-project/ray/pull/39805, closing to run the test (seems that re-opening this issue when it was at jailed state immediately puts it back into jailed state, so it is not included in the nightly release test run).

**Comment by scottjlee** [comment]
Potential fix with https://github.com/ray-project/ray/pull/39805, closing to run the test (seems that re-opening this issue when it was at jailed state immediately puts it back into jailed state, so it is not included in the nightly release test run).

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2192#018acb75-b2b1-4253-bbd1-873f53eec950
