### ISSUE TITLE
Release test read_images_comparison_microbenchmark_single_node.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#39378]
Release test **read_images_comparison_microbenchmark_single_node.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2134#018a6ed6-abb1-41fc-8321-fede0de5b401 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by can-anyscale** [comment]
Maybe same root cause with https://github.com/ray-project/ray/issues/39309?

**Comment by bveeramani** [comment]
Should be fixed by https://github.com/ray-project/ray/pull/39609

cc @scottjlee

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2188#018ab8d9-4a7d-48bd-abec-d07f490a1f58

**Comment by scottjlee** [comment]
Fixed by https://github.com/ray-project/ray/pull/39825

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2202#018ae020-6d2b-464f-82e3-c5b10f5b5ef6
