### ISSUE TITLE
Release test read_images_train_4_gpu.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#39728]
Release test **read_images_train_4_gpu.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2183#018aa738-5ca2-4e5e-99a6-3a40b55ff83f for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by bveeramani** [comment]
Should be fixed by https://github.com/ray-project/ray/pull/39752

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2188#018ab8d2-a5d2-4e6c-8301-f709c05713bc

**Comment by scottjlee** [comment]
Potential fix with https://github.com/ray-project/ray/pull/39805, closing to run the test (seems that re-opening this issue when it was at jailed state immediately puts it back into jailed state, so it is not included in the nightly release test run).

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2192#018acb75-b2a9-4a63-a644-b6013ddd919a
