### ISSUE TITLE
[autoscaler] Issues with gcp auto scaling

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#4072]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: latest wheel on 2019/02/16
- **Ray version**: latest wheel on 2019/02/16
- **Python version**: 3.6
- **Exact command to reproduce**: n/a

### Describe the problem
I'm seeing a ton of autoscaler errors when trying to run experiments on GCP. I believe these might be related to the threading changes that were introduced recently. I've been able to run things without problem with this same environment for a long time, and only after updating to the latest version started seeing these errors.

The reason I believe these might be related to the threading is that the errors happen pretty randomly, and despite them some of the worker nodes still get started correctly.

This makes the gcp autoscaling effectively unusable for me right now :(

### Source code / logs
```
=0.0, ResourceUsage=, TimeSinceLastHeartbeat=Min=-1 Mean=-1 Max=-1
2019-02-16 19:51:31,152	INFO autoscaler.py:599 -- StandardAutoscaler: Launching 5 new nodes
2019-02-16 19:51:34,049	ERROR autoscaler.py:364 -- StandardAutoscaler: Error during autoscaling.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 362, in update
    self._update()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 430, in _update
    nodes = self.workers()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 605, in workers
    return self.provider.nodes(tag_filters={TAG_RAY_NODE_TYPE: "worker"})
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/gcp/node_provider.py", line 86, in nodes
    filter=filter_expr,
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/http.py", line 852, in execute
    return self.postproc(resp, content)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/model.py", line 209, in response
    return self.deserialize(content)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/model.py", line 267, in deserialize
    body = json.loads(content)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 260, in run
    self._launch_node(config, count)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 250, in _launch_node
    }, count)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/gcp/node_provider.py", line 186, in create_node
    })).execute() for i in range(count)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/gcp/node_provider.py", line 186, in <listcomp>
    })).execute() for i in range(count)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 409 when requesting https://www.googleapis.com/compute/v1/projects/tuomas-softlearning/zones/us-west1-a/instances?alt=json returned "The resource 'projects/tuomas-softlearning/zones/us-west1-a/instances/ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-f1514413' already exists">

2019-02-16 19:51:36,192	INFO autoscaler.py:608 -- StandardAutoscaler: 2/10 target nodes (0 pending) (bringup=True)
2019-02-16 19:51:36,193	INFO autoscaler.py:609 -- LoadMetrics: NodeIdleSeconds=Min=1 Mean=1 Max=1, NumNodesConnected=1, NumNodesUsed=0.0, ResourceUsage=0.0/8.0 b'CPU', 0.0/0.0 b'GPU', TimeSinceLastHeartbeat=Min=0 Mean=0 Max=0
2019-02-16 19:51:36,193	INFO autoscaler.py:599 -- StandardAutoscaler: Launching 5 new nodes
2019-02-16 19:51:36,366	ERROR autoscaler.py:364 -- StandardAutoscaler: Error during autoscaling.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 362, in update
    self._update()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 430, in _update
    nodes = self.workers()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 605, in workers
    return self.provider.nodes(tag_filters={TAG_RAY_NODE_TYPE: "worker"})
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/gcp/node_provider.py", line 86, in nodes
    filter=filter_expr,
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/http.py", line 852, in execute
    return self.postproc(resp, content)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/model.py", line 209, in response
    return self.deserialize(content)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/model.py", line 267, in deserialize
    body = json.loads(content)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 260, in run
    self._launch_node(config, count)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 250, in _launch_node
    }, count)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/gcp/node_provider.py", line 186, in create_node
    })).execute() for i in range(count)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/gcp/node_provider.py", line 186, in <listcomp>
    })).execute() for i in range(count)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/http.py", line 183, in _retry_request
    raise exception
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/google_auth_httplib2.py", line 198, in request
    uri, method, body=body, headers=request_headers, **kwargs)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/httplib2/__init__.py", line 1924, in request
    cachekey,
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/httplib2/__init__.py", line 1595, in _request
    conn, request_uri, method, body, headers
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/httplib2/__init__.py", line 1533, in _conn_request
    response = conn.getresponse()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2273)

2019-02-16 19:51:41,504	ERROR autoscaler.py:364 -- StandardAutoscaler: Error during autoscaling.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 362, in update
    self._update()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 382, in _update
    nodes = self.workers()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 605, in workers
    return self.provider.nodes(tag_filters={TAG_RAY_NODE_TYPE: "worker"})
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/gcp/node_provider.py", line 86, in nodes
    filter=filter_expr,
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/http.py", line 183, in _retry_request
    raise exception
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/google_auth_httplib2.py", line 198, in request
    uri, method, body=body, headers=request_headers, **kwargs)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/httplib2/__init__.py", line 1924, in request
    cachekey,
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/httplib2/__init__.py", line 1595, in _request
    conn, request_uri, method, body, headers
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/httplib2/__init__.py", line 1562, in _conn_request
    content = response.read()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/http/client.py", line 456, in read
    return self._readall_chunked()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/http/client.py", line 563, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/http/client.py", line 546, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/http/client.py", line 506, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2273)
2019-02-16 19:51:46,330	INFO autoscaler.py:608 -- StandardAutoscaler: 6/10 target nodes (0 pending) (bringup=True)
2019-02-16 19:51:46,331	INFO autoscaler.py:609 -- LoadMetrics: NodeIdleSeconds=Min=11 Mean=11 Max=11, NumNodesConnected=1, NumNodesUsed=0.0, ResourceUsage=0.0/8.0 b'CPU', 0.0/0.0 b'GPU', TimeSinceLastHeartbeat=Min=0 Mean=0 Max=0
2019-02-16 19:51:46,331	INFO autoscaler.py:599 -- StandardAutoscaler: Launching 4 new nodes
2019-02-16 19:51:46,470	INFO autoscaler.py:608 -- StandardAutoscaler: 6/10 target nodes (4 pending) (bringup=True)
2019-02-16 19:51:46,471	INFO autoscaler.py:609 -- LoadMetrics: NodeIdleSeconds=Min=12 Mean=12 Max=12, NumNodesConnected=1, NumNodesUsed=0.0, ResourceUsage=0.0/8.0 b'CPU', 0.0/0.0 b'GPU', TimeSinceLastHeartbeat=Min=0 Mean=0 Max=0
2019-02-16 19:51:46,471	INFO autoscaler.py:518 -- StandardAutoscaler: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-4ef8168c: Runtime state is None, want bab730eb55995165c25bcf3c337e47b449bdb5cd
2019-02-16 19:51:46,471	INFO autoscaler.py:518 -- StandardAutoscaler: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-93a96efc: Runtime state is None, want bab730eb55995165c25bcf3c337e47b449bdb5cd
2019-02-16 19:51:46,471	INFO autoscaler.py:518 -- StandardAutoscaler: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-a923daf4: Runtime state is None, want bab730eb55995165c25bcf3c337e47b449bdb5cd
2019-02-16 19:51:46,471	INFO autoscaler.py:518 -- StandardAutoscaler: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-bb5bf423: Runtime state is None, want bab730eb55995165c25bcf3c337e47b449bdb5cd
2019-02-16 19:51:46,472	INFO autoscaler.py:518 -- StandardAutoscaler: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-e463bfec: Runtime state is None, want bab730eb55995165c25bcf3c337e47b449bdb5cd
2019-02-16 19:51:46,472	INFO autoscaler.py:518 -- StandardAutoscaler: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-f1514413: Runtime state is None, want bab730eb55995165c25bcf3c337e47b449bdb5cd
2019-02-16 19:51:46,474	INFO updater.py:128 -- NodeUpdater: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-4ef8168c: Updating to bab730eb55995165c25bcf3c337e47b449bdb5cd
2019-02-16 19:51:46,480	INFO updater.py:128 -- NodeUpdater: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-93a96efc: Updating to bab730eb55995165c25bcf3c337e47b449bdb5cd
2019-02-16 19:51:46,494	INFO updater.py:128 -- NodeUpdater: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-bb5bf423: Updating to bab730eb55995165c25bcf3c337e47b449bdb5cd
2019-02-16 19:51:46,503	INFO updater.py:128 -- NodeUpdater: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-a923daf4: Updating to bab730eb55995165c25bcf3c337e47b449bdb5cd
2019-02-16 19:51:46,512	INFO updater.py:128 -- NodeUpdater: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-e463bfec: Updating to bab730eb55995165c25bcf3c337e47b449bdb5cd
2019-02-16 19:51:46,518	INFO updater.py:128 -- NodeUpdater: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-f1514413: Updating to bab730eb55995165c25bcf3c337e47b449bdb5cd
2019-02-16 19:51:46,766	INFO log_timer.py:21 -- NodeUpdater: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-f1514413: Applied config bab730eb55995165c25bcf3c337e47b449bdb5cd [LogTimer=248ms]
2019-02-16 19:51:46,766	ERROR updater.py:140 -- NodeUpdater: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-f1514413: Error updating IncompleteRead(0 bytes read)
2019-02-16 19:51:47,591	INFO node_provider.py:25 -- wait_for_compute_zone_operation: Waiting for operation operation-1550346706780-5820838bc8343-a168b43c-30ad7521 to finish...
2019-02-16 19:51:47,818	INFO log_timer.py:21 -- NodeUpdater: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-93a96efc: Applied config bab730eb55995165c25bcf3c337e47b449bdb5cd [LogTimer=1337ms]
2019-02-16 19:51:47,818	ERROR updater.py:140 -- NodeUpdater: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-93a96efc: Error updating [SSL: DATA_LENGTH_TOO_LONG] data length too long (_ssl.c:2273)
2019-02-16 19:51:48,012	INFO log_timer.py:21 -- NodeUpdater: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-e463bfec: Applied config bab730eb55995165c25bcf3c337e47b449bdb5cd [LogTimer=1500ms]
2019-02-16 19:51:48,013	ERROR updater.py:140 -- NodeUpdater: ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-e463bfec: Error updating Invalid instance id ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-e463bfec
2019-02-16 19:51:48,917	INFO node_provider.py:25 -- wait_for_compute_zone_operation: Waiting for operation operation-1550346708180-5820838d1dd7d-9a52d477-a29846d6 to finish...
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 132, in run
    self.do_update()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 182, in do_update
    {TAG_RAY_NODE_STATUS: "waiting-for-ssh"})
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/gcp/node_provider.py", line 113, in set_node_tags
    node = self._get_node(node_id)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/gcp/node_provider.py", line 213, in _get_node
    self.nodes({})  # Side effect: fetches and caches the node.
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/gcp/node_provider.py", line 86, in nodes
    filter=filter_expr,
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/http.py", line 183, in _retry_request
    raise exception
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/googleapiclient/http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/google_auth_httplib2.py", line 198, in request
    uri, method, body=body, headers=request_headers, **kwargs)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/httplib2/__init__.py", line 1924, in request
    cachekey,
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/httplib2/__init__.py", line 1595, in _request
    conn, request_uri, method, body, headers
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/httplib2/__init__.py", line 1533, in _conn_request
    response = conn.getresponse()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DATA_LENGTH_TOO_LONG] data length too long (_ssl.c:2273)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 142, in run
    {TAG_RAY_NODE_STATUS: "update-failed"})
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/gcp/node_provider.py", line 113, in set_node_tags
    node = self._get_node(node_id)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/gcp/node_provider.py", line 216, in _get_node
    node_id)
AssertionError: Invalid instance id ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-93a96efc

Exception in thread Thread-13:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 132, in run
    self.do_update()
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 182, in do_update
    {TAG_RAY_NODE_STATUS: "waiting-for-ssh"})
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/gcp/node_provider.py", line 113, in set_node_tags
    node = self._get_node(node_id)
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/autoscaler/gcp/node_provider.py", line 216, in _get_node
    node_id)
AssertionError: Invalid instance id ray-20190216t114849-cc0e56-point2denv-wall-v0-worker-e463bfec
```

**Comment by hartikainen** [comment]
Things work fine when I downgrade to `ray==0.6.2`

**Comment by ericl** [comment]
Can you try https://github.com/ray-project/ray/pull/4074 out?

**Comment by hartikainen** [comment]
Seems promising. I don't see the errors I saw previously and the nodes start fine. I do the following in the logs though:
```
2019-02-17 06:04:14,803 INFO autoscaler.py:609 -- LoadMetrics: NodeIdleSeconds=Min=30 Mean=31 Max=31,
NumNodesConnected=4, NumNodesUsed=1.0, ResourceUsage=8.0/32.0 b'CPU', 0.0/0.0 b'GPU', TimeSinceLastHea
rtbeat=Min=0 Mean=24 Max=30
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
Monitor: could not find ip for client 1446ff23d8815716bc18ad9748c311dff1d63a58
```

Not sure if that's a problem or not. It doesn't seem to cause problems at least.

I'll report back tomorrow morning how the runs finish.

**Comment by hartikainen** [comment]
I'm not yet sure if this fixed my problem or not. I ran the experiment with your fixes and for some reason some of the runs kept stalling, whereas everything finished fine with the older version. I don't see any errors (other than the couple `Monitor: could not find ip for client` above), though, so it might be something else.

I'll get back to you once I've run some more experiments.

**Comment by richardliaw** [comment]
Wait it’s not clear that this issue is fixed right?

**Comment by hartikainen** [comment]
@richardliaw true, I'm not 100% sure it got fixed. I'll try running some tests in a moment and report back how it goes.

**Comment by hartikainen** [comment]
Yeah, it seems like there's still something wrong with the GCP autoscaler. Here are some of the errors that I see in the logs:
```
2019-02-21 02:46:38,782 INFO autoscaler.py:608 -- StandardAutoscaler: 5/1 target nodes (0 pending) (1 updating)
2019-02-21 02:46:38,783 INFO autoscaler.py:609 -- LoadMetrics: NodeIdleSeconds=Min=17 Mean=21 Max=29, NumNodesConnected=3, NumNodesUsed=1.0, ResourceUsage=8.0/24.0 b'CPU', 0.0/0.0 b'GPU', TimeSinceLastHea
rtbeat=Min=0 Mean=13 Max=17
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
Monitor: could not find ip for client d558c9d5f22ef4dceb75cc0ae5b448a0e4a0e029
```
```
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/autoscaler/updater.py", line 132, in run
    self.do_update()
  File "/home/ubuntu/ray/python/ray/autoscaler/updater.py", line 189, in do_update
    ssh_ok = self.wait_for_ssh(deadline)
  File "/home/ubuntu/ray/python/ray/autoscaler/updater.py", line 158, in wait_for_ssh
    not self.provider.is_terminated(self.node_id):
  File "/home/ubuntu/ray/python/ray/autoscaler/gcp/node_provider.py", line 105, in is_terminated
    node = self._get_cached_node(node_id)
  File "/home/ubuntu/ray/python/ray/autoscaler/gcp/node_provider.py", line 237, in _get_cached_node
    return self._get_node(node_id)
  File "/home/ubuntu/ray/python/ray/autoscaler/gcp/node_provider.py", line 229, in _get_node
    node_id)
AssertionError: Invalid instance id ray-20190220t175319-2f5f11-point2denv-wall-v0-worker-c91504d8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/softlearning/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/ray/python/ray/autoscaler/updater.py", line 142, in run
    {TAG_RAY_NODE_STATUS: "update-failed"})
  File "/home/ubuntu/ray/python/ray/autoscaler/gcp/node_provider.py", line 120, in set_node_tags
    node = self._get_node(node_id)
  File "/home/ubuntu/ray/python/ray/autoscaler/gcp/node_provider.py", line 229, in _get_node
    node_id)
AssertionError: Invalid instance id ray-20190220t175319-2f5f11-point2denv-wall-v0-worker-c91504d8

2019-02-21 04:01:53,373 INFO autoscaler.py:608 -- StandardAutoscaler: 7/7 target nodes (0 pending) (2 updating)
2019-02-21 04:01:53,374 INFO autoscaler.py:609 -- LoadMetrics: NodeIdleSeconds=Min=0 Mean=0 Max=0, NumNodesConnected=7, NumNodesUsed=7.0, ResourceUsage=56.0/56.0 b'CPU', 0.0/0.0 b'GPU', TimeSinceLastHeartbeat=Min=0 Mean=8 Max=67
2019-02-21 04:01:53,532 ERROR autoscaler.py:364 -- StandardAutoscaler: Error during autoscaling.
Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/autoscaler/autoscaler.py", line 362, in update
    self._update()
  File "/home/ubuntu/ray/python/ray/autoscaler/autoscaler.py", line 449, in _update
    self.load_metrics.mark_active(self.provider.internal_ip(node_id))
  File "/home/ubuntu/ray/python/ray/autoscaler/gcp/node_provider.py", line 152, in internal_ip
    node = self._get_cached_node(node_id)
  File "/home/ubuntu/ray/python/ray/autoscaler/gcp/node_provider.py", line 237, in _get_cached_node
    return self._get_node(node_id)
  File "/home/ubuntu/ray/python/ray/autoscaler/gcp/node_provider.py", line 229, in _get_node
    node_id)
AssertionError: Invalid instance id ray-20190220t175319-2f5f11-point2denv-wall-v0-worker-c91504d8
```
```
2019-02-21 04:12:30,832 WARNING autoscaler.py:534 -- StandardAutoscaler: ray-20190220t175319-2f5f11-point2denv-wall-v0-worker-b1fef1a9: No heartbeat in 32.93967413902283s, restarting Ray to recover...
```

This is run from the latest master which has @ericl's fixes merged. I got the full logs available if those help.

**Comment by ericl** [comment]
Ok, we might have to go back to the process based one then. Seems like there is some issue that locks didn't fix.
