### ISSUE TITLE
[data] slow consumers don't trigger backpressure

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#40753]
Today, the code that consumes data (`iter_batches/iter_row`) isn't a part of DAG. Thus the streaming executor doesn't take the consuming speed into account for backpressure. 

In the following example, the map will keep producing data although the consumers are halted.

```python
import ray
import time
import numpy as np

N = 1_000_000
S = 10

ds = ray.data.range(N)

def produce_data(input):
    id = input["id"]
    print("producing", id)
    return {
        "id": id,
        "data": np.zeros(1024 * 1024, dtype=np.uint8)
    }

ds = ds.map(produce_data)

splits = ds.streaming_split(S)


@ray.remote
class Consumer:
    def __init__(self,  index):
        self.index = index
        self.count = 0

    def start(self, it):
        print(f"Consumer {self.index} starting")
        for _ in it.iter_rows():
            self.count += 1
            if self.count == 100:
                print(f"Consumer {self.index} reached 100")
                time.sleep(10)
                print(f"Consumer {self.index} done sleeping")
                break

consumers = [Consumer.remote(i) for i in range(S)]
for i, it in enumerate(splits):
    consumers[i].start.remote(it)

time.sleep(100)
```

**Comment by ericl** [comment]
I tried this out and I believe this should actually be fixed by streaming generator backpressure as well.

When you make the following change, backpressure works and the execution halts when object store memory reaches the limit (e.g., `1.74 GiB / 1.74 GiB`):

```
N = 10000
S = 10

ds = ray.data.range(N, parallelism=N)
```

I guess without backpressure, the generator task will keep producing rows for the block until the entire block for the task is done, ignoring the memory quota.

**Comment by anyscalesam** [comment]
Done

**Comment by xhook** [comment]
Do I understand correctly that this issue was not actually solved, but moved to the #40754 ?
