### ISSUE TITLE
"'Middleware' object has no attribute options" error with Ray server proxy using fastapi >= 0.109.0

### ISSUE THREAD

**Issue by JoeSF49** [ray-project/ray#42654]
### What happened + What you expected to happen

Error:  "'Middleware' object has no attribute options"   against self.wrapped_http_proxy in ProxyActor.__init__()

Ray serve fails to start using fastapi 0.109.0.  Downgrading to fastapi 0.108.0 allows serve.start method to start proxy actor in healthy  state so i can run serve.run on the deployment bind.   I'm using serve.start to specify the host, port, and timeouts as the host and port parameters within serve.run directly are deprecated. i'm not even using fastapi. I'm using starlette.requests for raw Request method.  

Note: I'm not even trying to use fastapi however the latest is installed when installing updating ray[serve] then breaks my working code.  I'm using starlette.requests for raw Request method

### Versions / Dependencies

ray 2.9.1
fastapi 0.109.0

### Reproduction script

I don't have specific code snippet  due to work however the basic documented ray-serve quickstart using @serve.deployment decorator on class, then app bind deployment, then serve.start to specify custom host/port with following serve.run OR just running serve.run directly allowing for defaults errors with 'Middleware' attribute error.  Serve ProxyActor  errors and subsequent starts just hangs on 'starting' state when i check serve.status()

Note: I'm using starlette.requests for raw Request method.  not even using fastapi (yet), app decorators just raw starlette.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by GeneDer** [comment]
Should be fixed in Ray 2.9.2

**Comment by JoeSF49** [comment]
Yes it has.  I tested Ray 2.9.2 along with the latest fastapi.

Thank you.

**Comment by HarryCaveMan** [comment]
I am seeing this issue still on `rayproject/ray:2.9.2-py310` with fastapi upgraded to `0.110.0`.

**Comment by HarryCaveMan** [comment]
Confirmed `ray[serve]==2.9.3` works fine with `fastapi==0.110.0`. However, the `ray 2.9.3`.
Please also see:
https://github.com/ray-project/ray/commit/570932614301fa80b98635fbe97792a2e9608f98
