### ISSUE TITLE
[tune] Performance collapses with thousands of queued jobs

### ISSUE THREAD

**Issue by max333** [ray-project/ray#4366]
### System information
- **Ray version**: 0.6.2 to at least March 12th nightly

When there are thousands of trials queued (not even running), the master node performance is very poor and it processes results from the nodes very slowly.  The nodes cpu utilization is very low.

Here is an example where this problem happens:
```
import time

from ray import tune
import ray.tune.util
from ray.tune import trainable


class IdleTrainable(trainable.Trainable):

    def _setup(self, config):
        self.name = config['name']
        self.timeout = config['timeout']

    def _train(self):
        time.sleep(self.timeout)
        string = f"hello from {self.name}"
        print(f"done: {self.name}")
        return {'done': True, 'message': string}

timeout = 3

def build_experiment(i):
    name = f"exp{i}"
    return tune.Experiment(
                run=IdleTrainable,
                name=name,
                config={"name": name,
                        "timeout": timeout},
                #num_samples=1, # We are using repeats instead.
                checkpoint_at_end=False,
                local_dir="/tmp/rayidle",
                # It seems this means a thread and not a full core.
                resources_per_trial={'cpu': 1})

ray.init()
n_jobs = 2500
experiments = [build_experiment(i) for i in range(n_jobs)]

tune.run_experiments(experiments, verbose=False)
```
You can run this locally and see that the jobs (trials) are processed very slowly.  However if you change `n_jobs = 100`, than the _rate_ at which the jobs are processed is much faster.  So the this bug is directly related to the length of the list of jobs.  I explain why below.

And here is the associated stack trace:
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   2352/1    0.074    0.000   66.300   66.300 {built-in method builtins.exec}
        1    0.000    0.000   66.299   66.299 junk_ray.py:1(<module>)
        1    0.000    0.000   62.646   62.646 tune.py:55(run_experiments)
       35    0.002    0.000   62.637    1.790 trial_runner.py:218(step)
       35    0.000    0.000   43.330    1.238 trial_runner.py:377(_get_next_trial)
       35    0.055    0.002   40.574    1.159 trial_scheduler.py:86(choose_trial_to_run)
    33375    0.028    0.000   40.519    0.001 trial_runner.py:373(has_resources)
    33375    0.089    0.000   40.491    0.001 ray_trial_executor.py:320(has_resources)
    33411    0.345    0.000   40.011    0.001 ray_trial_executor.py:292(_update_avail_resources)
   167051    0.558    0.000   39.222    0.000 state.py:750(cluster_resources)
   167051    0.232    0.000   38.638    0.000 state.py:390(client_table)
   167051    2.000    0.000   38.356    0.000 state.py:20(parse_client_table)
       34    0.004    0.000   17.156    0.505 trial_runner.py:127(checkpoint)
       68    3.035    0.045   17.107    0.252 __init__.py:120(dump)
```

The issue is the performance of method `FIFOScheduler.choose_trial_to_run(trial_runner)` in tune/scheduler/trial_scheduler.py when there are no resources available.  This method loops over the complete list of trials to see if any one of them is small enough to run given the current available resources.  But checking each trial ends up calling `parse_client_table(redis_client)` in tune/experimental/state.py which is very slow (> 1 ms) because it communicates with the redis server.  

So if the list of trials contains thousands of items, it will take *many seconds* to iterate over the whole list to realize that not a single job can run when there are 0 cpus available.  This is why the master has very poor performance and can't process results from the nodes.

Note that in the main master loop, `FIFOScheduler.choose_trial_to_run(trial_runner)` is basically called in two different situations: right after a job completed and right after a job started.  In the first case, `FIFOScheduler.choose_trial_to_run(trial_runner)` will run very quickly because it will find a job to run given that some resources were just freed by the completed job.  However, when a new job just started, it is likely that there are no resources left (unless it's at the very beginning or the user just added new resources) and it is in those cases that `FIFOScheduler.choose_trial_to_run(trial_runner)` iterates over the full list of jobs and finds no runnable job and occupies the master thread for many seconds.  

So every time a new result comes in and a new job starts, the master thread basically freezes for a few seconds.

**Comment by ericl** [comment]
Yep, looks like self.has_resources is much more expensive than it needs to be: https://github.com/ray-project/ray/blob/d5f46983056642ad0a2e4dff2a0030845f5c3f03/python/ray/tune/ray_trial_executor.py#L359

**Comment by ericl** [comment]
A reasonable fix would to be to avoid calling `_update_avail_resources` unless there is actually a state change in the cluster.

**Comment by max333** [comment]
But then it's not clear how the trial executor ever becomes aware that the user changed resources.  

Currently every single pending trial calls `_update_avail_resources`, but maybe it could only be called once instead.

**Comment by ericl** [comment]
I see, it makes sense to call it once in a while. Perhaps at the beginning of `choose_trial_to_run`?

**Comment by richardliaw** [comment]
Actually, I think it would be OK if we just call it on `TrialExecutor.on_step_begin` and remove it from `has_resources`.

**Comment by richardliaw** [comment]
Addressed in https://github.com/ray-project/ray/pull/4379.

**Comment by max333** [comment]
Sounds good to just leave `_update_avail_resources` in `TrialExecutor.on_step_begin` and remove it from `has_resources`.

However, `self.trial_executor.has_resources(trial.resources)` is called in `TrialRunner._try_recover`.  This is called in the main loop (`TrialRunner._process_trial`) in case `self.trial_executor.fetch_result(trial)` raises an exception.  Since `fetch_result` is a blocking call, there might have been resources added in the meantime.  So maybe `TrialExecutor._update_avail_resources` should be called at the start of `TrialRunner._try_recover` too.  However TrialRunner would be calling a private method of TrialExecutor.

**Comment by max0x7ba** [comment]
> When there are thousands of trials queued (not even running), the master node performance is very poor and it processes results from the nodes very slowly. The nodes cpu utilization is very low.

I still face this very issue with ray-1.3.0. What is a solution for it, please?
