### ISSUE TITLE
Release test rllib_learning_tests_ppo_new_api_stack_torch.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#43720]
Release test **rllib_learning_tests_ppo_new_api_stack_torch.aws** failed. See https://buildkite.com/ray-project/release/builds/10431#018e0e4a-bed2-4fac-81d4-911f40a2d57b for more details.

Managed by OSS Test Policy

**Comment by anyscalesam** [comment]
@sven1977 any update on this; we need confirmation that this is/is-not a release-blocker for ray210

**Comment by sven1977** [comment]
Ok, seems to be a wront machine config on our end. 4 GPUs where 8 needed. Will fix asap ...

**Comment by sven1977** [comment]
Closing this issue. Fixed by https://github.com/ray-project/ray/pull/44001

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/11364#018e40a9-0d08-4a0d-a61f-727e7786ca6a

**Comment by khluu** [comment]
This test still failed on releases/2.10.0 branch even after the fix was cherry picked in @sven1977

**Comment by khluu** [comment]
@sven1977 confirmed the test works when kicked off manually

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/11543#018e5541-f276-4b5c-8b85-e42a93201d0e

**Comment by can-anyscale** [comment]
https://github.com/ray-project/ray/pull/44116 to mark this test as unstable

**Comment by can-anyscale** [comment]
was not a blocker for 2.10

**Comment by sven1977** [comment]
Closing. This CI test has been stabilized
