### ISSUE TITLE
Remote functions and actors do not properly handle kwargs.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#439]
Currently, we have the following behavior.

```python
import ray

ray.init()

@ray.remote
def f():
  return

f.remote(x=1)  # This does not throw an exception, but it should.
```

**Comment by raopku** [comment]
Not only remote function, but also actor
I got an exception when i create an Actor
`Exception: Actors currently do not support **kwargs.`

**Comment by robertnishihara** [comment]
At the moment, remote functions and actors don't support `**kwargs` arguments.

As a workaround for now, you might try doing something like the following.

```python
@ray.actor
class A(B):
    def __init__(self, nb_actions, gamma=.99, batch_size=32, memory=None):
        super(A, self).__init__(memory=memory)
```

**Comment by robertnishihara** [comment]
Does that work for your current use case? Or do you need `**kwargs`?

If `B` is a class that you implemented, you could make it take a dictionary instead of `**kwargs`.

**Comment by raopku** [comment]
interesting
it looks like actor does not support default parameters value

```
@ray.actor
class MyAgent(object):
    def __init__(self,nb_actions,batch_size=32):
        #self.model = model_from_config(model_config)
        self.nb_actions=nb_actions
        self.batch_size=batch_size
    
    def get_batch_size(self):
        return self.batch_size

myactor1 = MyAgent(2,90)(works)
myactor2 = MyAgent(2,batch_size=90)(Exception: Actors currently do not support **kwargs.)
```

**Comment by robertnishihara** [comment]
I think this was fixed yesterday in #441. Can you check what commit you're at (e.g., via `git log`)?

**Comment by raopku** [comment]
After i update the ray.
```
@ray.actor
class MyAgent(object):
    def __init__(self,nb_actions,batch_size=32):
        #self.model = model_from_config(model_config)
        self.nb_actions=nb_actions
        self.batch_size=batch_size
    
    def get_batch_size(self):
        return self.batch_size

myactor1 = MyAgent(2,90)(works)
myactor2 = MyAgent(2,batch_size=90)(works)
```

However, this code is still not work.

```
class A(object):
    def __init__(self,memory=None):
        self.memory = memory
@ray.actor
class B(A):
    def __init__(self, nb_actions, gamma=.99, batch_size=32, memory=None):
        super(B, self).__init__(memory=memory)
        self.nb_actions=3

actor=B(3,memory=8)
```
So how can i pass a value to parameter of super class?

**Comment by robertnishihara** [comment]
Let me think about this more, it looks like a pickling problem. At least on my machine, without using Ray, the following code fails.

```python
import cloudpickle

class A(object):
  pass

class B(A):
  def __init__(self):
    super(B, self).__init__()

cloudpickle.dumps(B)
```

The last line throws the following exception.

```python
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
/Users/rkn/anaconda3/lib/python3.6/site-packages/cloudpickle/cloudpickle.py in dump(self, obj)
    145         try:
--> 146             return Pickler.dump(self, obj)
    147         except RuntimeError as e:

/Users/rkn/anaconda3/lib/python3.6/pickle.py in dump(self, obj)
    408             self.framer.start_framing()
--> 409         self.save(obj)
    410         self.write(STOP)

/Users/rkn/anaconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return

/Users/rkn/anaconda3/lib/python3.6/site-packages/cloudpickle/cloudpickle.py in save_global(self, obj, name, pack)
    424 
--> 425             self.save_reduce(typ, (obj.__name__, obj.__bases__, d), obj=obj)
    426         else:

/Users/rkn/anaconda3/lib/python3.6/site-packages/cloudpickle/cloudpickle.py in save_reduce(self, func, args, state, listitems, dictitems, obj)
    585             save(func)
--> 586             save(args)
    587             write(pickle.REDUCE)

/Users/rkn/anaconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return

/Users/rkn/anaconda3/lib/python3.6/pickle.py in save_tuple(self, obj)
    735             for element in obj:
--> 736                 save(element)
    737             # Subtle.  Same as in the big comment below.

/Users/rkn/anaconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return

/Users/rkn/anaconda3/lib/python3.6/pickle.py in save_dict(self, obj)
    820         self.memoize(obj)
--> 821         self._batch_setitems(obj.items())
    822 

/Users/rkn/anaconda3/lib/python3.6/pickle.py in _batch_setitems(self, items)
    846                     save(k)
--> 847                     save(v)
    848                 write(SETITEMS)

/Users/rkn/anaconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return

/Users/rkn/anaconda3/lib/python3.6/site-packages/cloudpickle/cloudpickle.py in save_function(self, obj, name)
    263                 or themodule is None):
--> 264             self.save_function_tuple(obj)
    265             return

/Users/rkn/anaconda3/lib/python3.6/site-packages/cloudpickle/cloudpickle.py in save_function_tuple(self, func)
    311         save(_make_skel_func)
--> 312         save((code, closure, base_globals))
    313         write(pickle.REDUCE)

/Users/rkn/anaconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return

/Users/rkn/anaconda3/lib/python3.6/pickle.py in save_tuple(self, obj)
    735             for element in obj:
--> 736                 save(element)
    737             # Subtle.  Same as in the big comment below.

/Users/rkn/anaconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return

/Users/rkn/anaconda3/lib/python3.6/pickle.py in save_list(self, obj)
    780         self.memoize(obj)
--> 781         self._batch_appends(obj)
    782 

/Users/rkn/anaconda3/lib/python3.6/pickle.py in _batch_appends(self, items)
    807             elif n:
--> 808                 save(tmp[0])
    809                 write(APPEND)

... last 16 frames repeated, from the frame below ...

/Users/rkn/anaconda3/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return

RecursionError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

PicklingError                             Traceback (most recent call last)
<ipython-input-2-e105f7705909> in <module>()
----> 1 cloudpickle.dumps(B)

/Users/rkn/anaconda3/lib/python3.6/site-packages/cloudpickle/cloudpickle.py in dumps(obj, protocol)
    704 
    705     cp = CloudPickler(file,protocol)
--> 706     cp.dump(obj)
    707 
    708     return file.getvalue()

/Users/rkn/anaconda3/lib/python3.6/site-packages/cloudpickle/cloudpickle.py in dump(self, obj)
    148             if 'recursion' in e.args[0]:
    149                 msg = """Could not pickle object as excessively deep recursion required."""
--> 150                 raise pickle.PicklingError(msg)
    151 
    152     def save_memoryview(self, obj):

PicklingError: Could not pickle object as excessively deep recursion required.
```

**Comment by robertnishihara** [comment]
I created a separate issue #449 to track this problem with subclasses.

**Comment by robertnishihara** [comment]
Closing because the original issue (in the first post) was fixed in #441 I believe.
