### ISSUE TITLE
Release test air_example_vicuna_13b_lightning_deepspeed_finetuning failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#46709]
Release test **air_example_vicuna_13b_lightning_deepspeed_finetuning** failed. See https://buildkite.com/ray-project/release/builds/19693#0190cbc8-7ffa-4efc-8541-b2e25961665e for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by aslonnie** [comment]
fix maybe: https://buildkite.com/ray-project/release/builds/19770

**Comment by aslonnie** [comment]
test pasing: https://buildkite.com/ray-project/release/builds/19771#0190cfcd-8e99-4d1c-aae1-49a6c6c8c3c3 how to unjail this?

**Comment by can-anyscale** [comment]
nice, just close this issue after you merge the fix will unjail this

**Comment by aslonnie** [comment]
fixed by https://github.com/ray-project/ray/pull/46723

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/19763#0190d821-5d4b-4c50-819e-22b001e0f22b

**Comment by aslonnie** [comment]
the commit is merged after the run.

@khluu you should not have retried it.

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/19976#0190e8a5-16cc-4c7b-836d-70706e01615e

**Comment by aslonnie** [comment]
this was due to last night's mass failing, on many of the long running release tests that hit the time point.

**Comment by can-anyscale** [comment]
let's close so that it can run again

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release/builds/19976#0190ebcf-11a0-465d-9548-999217fe38af
