### ISSUE TITLE
Release test aggregate_benchmark.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#48176]
Release test **aggregate_benchmark.aws** failed. See https://buildkite.com/ray-project/release/builds/24221#0192b2c2-d3d3-4b5b-9cf8-51e87286c14f for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: 26bdd948d78fb65e04d4053a3fc17f83bfa509e0 found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/1640

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by can-anyscale** [comment]
fixed, to confirm

**Comment by scottjlee** [comment]
Fixed by https://github.com/ray-project/ray/pull/48209

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/24456#0192c241-79d5-4d01-946c-5fd92916f3c1

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release/builds/24591#0192c756-9cdf-45cf-a22a-4558fe96756e
