### ISSUE TITLE
[Ray Core] `ray.data.Dataset.repartition` not working consistently with doc/error message

### ISSUE THREAD

**Issue by marcmk6** [ray-project/ray#51060]
### What happened + What you expected to happen

```
ds = ds.repartition(num_blocks=x, target_num_rows_per_block=y)
```
Obviously it's conflicting to setting both. Calling this gives the error `ValueError: Either num_blocks or target_num_rows_per_block must be set, but not both.`, as expected.

But this doesn't work `ds = ds.repartition(target_num_rows_per_block=y)`. I got `TypeError: Dataset.repartition() missing 1 required positional argument: 'num_blocks'`

This doesn't seem to make sense to me. According to [doc](https://docs.ray.io/en/latest/data/api/doc/ray.data.Dataset.repartition.html), it should be happy with one of the 2 arguments given. 

### Versions / Dependencies

ray 2.43.0
Python 3.11.11
Ubuntu 22.04.3 LTS

### Reproduction script

```
import ray
ds = ray.data.range(100)
ds.repartition(target_num_rows_per_block=10)
```

### Issue Severity

None

**Comment by richardliaw** [comment]
Seems like a bug. 

cc @srinathk10 @raulchen - we should fix this by the next release

**Comment by srinathk10** [comment]
@marcmk6 PR https://github.com/ray-project/ray/pull/50997/ is addressing this issue.

**Comment by raulchen** [comment]
https://github.com/ray-project/ray/pull/50997 doesn't address this issue. 
ds.repartition(target_num_rows_per_block=10) would still fail. You'll need to do ds.repartition(num_blocks =None, target_num_rows_per_block=10), which looks very cumbersome. 
I still think we should make num_blocks default to None
