### ISSUE TITLE
[Core] Raylet heartbeat misses

### ISSUE THREAD

**Issue by testinfected** [ray-project/ray#54321]
### What happened + What you expected to happen

I'm using Ray Core 2.47 with Kuberay 1.4.0 with a GKE cluster.

I'm seeing Raylet heartbeat misses quite frequently, such as:

```
[2025-07-03 11:12:01,375 I 42 42] (gcs_server) gcs_node_manager.cc:386: Removing node, node name = 172.24.1.211, death reason = UNEXPECTED_TERMINATION, death message = Raylet could not connect to Runtime Env Agent node_id=3f59adf5c5637be592d585665324bc4d7e22d22f86bc0a4847c89076
[2025-07-03 11:12:01,375 W 42 42] (gcs_server) gcs_node_manager.cc:415: The node with node id: 3f59adf5c5637be592d585665324bc4d7e22d22f86bc0a4847c89076 and address: 172.24.1.211 and node name: 172.24.1.211 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a (1) raylet crashes unexpectedly (OOM, etc.)
 (2) raylet has lagging heartbeats due to slow network or busy workload.
```

What could be the cause of those errors? I don't know where to look.

Thanks

### Versions / Dependencies

Ray 2.4.7 and KubeRay 1.4.0

### Reproduction script

Simple sleep task:

```python
import time
import ray

ray.init()

sleep_sec = 300
num_tasks = 2000

test_start = time.time()

@ray.remote(num_cpus=1)
def sleep_task(sleep_sec: int):
    time.sleep(sleep_sec)

res_refs = [sleep_task.remote(sleep_sec) for _ in range(num_tasks - 1)]
res = ray.get(res_refs)

test_end = time.time()
run_time = test_end - test_start

print(
    f"Scale test with {num_tasks} tasks ran in"
    + f" {run_time:.1f} secs.\n"
)

### Issue Severity

None

**Comment by edoakes** [comment]
@testinfected this can happen under network degradation or heavy CPU contention. Are you by chance using very small pods in your KubeRay cluster?

**Comment by testinfected** [comment]
I have a setup on GKE and I've run on machines with 64 CPUS, with 60 allocated to the pod for the Ray worker node. In fact I see this problem In GKE and also on our on prem cluster in different configurations. I'd like to investigate but don't know where to start.

What would you recommend?

**Comment by testinfected** [comment]
It seems the runtime env agent not starting is the cause of the issue:

`(raylet, ip=172.24.105.136) [2025-06-12 06:52:31,835 E 99 99] (raylet) runtime_env_agent_client.cc:336: Runtime Env Agent timed out in 30000ms. Status: NotFound: on_connect Connection refused, address: 172.24.105.136, port: 53090, existing immediately... [repeated 1419x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(raylet, ip=172.24.105.136) [2025-06-12 06:52:31,835 E 99 99] (raylet) runtime_env_agent_client.cc:292: The raylet exited immediately because the runtime env agent timed out when Raylet try to connect to it. This can happen because the runtime env agent was never started, or is listening to the wrong port. Read the log `cat /tmp/ray/session_latest/logs/runtime_env_agent.log`. You can find the log file structure here https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#logging-directory-structure. [repeated 1418x across cluster]
`
Any idea what is happening here?

**Comment by edoakes** [comment]
Are there relevant logs in `/tmp/ray/session_latest/logs/runtime_env_agent.{log,err,out}`?

**Comment by testinfected** [comment]
The node disappears when I'm investigating. I've tried autoscaler v1 and v2. What's the best way to keep the node alive to have time to investigate?

**Comment by edoakes** [comment]
In general I'd recommend exporting logs to persistent storage ([example](https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/persist-kuberay-custom-resource-logs.html#setting-up-logging-sidecars-with-fluent-bit)).

In this case you might be able to delay the node being removed by tuning these environment variables up in your container image:
```
# This will take ~10min before a node is marked as dead.
RAY_health_check_failure_threshold=10
RAY_health_check_period_ms=6000
```

I'm not completely sure that this will work though -- KubeRay might still remove the pod because `ray start` failed.

**Comment by testinfected** [comment]
We will try that thank you

**Comment by testinfected** [comment]
Btw, are there any more debug logs that we can activate or is everything already logged by default?

**Comment by edoakes** [comment]
> Btw, are there any more debug logs that we can activate or is everything already logged by default?

You can set `RAY_BACKEND_LOG_LEVEL=debug` to enable debug-level, but I'd suggest first checking without that as it will be significantly more verbose.

**Comment by testinfected** [comment]
I've got some additional info. Setting debug logs did not help but something I noticed when I get the `runtime_env_agent` error is that the `runtime_env_agent.{err,log}` show no errors but the `runtime_env_agent.out` is empty. On healthy nodes it contains a line saying it's running (as per https://github.com/aio-libs/aiohttp/blob/3d969a334830e4ca7ff9b30e176d78ceff341db4/aiohttp/web.py#L412).

So somehow the agent does not start but doesn't report any error. Might be stuck? (see logs attached)

[agent.log](https://github.com/user-attachments/files/21170909/agent.log)

[raylet.out.txt](https://github.com/user-attachments/files/21170922/raylet.out.txt)
[agent.err.txt](https://github.com/user-attachments/files/21170923/agent.err.txt)
[agent.out.txt](https://github.com/user-attachments/files/21170925/agent.out.txt)
[raylet.err.txt](https://github.com/user-attachments/files/21170924/raylet.err.txt)

**Comment by testinfected** [comment]
Apparently we can get some extra information on what's happening in the event loop by using the `debug` parameter (see https://github.com/aio-libs/aiohttp/blob/3d969a334830e4ca7ff9b30e176d78ceff341db4/aiohttp/web.py#L472) but there's no way to set it in the Ray code: https://github.com/ray-project/ray/blob/be0959c06a3a92cf51a087b5b7bb563311bfa66e/python/ray/_private/runtime_env/agent/main.py#L225

Would it be possible to have e.g. an env variable to control that and get the debug statements for the event loop?

**Comment by edoakes** [comment]
The `agent.log` that you posted appears to match the expected logs when the agent does start up successfully. I ran some tests locally, and when it is running as expected the logs contain (prior to running anything on the cluster):
```
2025-07-11 11:17:11,569 INFO runtime_env_agent.py:193 -- Starting runtime env agent at pid 1779
2025-07-11 11:17:11,570 INFO runtime_env_agent.py:194 -- Parent raylet pid is 1776
2025-07-11 11:17:11,571 INFO runtime_env_agent.py:252 -- Listening to address 127.0.0.1, port 58191
```

**Comment by edoakes** [comment]
Ah I see what you mean now, the `runtime_env_agent.out` file contains the `aiohttp` startup log

**Comment by edoakes** [comment]
We can consider adding an env var to set debug mode on the asyncio loop, but from my experience it's unlikely to be very helpful.

One thing I'd suggest is attaching to the process using [py-spy](https://github.com/benfred/py-spy). The `py-spy dump` command will give you the current stack trace of the threads in the process. If something is hanging, that should reveal it.

**Comment by testinfected** [comment]
> Ah I see what you mean now, the `runtime_env_agent.out` file contains the `aiohttp` startup log
 
Yes and it stays empty which indicates it's probably stuck in the loop waiting for the web server to start:
https://github.com/aio-libs/aiohttp/blob/3d969a334830e4ca7ff9b30e176d78ceff341db4/aiohttp/web.py#L407

**Comment by pankajs9999** [comment]
So, the `py-spy dump` output for the working and problematic raylets nodes are same. The only difference is problematic raylet parent process only abled to start the `log_monitor.py` process whereas the working one abled to start other processes like `dashboard/agent.py` and `runtime_env/agent/main.py` as well. 

`working raylet:
~$ py-spy dump --pid 1
Python v3.9.22 (/home/ray/anaconda3/bin/python3.9)

Thread 1 (idle): "MainThread"
    start (ray/scripts/scripts.py:1193)
    wrapper (ray/autoscaler/_private/cli_logger.py:823)
    invoke (click/core.py:783)
    invoke (click/core.py:1434)
    invoke (click/core.py:1688)
    main (click/core.py:1078)
    __call__ (click/core.py:1157)
    main (ray/scripts/scripts.py:2800)
    <module> (ray:8)

--> ports in use on the working raylet
Netid          State           Recv-Q           Send-Q                     Local Address:Port                      Peer Address:Port          Process                                                 
tcp            LISTEN          0                128                              0.0.0.0:52365                          0.0.0.0:*              users:(("python3.9",pid=1510824,fd=34))                
tcp            LISTEN          0                5                                0.0.0.0:8080                           0.0.0.0:*              users:(("python3.9",pid=1510824,fd=33))                
tcp            LISTEN          0                128                              0.0.0.0:59527                          0.0.0.0:*              users:(("python3.9",pid=1510826,fd=28))   

Problematic raylet:
$ py-spy dump --pid 1

Thread 1 (idle): "MainThread"
    start (ray/scripts/scripts.py:1193)
    wrapper (ray/autoscaler/_private/cli_logger.py:823)
    invoke (click/core.py:783)
    invoke (click/core.py:1434)
    invoke (click/core.py:1688)
    main (click/core.py:1078)
    __call__ (click/core.py:1157)
    main (ray/scripts/scripts.py:2800)
    <module> (ray:8)

--> no ports are in listening on the problematic raylet
Netid               State               Recv-Q               Send-Q                             Local Address:Port                              Peer Address:Port               Process 
`

Also, the problematic raylet was initially abled to sent the heartbeat but it failed afterwards. If a try to start the `ray` on it manually, it worked fine. 

`autoscaling-cluster-large-group-worker-fvxxx   1/1     Running   0          73s`    
`autoscaling-cluster-large-group-worker-fvxxx   1/1     Running   0          87s`   
`autoscaling-cluster-large-group-worker-fvxxx   0/1     Running   0          93s`

**Comment by testinfected** [comment]
@pankajs9999 and I are working on this together.

We were not seeing anything on the problematic node since the Raylet exits and stops all child processes. We traced it to this code: https://github.com/ray-project/ray/blob/c56cf90720d2d4812674a9cfaf84d1863f1be848/src/ray/raylet/runtime_env_agent_client.cc#L327

What is surprising is that we never hit the last branch of the if, which suggests we are already passed the deadline when entering this function the first time. 

We increased the `agent_register_timeout_ms` to 10 minutes (https://github.com/ray-project/ray/blob/c56cf90720d2d4812674a9cfaf84d1863f1be848/src/ray/common/ray_config_def.h#L568) to be able to see where the agent process hangs, but haven't been able to reproduce the issue yet.

What makes things even more difficult to troubleshoot is the fact we can't reproduce consistently. It might run ok several times, then fail. We can never be confident that the problem is solved.

**Comment by testinfected** [comment]
We were able to reproduce the issue today with a much larger register timeout:

```console
[33m(raylet, ip=172.28.137.100)[0m [2025-07-14 23:51:35,491 E 98 98] (raylet) runtime_env_agent_client.cc:336: Runtime Env Agent timed out in 40000ms. Status: NotFound: on_connect Connection refused, address: 172.28.137.100, port: 59098, existing immediately...[32m [repeated 48x across cluster][0m
[33m(raylet, ip=172.28.137.100)[0m [2025-07-14 23:51:35,491 E 98 98] (raylet) runtime_env_agent_client.cc:292: The raylet exited immediately because the runtime env agent timed out when Raylet try to connect to it. This can happen because the runtime env agent was never started, or is listening to the wrong port. Read the log `cat /tmp/ray/session_latest/logs/runtime_env_agent.log`.
```

**Comment by edoakes** [comment]
> We were able to reproduce the issue today with a much larger register timeout:

Oh this is great! Was the agent process running during the time before the timeout occurred? If so, were you able to capture its stack trace with `py-spy`?

**Comment by testinfected** [comment]
No unfortunately we could not. We need to figure out which one is not starting before the deadline is reached, after what the process are killed. Will try again

**Comment by testinfected** [comment]
Finally was able to capture the thread dump and the flamegraph for the problem.

[profile.speedscope.json](https://github.com/user-attachments/files/21263870/profile.speedscope.json)

[runtime_env_agent.dump.txt](https://github.com/user-attachments/files/21263890/runtime_env_agent.dump.txt)

**Comment by testinfected** [comment]
So I guess the agent dies right away but for some reason it hangs on shutdown in that finally branch cancelling the task. Why it dies in the first place I have no clue though. Could be a race condition.

**Comment by andrewsykim** [comment]
Similar to @ryanaoleary's comment in https://github.com/ray-project/kuberay/issues/3794#issuecomment-3084808786, I suggest removing CPU limits in your pod specs to rule out CPU throttling that could be happening from cgroups. Just a hunch but something that is very easy to rule out. Starting in KubeRay v1.3, only CPU requests are required, limits can be unset

**Comment by testinfected** [comment]
Just run into the issue rn on GKE on 1000 nodes with 32 CPUs each. Requested 10 CPUs per worker node, no limit. Batch of 10k tasks:

```
2025-07-18 07:19:51,801 DEBUG (unknown file):0 -- gc.collect() freed 11 refs in 0.03372916900002565 seconds
(raylet) The node with node id: 6e71a9cad276c76d20261932457c08ebb0d836547619f0a0cef14cee and address: 172.24.38.146 and node name: 172.24.38.146 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a     (1) raylet crashes unexpectedly (OOM, etc.)
        (2) raylet has lagging heartbeats due to slow network or busy workload.
(raylet, ip=172.24.38.146) [2025-07-18 07:20:02,004 E 66 66] (raylet) runtime_env_agent_client.cc:336: Runtime Env Agent timed out in 30000ms. Status: NotFound: on_connect Connection refused, address: 172.24.38.146, port: 52196, existing immediately...
(raylet, ip=172.24.38.146) [2025-07-18 07:20:02,004 E 66 66] (raylet) runtime_env_agent_client.cc:292: The raylet exited immediately because the runtime env agent timed out when Raylet try to connect to it. This can happen because the runtime env agent was never started, or is listening to the wrong port. Read the log `cat /tmp/ray/session_latest/logs/runtime_env_agent.log`. You can find the log file structure here https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#logging-directory-structure.
```

**Comment by testinfected** [comment]
One reason this can happen is a port conflict. I patched the `aiohttp` lib to print the stacktrace in case of exception and got this today:

```
Traceback (most recent call last):
 File "/home/ray/anaconda3/lib/python3.9/site-packages/aiohttp/web.py", line 524, in run_app
 loop.run_until_complete(main_task)
 File "/home/ray/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
 return future.result()
 File "/home/ray/anaconda3/lib/python3.9/site-packages/aiohttp/web.py", line 428, in _run_app
 await site.start()
 File "/home/ray/anaconda3/lib/python3.9/site-packages/aiohttp/web_runner.py", line 121, in start
 self._server = await loop.create_server(
 File "/home/ray/anaconda3/lib/python3.9/asyncio/base_events.py", line 1506, in create_server
 raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 53078): address already in use
```

Note that in this case I rerun a test case on a head node that was already Running. I don't if it is the same issue when the head node is fresh.

**Comment by testinfected** [comment]
I'm trying to figure out how/where the port number is allocated. Any idea?

**Comment by testinfected** [comment]
> I'm trying to figure out how/where the port number is allocated. Any idea?

Is it in `node.py` `_get_unused_port`?

If yes I don't understand how we prevent a race condition from happening and another process on the host to take that port before the runtime env agent actually starts?

**Comment by testinfected** [comment]
> > I'm trying to figure out how/where the port number is allocated. Any idea?
> 
> Is it in `node.py` `_get_unused_port`?
> 
> If yes I don't understand how we prevent a race condition from happening and another process on the host to take that port before the runtime env agent actually starts?

This is reminiscent of #8254 don't you think?

**Comment by edoakes** [comment]
@testinfected yes you're right it appears that we currently determine the port in `_get_unused_port`, and there could be a race condition where the port is taken by another process between `_get_unused_port` and the agent starting up.

To guard against this, I would recommend specifying a port that you know is reserved/unused on the machine.

**Comment by testinfected** [comment]
I see. Since we're running on Kubernetes that port has to be taken up by another ray component process right?

We can definitely specify ports for every component (dashboard, runtime env, etc).

That being said, what about improving the error handling logic around https://github.com/ray-project/ray/blob/5c06ef6e8ee26634d324ed1501c4aee60811f428/python/ray/_private/runtime_env/agent/main.py#L224? 
Making sure all exceptions when starting up are recorded in the `runtime_env_agent.err` log file would help diagnose the issue, wdygt?

**Comment by edoakes** [comment]
> Making sure all exceptions when starting up are recorded in the `runtime_env_agent.err` log file would help diagnose the issue, wdygt?

Totally agree! What is happening to the output of `web.run_app` currently? At a minimum we can add a `try: except:` there and log any exception tracebacks that it throws.

**Comment by testinfected** [comment]
There would need a `try: except:` indeed to catch `OSError`s like that and at least print the stack trace in the Runtime Env Agent logs

**Comment by testinfected** [comment]
I ran into the issue again today while running background tests in our on premise cluster. This time I captured the netstat output at the time of failure: 

[netstat.out.txt](https://github.com/user-attachments/files/21434452/netstat.out.txt)

I suspect that once the `node.py` code has checked for a random available port, bound to it and released it, the socket is still in `TIME_WAIT` when the runtime environment agent starts and tries to bind to the same port. 

If this is the case, the solution would simply to call `aiohttp` `web.run_app` with `reuse_port=True` (see https://github.com/aio-libs/aiohttp/blob/911645731da52f0572484b86729b2dab141a090f/aiohttp/web.py#L465)

That port is not supposed to be used by any other process, and there aren't any running in the pods except for the ones started by Ray

**Comment by edoakes** [comment]
> I suspect that once the `node.py` code has checked for a random available port, bound to it and released it, the socket is still in `TIME_WAIT` when the runtime environment agent starts and tries to bind to the same port.

This could definitely be the case!

> If this is the case, the solution would simply to call aiohttp web.run_app with reuse_port=True

I wouldn't want to do this in general, as not all users run Ray in a containerized fashion and this could cause very strange failure modes.

We could also implement a retry/timeout policy for binding to the port. At a minimum, we can try binding a few times (maybe up to 10s), which should be long enough for the port to be freed by the OS.

**Comment by testinfected** [comment]
> > I suspect that once the `node.py` code has checked for a random available port, bound to it and released it, the socket is still in `TIME_WAIT` when the runtime environment agent starts and tries to bind to the same port.
> 
> This could definitely be the case!
> 
> > If this is the case, the solution would simply to call aiohttp web.run_app with reuse_port=True
> 
> I wouldn't want to do this in general, as not all users run Ray in a containerized fashion and this could cause very strange failure modes.

Could you at least make that an configuration option maybe? Or make it the default for KubeRay provider whatever makes more sense
> 
> We could also implement a retry/timeout policy for binding to the port. At a minimum, we can try binding a few times (maybe up to 10s), which should be long enough for the port to be freed by the OS.

**Comment by testinfected** [comment]
Coming back to this, any idea when we can expect a new version of ray that would solve the issue?

Thanks

**Comment by jjyao** [comment]
@testinfected we are discussing a solution internally and once we agree on it, I'll try to find some resource to work on it.

**Comment by shomilj** [comment]
We also just ran into this issue. If there is code that is racy in the port discovery logic under high load, it would be awesome if it were fixed w/ high priority! 🙏

**Comment by pxp531** [comment]
> I suspect that once the `node.py` code has checked for a random available port, bound to it and released it, the socket is still in `TIME_WAIT` when the runtime environment agent starts and tries to bind to the same port.

What is being mentioned here is that when using random ports, attempting to bind and then closing can cause this issue. If the user specifies the runtime-env-agent-port when starting ray, is there still a possibility of encountering this problem? I would like to know if this issue occurred to you because no specific ports were specified and they were all randomly assigned? thanks
@testinfected @edoakes

**Comment by Hxinyue** [comment]
We attempted to set it up using the following fixed ports:
`
worker:
  ...
  rayStartParams:
    runtime-env-agent-port: 'xxxxx'
`
However, this problem still occurs:
The node with node id: 5d0da9d7f80164c7d61df8addb6a5d80a9d36ec3d8f988c0eef6b545 and address: 192.168.10.175 and node name: 192.168.10.175 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a (1) raylet crashes unexpectedly (OOM, etc.)
(2) raylet has lagging heartbeats due to slow network or busy workload.

**Comment by amruth-sn** [comment]
@Hxinyue @pxp531 From my understanding of the issue, setting a fixed port via `runtime-env-agent-port` doesn't reduce the odds of the race condition occurring. The port is unidirectionally fixed only from the perspective of the binding agent to the raylet itself, not vice versa, ergo any other agent/process can still takeover, if that makes sense. 

Although, I would like to know more about why this is mitigated in [#59613](https://github.com/ray-project/ray/pull/59613).

Feel free to correct me because I could be wrong!
