### ISSUE TITLE
[rllib] Actor died unexpectedly before finishing this task.

### ISSUE THREAD

**Issue by davidcotton** [ray-project/ray#5820]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: pip
- **Ray version**: 0.7.5
- **Python version**: 3.6.8
- **Exact command to reproduce**: `ray.get(future)` (see code below)

### Describe the problem

Apologies if this issue is because I'm doing something wrong. 

I'm trying to use [Global Coordination](https://ray.readthedocs.io/en/latest/rllib-training.html#global-coordination) to make a stateful policy mapping function. I've found that if I try to get the value of a future from a remote object in either a RLlib callback, policy mapping function or custom train function, Ray/the actor dies with `ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.` 

### Source code / logs

This minimal example should be all you need to reproduce.
```
from gym.envs.classic_control import CartPoleEnv
import ray
from ray import tune
from ray.experimental import named_actors

@ray.remote
class Counter:
    def __init__(self):
        self.count = 0
    def inc(self, n):
        self.count += n
    def get(self):
        return self.count

class CountingCartpole(CartPoleEnv):
    def step(self, action):
        counter = named_actors.get_actor("global_counter")
        counter.inc.remote(1)
        return super().step(action)

def on_episode_end(info):
    counter = named_actors.get_actor("global_counter")
    future = counter.get.remote()
    count = ray.get(future)
    print(count)

if __name__ == "__main__":
    ray.init()
    named_actors.register_actor("global_counter", Counter.remote())
    tune.register_env("counting_cartpole", lambda _: CountingCartpole())
    trials = tune.run(
        "PG",
        stop={"training_iteration": 10},
        config={
            "env": "counting_cartpole",
            "callbacks": {"on_episode_end": on_episode_end},
        }
    )
```

```
(pid=68066) 2019-10-02 16:40:10,472	INFO tf_run_builder.py:92 -- Executing TF run without tracing. To dump TF timeline traces to disk, set the TF_TIMELINE_DIR environment variable.
2019-10-02 16:40:10,517	ERROR trial_runner.py:560 -- Error processing event.
Traceback (most recent call last):
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 506, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 347, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/worker.py", line 2349, in get
    raise value
ray.exceptions.RayTaskError: ray_PG:train() (pid=68066, host=dave)
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 417, in train
    raise e
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 406, in train
    result = Trainable.train(self)
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/tune/trainable.py", line 176, in train
    result = self._train()
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 129, in _train
    fetches = self.optimizer.step()
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/optimizers/sync_samples_optimizer.py", line 70, in step
    samples.append(self.workers.local_worker().sample())
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 469, in sample
    batches = [self.input_reader.next()]
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 56, in next
    batches = [self.get_data()]
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 99, in get_data
    item = next(self.rollout_provider)
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 319, in _env_runner
    soft_horizon, no_done_at_end)
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 473, in _process_observations
    "episode": episode
  File "/home/dave/projects/test_rllib/test.py", line 29, in on_episode_end
    count = ray.get(future)
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
```

**Comment by stephanie-wang** [comment]
Actors will exit when the original handle to the actor is out of scope, so the actor's probably exiting here before it can execute the task. Try keeping the original handle to the actor around by doing something like this:
```
    c = Counter.remote()
    named_actors.register_actor("global_counter", c)
```
instead of this:
```
    named_actors.register_actor("global_counter", Counter.remote())
```

**Comment by stephanie-wang** [comment]
Actually, there appears to be something else going on. I'll try to investigate more.

**Comment by davidcotton** [comment]
Thanks heaps for the help @stephanie-wang! I've implemented your fix and it solves the `ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task` error.

With the updated code I now get the following errors (Ray 0.7.5):
```
(pid=7832) 2019-10-08 12:54:40,669	INFO sample_batch_builder.py:161 -- Trajectory fragment after postprocess_trajectory():
(pid=7832)
(pid=7832) { 'agent0': { 'data': { 'action_logp': np.ndarray((19,), dtype=float32, min=-0.695, max=-0.691, mean=-0.693),
(pid=7832)                         'action_prob': np.ndarray((19,), dtype=float32, min=0.499, max=0.501, mean=0.5),
(pid=7832)                         'actions': np.ndarray((19,), dtype=int64, min=0.0, max=1.0, mean=0.368),
(pid=7832)                         'advantages': np.ndarray((19,), dtype=float32, min=1.0, max=17.383, mean=9.425),
(pid=7832)                         'agent_index': np.ndarray((19,), dtype=int64, min=0.0, max=0.0, mean=0.0),
(pid=7832)                         'dones': np.ndarray((19,), dtype=bool, min=0.0, max=1.0, mean=0.053),
(pid=7832)                         'eps_id': np.ndarray((19,), dtype=int64, min=1755434577.0, max=1755434577.0, mean=1755434577.0),
(pid=7832)                         'infos': np.ndarray((19,), dtype=object, head={}),
(pid=7832)                         'new_obs': np.ndarray((19, 4), dtype=float32, min=-1.368, max=2.053, mean=0.052),
(pid=7832)                         'obs': np.ndarray((19, 4), dtype=float32, min=-1.368, max=2.053, mean=0.043),
(pid=7832)                         'prev_actions': np.ndarray((19,), dtype=int64, min=0.0, max=1.0, mean=0.316),
(pid=7832)                         'prev_rewards': np.ndarray((19,), dtype=float32, min=0.0, max=1.0, mean=0.947),
(pid=7832)                         'rewards': np.ndarray((19,), dtype=float32, min=1.0, max=1.0, mean=1.0),
(pid=7832)                         't': np.ndarray((19,), dtype=int64, min=0.0, max=18.0, mean=9.0),
(pid=7832)                         'unroll_id': np.ndarray((19,), dtype=int64, min=0.0, max=0.0, mean=0.0),
(pid=7832)                         'value_targets': np.ndarray((19,), dtype=float64, min=0.0, max=0.0, mean=0.0)},
(pid=7832)               'type': 'SampleBatch'}}
(pid=7832)
(pid=raylet) F1008 12:54:40.655108  7785 node_manager.cc:1798]  Check failed: static_cast<int64_t>(spec.ActorCounter()) == expected_task_counter Expected actor counter: 1, task c2305678fa8d7d58f41501000000 has: 0
(pid=raylet) *** Check failure stack trace: ***
(pid=raylet)     @           0x6f8d1a  google::LogMessage::Fail()
(pid=raylet)     @           0x6fa103  google::LogMessage::SendToLog()
(pid=raylet)     @           0x6f8a42  google::LogMessage::Flush()
(pid=raylet)     @           0x6f8c31  google::LogMessage::~LogMessage()
(pid=raylet)     @           0x52b0d2  ray::RayLog::~RayLog()
(pid=raylet)     @           0x45df3f  ray::raylet::NodeManager::AssignTask()
(pid=raylet)     @           0x45e6c7  ray::raylet::NodeManager::DispatchTasks()
(pid=raylet)     @           0x463dea  ray::raylet::NodeManager::HandleWorkerAvailable()
(pid=raylet)     @           0x46b32f  ray::raylet::NodeManager::ProcessClientMessage()
(pid=raylet)     @           0x433a4d  _ZNSt17_Function_handlerIFvSt10shared_ptrIN3ray16ClientConnectionIN5boost4asio5local15stream_protocolEEEElPKhEZNS1_6raylet6Raylet12HandleAcceptERKNS3_6system10error_codeEEUlS8_lSA_E0_E9_M_invokeERKSt9_Any_dataS8_lSA_
(pid=raylet)     @           0x50a7e0  ray::ClientConnection<>::ProcessMessage()
(pid=raylet)     @           0x508b5a  boost::asio::detail::read_op<>::operator()()
(pid=raylet)     @           0x508ca3  boost::asio::detail::reactive_socket_recv_op<>::do_complete()
(pid=raylet)     @           0x425bcd  boost::asio::detail::scheduler::run()
(pid=raylet)     @           0x40fb1d  main
(pid=raylet)     @     0x7f6e70cc4b97  __libc_start_main
(pid=raylet)     @           0x4207e1  (unknown)
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/dave/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/191.7141.48/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/dave/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/191.7141.48/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/dave/projects/test_rllib/test1.py", line 47, in <module>
    "callbacks": {"on_episode_end": tune.function(on_episode_end)},
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/tune/tune.py", line 244, in run
    runner.step()
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 336, in step
    self._process_events()  # blocking
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 500, in _process_events
    trial = self.trial_executor.get_next_available_trial()  # blocking
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 323, in get_next_available_trial
    [result_id], _ = ray.wait(shuffled_results)
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/worker.py", line 2499, in wait
    worker.current_task_id,
  File "python/ray/_raylet.pyx", line 527, in ray._raylet.CoreWorker.wait
  File "python/ray/_raylet.pyx", line 98, in ray._raylet.check_status
ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Raylet connection closed.
E1008 12:54:40.766768  8489 raylet_client.cc:339] IOError: [RayletClient] Connection closed unexpectedly. [RayletClient] Failed to push profile events.
(pid=7816) Traceback (most recent call last):
(pid=7816)   File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/workers/default_worker.py", line 98, in <module>
(pid=7816)     ray.worker.global_worker.main_loop()
(pid=7816)   File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/worker.py", line 1118, in main_loop
(pid=7816)     task = self._get_next_task_from_raylet()
(pid=7816)   File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/worker.py", line 1101, in _get_next_task_from_raylet
(pid=7816)     task = self.raylet_client.get_task()
(pid=7816)   File "python/ray/_raylet.pyx", line 291, in ray._raylet.RayletClient.get_task
(pid=7816)   File "python/ray/_raylet.pyx", line 98, in ray._raylet.check_status
(pid=7816) ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Raylet connection closed.
```
and in 0.7.3 & 0.7.4 I get:
```
(pid=10654) 2019-10-08 13:04:47,899	INFO trainer.py:339 -- Tip: set 'eager': true or the --eager flag to enable TensorFlow eager execution
2019-10-08 13:04:48,245	ERROR trial_runner.py:552 -- Error processing event.
Traceback (most recent call last):
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 498, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 347, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/worker.py", line 2332, in get
    raise value
ray.exceptions.RayTaskError: ray_PG:train() (pid=10654, host=dave)
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 412, in train
    raise e
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 401, in train
    result = Trainable.train(self)
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/tune/trainable.py", line 171, in train
    result = self._train()
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 129, in _train
    fetches = self.optimizer.step()
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/optimizers/sync_samples_optimizer.py", line 62, in step
    samples.append(self.workers.local_worker().sample())
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 472, in sample
    batches = [self.input_reader.next()]
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 56, in next
    batches = [self.get_data()]
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 99, in get_data
    item = next(self.rollout_provider)
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 319, in _env_runner
    soft_horizon, no_done_at_end)
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 473, in _process_observations
    "episode": episode
  File "/home/dave/projects/test_rllib/venv/lib/python3.6/site-packages/ray/tune/sample.py", line 45, in __call__
    return self.func(*args, **kwargs)
  File "/home/dave/projects/test_rllib/test1.py", line 29, in on_episode_end
    count = ray.get(future)
ray.exceptions.UnreconstructableError: Object e5ffbb0ddcef7d58f4150100000000c001000000 is lost (either evicted or explicitly deleted) and cannot be reconstructed.
```
However, I've found that the code runs successfully with `ray.init(local_mode=True)` in 0.7.3

With the help of some debugging print statements it looks like new error still occurs on the `ray.get(future)` line.

**Comment by stephanie-wang** [comment]
Thanks, @davidcotton! The issue that you're getting has to do with the way Ray maintains handles to named actors. Hopefully that will be fixed with #5814.

For your particular application, you can actually fix it by saving the actor handle directly in the environment and reusing it later on in the callback. I'd recommend using this kind of pattern wherever possible instead of named actors. Here's some example code:
```python
from gym.envs.classic_control import CartPoleEnv
import ray
from ray import tune


@ray.remote
class Counter:
    def __init__(self):
        self.count = 0
    def inc(self, n):
        self.count += n
    def get(self):
        return self.count

class CountingCartpole(CartPoleEnv):
    def __init__(self, counter):
        super().__init__()
        self.counter = counter

    def step(self, action):
        self.counter.inc.remote(1)
        return super().step(action)

def on_episode_end(info):
    # Get the counter that was saved in the env instead of the named actor.
    env = info["env"].get_unwrapped()[0]
    future = env.counter.get.remote()
    count = ray.get(future)
    print(count)

if __name__ == "__main__":
    ray.init()
    # Need to keep around c to prevent the actor from exiting.
    c = Counter.remote()
    tune.register_env("counting_cartpole", lambda _: CountingCartpole(c))
    trials = tune.run(
        "PG",
        stop={"training_iteration": 100},
        config={
            "env": "counting_cartpole",
            "callbacks": {"on_episode_end": on_episode_end},
        }
    )
```

**Comment by janblumenkamp** [comment]
Is this supposed to be fixed? It appears to me that this error still persists. I created the following example:
```
import ray
from ray import tune
from ray.rllib.examples.custom_env import SimpleCorridor

if __name__ == '__main__':
    ray.init()
    tune.run(
        "PPO",
        checkpoint_freq=10,
        config={
            "env": SimpleCorridor,
            "lambda": 0.95,
            "kl_coeff": 0.5,
            "horizon": 250,
            "clip_rewards": True,
            "clip_param": 0.2,
            "vf_clip_param": 10.0,
            "entropy_coeff": 0.01,
            "train_batch_size": 5000,
            "sample_batch_size": 100,
            "sgd_minibatch_size": 500,
            "num_sgd_iter": 10,
            "num_workers": 31,
            "num_envs_per_worker": 256,
            "batch_mode": "truncate_episodes",
            "observation_filter": "NoFilter",
            "vf_share_layers": True,
            "tf_session_args": {
                "gpu_options": {"allow_growth": True},
            },
            "env_config": {"corridor_length": 5}
           })
```
I am working on a cluster. I started the application on a single node with 32 cores. The error log is huge and I can't really make anything out of it. It seems to me that ray creates a directory each worker in the ray_results directory:
```
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae214f84_2019-12-27_14-03-38iohf82gs
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae214fca_2019-12-27_14-03-38psvjm457
drwx------+ 2 jb2270 jb2270      7 Dec 27 14:08 PPO_SimpleCorridor_ae214fe8_2019-12-27_14-03-38eed_yp0x
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae215006_2019-12-27_14-03-3888enc08f
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae215038_2019-12-27_14-03-38a0enl6jh
drwx------+ 2 jb2270 jb2270      7 Dec 27 14:08 PPO_SimpleCorridor_ae23e208_2019-12-27_14-03-386cowy29w
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae23e208_2019-12-27_14-03-38ysw5xw_m
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae23e9a6_2019-12-27_14-03-38_fwjkuna
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae250f52_2019-12-27_14-03-387rmu2wyn
drwx------+ 2 jb2270 jb2270      7 Dec 27 14:08 PPO_SimpleCorridor_ae25cf82_2019-12-27_14-03-38zxgzkh3d
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae26e30e_2019-12-27_14-03-38078feqfg
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae270a1e_2019-12-27_14-03-38nive2288
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae270bae_2019-12-27_14-03-38en2a8hde
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae270c3a_2019-12-27_14-03-38rmug58dg
drwx------+ 2 jb2270 jb2270      7 Dec 27 14:08 PPO_SimpleCorridor_ae270db6_2019-12-27_14-03-381mrftkfr
drwx------+ 2 jb2270 jb2270      7 Dec 27 14:08 PPO_SimpleCorridor_ae2712ac_2019-12-27_14-03-38p6ycb2sq
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae2712ca_2019-12-27_14-03-381zp0haeq
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae293d48_2019-12-27_14-03-38hetzdgas
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae2a76b8_2019-12-27_14-03-38kod0ea4b
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae2ef1fc_2019-12-27_14-03-385kl4rx1d
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae2f2b72_2019-12-27_14-03-38ypqd6opq
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_ae634d1c_2019-12-27_14-03-38v0kfog4h
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_aea5b51c_2019-12-27_14-03-39w8z3v3yy
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_aed7bfc6_2019-12-27_14-03-39e6flgpxb
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_af1173c4_2019-12-27_14-03-39q8wcbbc8
drwx------+ 2 jb2270 jb2270      7 Dec 27 14:11 PPO_SimpleCorridor_af6fb768_2019-12-27_14-03-40kb72ry2u
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_afa11f10_2019-12-27_14-03-4080ftvs0l
drwx------+ 2 jb2270 jb2270      7 Dec 27 14:08 PPO_SimpleCorridor_afd6e71c_2019-12-27_14-03-410b2yc0op
drwx------+ 2 jb2270 jb2270      7 Dec 27 14:11 PPO_SimpleCorridor_afe12ff6_2019-12-27_14-03-41bjmzldam
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_afffc696_2019-12-27_14-03-41mmo4ls_7
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_b036c420_2019-12-27_14-03-41vx2bj9pv
drwx------+ 2 jb2270 jb2270      6 Dec 27 14:03 PPO_SimpleCorridor_b0952d30_2019-12-27_14-03-42owo3qmd0
```
 This seems weird to me because if I start ray on a GPU node with a multi core processor, only a single directory is created. In some of the created directories, an error.txt was created that says

```
Failure £ 1 (occurred at 2019-12-27_14-11-29)
Traceback (most recent call last):
  File "/home/jb2270/venv_project_cpu/lib64/python3.6/site-packages/ray/tune/trial_runner.py", line 426, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/jb2270/venv_project_cpu/lib64/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 378, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/jb2270/venv_project_cpu/lib64/python3.6/site-packages/ray/worker.py", line 1459, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
```
The stdout of the application can be found here:
[slurm-18207458.txt](https://github.com/ray-project/ray/files/4005510/slurm-18207458.txt)
It contains references to the error.txt in the directories in the ray_results directory and ends with multiple lines of `A worker died or was killed while executing task`. Could somebody explain to me what the problem is? Please let me know if additional details are required.

**Comment by davidcotton** [comment]
Hi @janblumenkamp, it looks like the issue you describe is different to the one I encountered. The issue I had involved sharing state between actors in callbacks or policy mapping functions. A combination of; Steph's solution, avoiding named_actors, and the Ray 0.7.6 patch fixed things for me. 

The code sample you've provided looks like a pretty straightforward PPO task. I don't have access to a cluster but was able to run it successfully on a single machine. In the error log file you provide I can see
```
Traceback (most recent call last):
  File "/home/jb2270/venv_project_cpu/lib64/python3.6/site-packages/ray/tune/trial_runner.py", line 345, in step
    self.checkpoint()
  File "/home/jb2270/venv_project_cpu/lib64/python3.6/site-packages/ray/tune/trial_runner.py", line 276, in checkpoint
    os.rename(tmp_file_name, self.checkpoint_file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/jb2270/ray_results/PPO/.tmp_checkpoint' -> '/home/jb2270/ray_results/PPO/experiment_state-2019-12-27_14-03-38.json'
2019-12-27 14:04:04,218	ERROR trial_runner.py:347 -- Trial Runner checkpointing failed.

...

[2m[36m(pid=122072)[0m terminate called after throwing an instance of 'std::system_error'
[2m[36m(pid=122072)[0m   what():  Resource temporarily unavailable
[2m[36m(pid=122072)[0m Fatal Python error: Aborted
[2m[36m(pid=122072)[0m 
[2m[36m(pid=122072)[0m Stack (most recent call first):
[2m[36m(pid=122072)[0m   File "/home/jb2270/venv_project_cpu/lib64/python3.6/site-packages/ray/worker.py", line 1241 in connect
[2m[36m(pid=122072)[0m   File "/home/jb2270/venv_project_cpu/lib64/python3.6/site-packages/ray/workers/default_worker.py", line 117 in <module>
```
Is it possible that you don't have permission to write the experiment log files (json & tensorboard) and this causing a fatal error?

**Comment by janblumenkamp** [comment]
Thanks for your ideas! The weird thing is if I launch it in the same environment with `num_workers=1` it is working ([refer this log file](https://github.com/ray-project/ray/files/4006212/slurm-18209362.txt)). The errors you mention then occur as well, generally it seems like many of the error messages in the beginning are the same (not sure if they are cause for concern?). I guess it has something to do with missing resources, but from the log I can't really infer what resources are missing because the memory usage seems to be fine...

**Comment by davidcotton** [comment]
>>> it seems like many of the error messages in the beginning are the same

Ray creates duplicate error messages for each worker. Also some of the stuff I saw was just warnings/suggestions, like install ray[debug]

My experience with Ray resource allocation is that it gives you pretty clear error messages when you push it too far. I was able to run your code for about 25 iterations with 20 workers (my machine limit) before I stopped it, so I think your issue might be with the cluster setup

**Comment by zpymyyn** [comment]
Hi, I've met with a similar issue, using a hpc cluster from my university. 

    E0401  15541 raylet_client.cc:343] IOError: [RayletClient] Connection closed 
    unexpectedly. [RayletClient] Failed to push profile events.

    Traceback (most recent call last):

    ....

    worker.current_task_id,

    File "python/ray/_raylet.pyx", line 271, in ray._raylet.RayletClient.wait

    File "python/ray/_raylet.pyx", line 61, in ray._raylet.check_status

    ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Raylet connection closed

Could this IOError be that I don't have permission to use that amount of throughput...?

**Comment by aidanmclaughlin** [comment]
@janblumenkamp that issue persists for me still. I have a 20-thread processor, but when num_workers > 2, I get this error. Any progress?

**Comment by InTheta** [comment]
having same issue, could be docker issue?
unable to complete a training session
