### ISSUE TITLE
Symmetric run not working on slurm

### ISSUE THREAD

**Issue by barbara-su** [ray-project/ray#58875]
### What happened + What you expected to happen

This is my python code. It's just a dummy testing script:

```
import os
import socket
from collections import Counter
import ray
import os
import socket
import ray
def main():
    print("Connecting with ray.init(address='auto')", flush=True)
    ray.init(address="auto")

    print("\nCluster resources:")
    print(ray.cluster_resources(), flush=True)

    @ray.remote
    def worker_info(i):
        
        ctx = ray.get_runtime_context()
        return {
            "task_id": i,
            "pid": os.getpid(),
            "hostname": socket.gethostname(),
            "node_id": ctx.node_id.hex(),
        }

    num_tasks = 300
    print(f"\nLaunching {num_tasks} tasks\n", flush=True)
    futures = [worker_info.remote(i) for i in range(num_tasks)]
    results = ray.get(futures)

    for r in results:
        print(f"task {r['task_id']:2d}  host={r['hostname']}  pid={r['pid']}")

    host_counts = Counter(r["hostname"] for r in results)
    print("\nTask distribution by host:")
    for host, cnt in host_counts.items():
        print(f"{host}: {cnt} tasks")

    if len(host_counts) >= 2:
        print("\nMulti node behavior confirmed.")
    else:
        print("\nWarning: tasks only ran on one node.")


if __name__ == "__main__":
    main()
```

And here is my sbatch sh file
```
#!/bin/bash
#SBATCH --job-name=multi
#SBATCH --output=logs/rank1-maxcut-%j.out
#SBATCH --error=logs/rank1-maxcut-%j.err
#SBATCH --nodes=2
#SBATCH --tasks-per-node=1

#SBATCH --partition=commons
#SBATCH --cpus-per-task=50
#SBATCH --mem=0
#SBATCH --time=23:00:00

# Clean environment
module purge || true
unset LD_PRELOAD || true
export XALT_EXECUTABLE_TRACKING=0
export XALT_RUNNABLE=0

# Conda
cd /home/bs82/max-k-cut-parallel/
mkdir -p logs
source ~/miniforge3/etc/profile.d/conda.sh
conda activate ./rayenv

nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST")
nodes_array=($nodes)
head_node=${nodes_array[0]}
port=6379
ip_head=$head_node:$port
export ip_head
echo "IP Head: $ip_head"

srun --nodes="$SLURM_JOB_NUM_NODES" --ntasks="$SLURM_JOB_NUM_NODES" \
    ray symmetric-run \
    --address "$ip_head" \
    --min-nodes "$SLURM_JOB_NUM_NODES" \
    --num-cpus="${SLURM_CPUS_PER_TASK}" \
    -- \
    python -u src/test_multi_nodes.py
```

The error I get 
Failed to start Ray: Command '['ray', 'start', '--head', '--node-ip-address=192.168.154.8', '--port=6379', 'symmetric-run', '--num-cpus=50']' returned non-zero exit status 2.
stderr:
Usage: ray start [OPTIONS]
Try 'ray start --help' for help.

Error: Got unexpected extra argument (symmetric-run)

### Versions / Dependencies

ray=2.51.1 (default)
Python 3.11.14
os: Linux 5.14.0-503.40.1.el9_5.x86_64

### Reproduction script

sbatch multi_node_test.sh (use the bash script I provided above)

### Issue Severity

High: It blocks me from completing my task.

**Comment by barbara-su** [comment]
I followed tutorial on https://docs.ray.io/en/latest/cluster/vms/user-guides/community/slurm.html

**Comment by barbara-su** [comment]
Here is full error message I got
```
Failed to start Ray: Command '['ray', 'start', '--head', '--node-ip-address=192.168.154.8', '--port=6379', 'symmetric-run', '--num-cpus=50']' returned non-zero exit status 2.
stderr:
Usage: ray start [OPTIONS]
Try 'ray start --help' for help.

Error: Got unexpected extra argument (symmetric-run)

[2025-11-20 23:01:42,380 W 1555781 1555781] rpc_client.h:153: Failed to connect to GCS at address bg4u13g1:6379 within 5 seconds.
[2025-11-20 23:02:12,381 W 1555781 1555781] gcs_client.cc:182: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
Traceback (most recent call last):
  File "/home/bs82/max-k-cut-parallel/rayenv/bin/ray", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/scripts/scripts.py", line 2754, in main
    return cli()
           ^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/click/core.py", line 1485, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/click/core.py", line 1406, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/click/core.py", line 1873, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/click/core.py", line 1269, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/click/core.py", line 824, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/scripts/symmetric_run.py", line 229, in symmetric_run
    if not check_head_node_ready(address):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/scripts/symmetric_run.py", line 51, in check_head_node_ready
    gcs_client = GcsClient(address=address)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python/ray/_raylet.pyx", line 2893, in ray._raylet.GcsClient.__cinit__
  File "python/ray/includes/gcs_client.pxi", line 67, in ray._raylet.InnerGcsClient.standalone
  File "python/ray/includes/common.pxi", line 132, in ray._raylet.check_status_timeout_as_rpc_error
ray.exceptions.RpcError: Timed out while waiting for GCS to become available.
srun: error: bg5u16g1: task 1: Exited with exit code 1
```

**Comment by richardliaw** [comment]
hey! thanks a bunch for reporting this; I just fixed this on master -- we're releasing a new version of Ray today.

**Comment by barbara-su** [comment]
Hi thanks for responding to this issue! FYI here is an AI patch that works but there's still an autoscaler error I cannot remove). It turns out something is wrong with symmetric run (even just fixing the argument issue won't help)

new symmetric_run.py
```
"""Symmetric Run for Ray."""

import socket
import subprocess
import sys
import time
from typing import List

import click

import ray
from ray._private.ray_constants import env_integer
from ray._raylet import GcsClient
import os

import psutil

CLUSTER_WAIT_TIMEOUT = 180 # env_integer("RAY_SYMMETRIC_RUN_CLUSTER_WAIT_TIMEOUT", 30)


def check_ray_already_started() -> bool:
    import ray._private.services as services

    # Try auto-detecting the Ray instance.
    running_gcs_addresses = services.find_gcs_addresses()
    return len(running_gcs_addresses) > 0


def check_cluster_ready(nnodes, timeout=CLUSTER_WAIT_TIMEOUT):
    """Wait for all nodes to start.

    Raises an exception if the nodes don't start in time.
    """
    start_time = time.time()
    current_nodes = 1
    ray.init(ignore_reinit_error=True)

    while time.time() - start_time < timeout:
        time.sleep(5)
        # try:
        #     # Debug info
        #     subprocess.run(["ray", "status"], check=False)
        # except Exception:
        #     pass
        current_nodes = len(ray.nodes())
        if current_nodes == nnodes:
            return True
        else:
            click.echo(
                f"Waiting for nodes to start... {current_nodes}/{nnodes} nodes started"
            )
    return False


def check_head_node_ready(address: str, timeout=CLUSTER_WAIT_TIMEOUT):
    start_time = time.time()
    gcs_client = GcsClient(address=address)
    while time.time() - start_time < timeout:
        if gcs_client.check_alive([], timeout=1):
            click.echo("Ray cluster is ready!")
            return True
        time.sleep(5)
    return False


def curate_and_validate_ray_start_args(run_and_start_args: List[str]) -> List[str]:
    # Reparse the arguments to remove symmetric_run arguments.
    ctx = symmetric_run.make_context("_", run_and_start_args, resilient_parsing=True)
    cleaned_args = list(ctx.params["ray_args_and_entrypoint"])

    for arg in cleaned_args:
        if arg == "--head":
            raise click.ClickException("Cannot use --head option in symmetric_run.")
        if arg == "--node-ip-address":
            raise click.ClickException(
                "Cannot use --node-ip-address option in symmetric_run."
            )
        if arg == "--port":
            raise click.ClickException("Cannot use --port option in symmetric_run.")
        if arg == "--block":
            raise click.ClickException("Cannot use --block option in symmetric_run.")

    return cleaned_args


@click.command(
    name="symmetric_run",
    context_settings={"ignore_unknown_options": True, "allow_extra_args": True},
    help="""Command to start Ray across all nodes and execute an entrypoint command.

USAGE:

    ray symmetric-run --address ADDRESS
[--min-nodes NUM_NODES] [RAY_START_OPTIONS] -- [ENTRYPOINT_COMMAND]

DESCRIPTION:

    This command (1) starts a Ray cluster across all nodes,
(2) runs a command on the head node, and (3) stops the Ray cluster.

    The '--' separator is required to distinguish between Ray start arguments
and the entrypoint command. The --min-nodes option is optional and
can be used to wait for a specific number of nodes to start.

EXAMPLES:

    # Start Ray with default settings and run a Python script

    ray symmetric-run --address 127.0.0.1:6379 -- python my_script.py

    # Start Ray with specific head node and run a command

    ray symmetric-run --address 127.0.0.1:6379 --min-nodes 4 -- python train_model.py --epochs=100

    # Start Ray and run a multi-word command

    ray symmetric-run --address 127.0.0.1:6379 --min-nodes 4 --num-cpus=4 -- python -m my_module --config=prod

RAY START OPTIONS:

    Most ray start command options are supported. Arguments that are not
supported are: --head, --node-ip-address, --port, --block.

SEPARATOR REQUIREMENT:

    The '--' separator is mandatory and must appear between Ray start
    arguments and the entrypoint command. This ensures clear separation
    between the two sets of arguments.
""",
)
@click.option(
    "--address", required=True, type=str, help="The address of the Ray cluster."
)
@click.option(
    "--min-nodes",
    type=int,
    help="If provided, wait for this number of nodes to start.",
)
@click.argument("ray_args_and_entrypoint", nargs=-1, type=click.UNPROCESSED)
def symmetric_run(address, min_nodes, ray_args_and_entrypoint):
    all_args = sys.argv[1:]
    try:
        separator = all_args.index("--")
    except ValueError:
        raise click.ClickException(
            "No separator '--' found in arguments. Please use '--' to "
            "separate Ray start arguments and the entrypoint command."
        )

    run_and_start_args, entrypoint_on_head = (
        all_args[:separator],
        all_args[separator + 1 :],
    )

    ray_start_args = curate_and_validate_ray_start_args(run_and_start_args)

    min_nodes = 1 if min_nodes is None else min_nodes

    if not entrypoint_on_head:
        raise click.ClickException("No entrypoint command provided.")

    if check_ray_already_started():
        raise click.ClickException("Ray is already started on this node.")

    # 1. Parse address and check if we are on the head node.
    gcs_host_port = ray._common.network_utils.parse_address(address)
    if gcs_host_port is None:
        raise click.ClickException(
            f"Invalid address format: {address}, should be `host:port`"
        )
    gcs_host, gcs_port = gcs_host_port

    try:
        # AF_UNSPEC allows resolving both IPv4 and IPv6
        addrinfo = socket.getaddrinfo(
            gcs_host, gcs_port, socket.AF_UNSPEC, socket.SOCK_STREAM
        )
        resolved_gcs_host = addrinfo[0][4][0]
    except socket.gaierror:
        raise click.ClickException(f"Could not resolve hostname: {gcs_host}")

    my_ips = []
    for iface, addrs in psutil.net_if_addrs().items():
        for addr in addrs:
            # Look for AF_INET (IPv4) or AF_INET6 (IPv6)
            if addr.family in [
                socket.AddressFamily.AF_INET,
                socket.AddressFamily.AF_INET6,
            ]:
                my_ips.append(addr.address)

    if min_nodes > 1:
        # Ban localhost ips if we are not running on a single node
        # to avoid starting N head nodes
        my_ips = [ip for ip in my_ips if ip != "127.0.0.1" and ip != "::1"]

    is_head = resolved_gcs_host in my_ips
    
    click.echo(f"[DEBUG] hostname={socket.gethostname()}")
    click.echo(f"[DEBUG] resolved_gcs_host={resolved_gcs_host}")
    click.echo(f"[DEBUG] my_ips={my_ips}")
    click.echo(f"[DEBUG] is_head={is_head}")
    

    result = None
    # 2. Start Ray and run commands.
    try:
        if is_head:
            # On the head node, start Ray, run the command, then stop Ray.
            click.echo("On head node. Starting Ray cluster head...")

            # Build the ray start command with all parameters
            ray_start_cmd = [
                "ray",
                "start",
                "--head",
                f"--node-ip-address={resolved_gcs_host}",
                f"--port={gcs_port}",
                *ray_start_args,
            ]

            # Start Ray head. This runs in the background and hides output.
            subprocess.run(ray_start_cmd, check=True, capture_output=True)
            click.echo("Head node started.")
            click.echo("=======================")
            if min_nodes > 1 and not check_cluster_ready(min_nodes):
                raise click.ClickException(
                    "Timed out waiting for other nodes to start."
                )

            click.echo(
                f"Running command on head node: {entrypoint_on_head}",
            )
            click.echo("=======================")
            result = subprocess.run(entrypoint_on_head)
            click.echo("=======================")
        else:
            # On a worker node, start Ray and connect to the head.
            click.echo(f"[WORKER] Hostname: {socket.gethostname()}")
            click.echo(f"[WORKER] address argument: {address}")
            click.echo(f"[WORKER] ip_head env var: {os.getenv('ip_head', '<not_set>')}")
            click.echo(f"[WORKER] Local IPs: {my_ips}")
            click.echo(f"[WORKER] Sleeping 10 seconds to let head come up...")
            time.sleep(10)

            # Build the ray start command for worker nodes with all parameters
            ray_start_cmd = [
                "ray",
                "start",
                "--address",
                address,
                "--block",
                *ray_start_args,
            ]

            click.echo(f"[WORKER] Running worker ray start: {' '.join(ray_start_cmd)}")

            proc = subprocess.run(
                ray_start_cmd,
                check=False,
                capture_output=True,
            )
            click.echo(f"[WORKER] ray start return code: {proc.returncode}")
            if proc.stdout:
                click.echo(f"[WORKER] ray start stdout:\n{proc.stdout.decode()}")
            if proc.stderr:
                click.echo(f"[WORKER] ray start stderr:\n{proc.stderr.decode()}")

    except subprocess.CalledProcessError as e:
        click.echo(f"Failed to start Ray: {e}", err=True)
        if e.stdout:
            click.echo(f"stdout:\n{e.stdout.decode()}", err=True)
        if e.stderr:
            click.echo(f"stderr:\n{e.stderr.decode()}", err=True)
    except KeyboardInterrupt:
        # This can be triggered by ctrl-c on the user's side.
        click.echo("Interrupted by user.", err=True)
    finally:
        # Stop Ray cluster.
        if is_head:
            subprocess.run(
                ["ray", "stop"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )

        # Propagate the exit code of the user script.
        if result is not None and result.returncode != 0:
            click.echo(f"Command failed with return code {result.returncode}", err=True)
            sys.exit(result.returncode)


if __name__ == "__main__":
    symmetric_run()
```

New sbatch (which calls the rewritten symmetric_run)
```
#!/bin/bash
#SBATCH --job-name=multi-nodes-test
#SBATCH --output=logs/multi-nodes-test-%j.out
#SBATCH --error=logs/multi-nodes-test-%j.err
#SBATCH --nodes=2
#SBATCH --tasks-per-node=1

#SBATCH --partition=commons
#SBATCH --cpus-per-task=8
#SBATCH --mem=0
#SBATCH --time=23:00:00

# Clean environment
module purge || true
unset LD_PRELOAD || true
export XALT_EXECUTABLE_TRACKING=0
export XALT_RUNNABLE=0

# Conda
cd /home/bs82/max-k-cut-parallel/
mkdir -p logs
source ~/miniforge3/etc/profile.d/conda.sh
conda activate ./rayenv

nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST")
nodes_array=($nodes)
head_node=${nodes_array[0]}
port=6379

# Ask Slurm to run hostname -I on the head node and grab the first IP
head_ip=$(srun -N1 -n1 -w "$head_node" hostname -I | awk '{print $1}')

ip_head="${head_ip}:${port}"
export ip_head
echo "Ray head GCS address: $ip_head"

srun --nodes="$SLURM_JOB_NUM_NODES" --ntasks="$SLURM_JOB_NUM_NODES" \
    python -m read_only.symmetric_run \
    --address "$ip_head" \
    --min-nodes "$SLURM_JOB_NUM_NODES" \
    --num-cpus="${SLURM_CPUS_PER_TASK}" \
    -- \
    python -u src/test_multi_nodes.py
```

Then test_muti_nodes.py
```
import os
import socket
from collections import Counter

import ray
from ray.util.scheduling_strategies import NodeAffinitySchedulingStrategy


def main():
    print("Connecting with ray.init(address='auto')", flush=True)
    ray.init(address="auto")

    # List nodes in the cluster
    nodes = [n for n in ray.nodes() if n.get("Alive", False)]
    print("\nAlive nodes:")
    for n in nodes:
        print(f"  NodeID={n['NodeID']}  Hostname={n['NodeManagerAddress']}")
    print(flush=True)

    if len(nodes) != 2:
        raise RuntimeError(f"Expected exactly 2 nodes, but found {len(nodes)}")

    node0_id = nodes[0]["NodeID"]
    node1_id = nodes[1]["NodeID"]
    node0_host = nodes[0]["NodeManagerAddress"]
    node1_host = nodes[1]["NodeManagerAddress"]

    print(f"\nNode 0: {node0_id} (host {node0_host})")
    print(f"Node 1: {node1_id} (host {node1_host})\n", flush=True)

    @ray.remote
    def worker_info(i):
        ctx = ray.get_runtime_context()
        return {
            "task_id": i,
            "pid": os.getpid(),
            "hostname": socket.gethostname(),
            "node_id": ctx.get_node_id(),
        }

    num_tasks = 20
    print(f"Launching {num_tasks} tasks", flush=True)

    half = num_tasks // 2
    futures = []

    # First half pinned to node 0
    for i in range(half):
        futures.append(
            worker_info.options(
                scheduling_strategy=NodeAffinitySchedulingStrategy(
                    node_id=node0_id,
                    soft=False,
                )
            ).remote(i)
        )

    # Second half pinned to node 1
    for i in range(half, num_tasks):
        futures.append(
            worker_info.options(
                scheduling_strategy=NodeAffinitySchedulingStrategy(
                    node_id=node1_id,
                    soft=False,
                )
            ).remote(i)
        )

    results = ray.get(futures)

    # Print each task location
    for r in sorted(results, key=lambda x: x["task_id"]):
        print(
            f"task {r['task_id']:2d}  host={r['hostname']}  pid={r['pid']}  node_id={r['node_id']}"
        )

    # Count by hostname and node_id
    host_counts = Counter(r["hostname"] for r in results)
    node_counts = Counter(r["node_id"] for r in results)

    print("\nTask distribution by hostname:")
    for host, cnt in host_counts.items():
        print(f"  {host}: {cnt} tasks")

    print("\nTask distribution by node_id:")
    for nid, cnt in node_counts.items():
        print(f"  {nid}: {cnt} tasks")

    print("\nExpected split:")
    print(f"  Node 0 ({node0_host}) should have {half} tasks")
    print(f"  Node 1 ({node1_host}) should have {num_tasks - half} tasks")

    assert node_counts[node0_id] == half, "Node 0 did not get the expected number of tasks"
    assert node_counts[node1_id] == num_tasks - half, "Node 1 did not get the expected number of tasks"

    print("\nExact half half split confirmed.")


if __name__ == "__main__":
    main()
```

**Comment by richardliaw** [comment]
ok we just released; try this version? https://github.com/ray-project/ray/releases/tag/ray-2.52.0

**Comment by barbara-su** [comment]
The new version still does not work on my slurm machine. 
Here are the errors and output files:

logs/multi-nodes-test-new-14674.err
```
Failed to start Ray: Command '['ray', 'start', '--head', '--node-ip-address=192.168.154.5', '--port=6379', '--num-cpus', '3']' returned non-zero exit status 1.
stdout:
2025-11-22 22:14:28,749	INFO usage_lib.py:478 -- Usage stats collection is enabled. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.
2025-11-22 22:14:28,749	INFO scripts.py:919 -- Local node IP: 192.168.154.5

stderr:
Traceback (most recent call last):
  File "/home/bs82/max-k-cut-parallel/rayenv/bin/ray", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/scripts/scripts.py", line 2843, in main
    return cli()
           ^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/click/core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/autoscaler/_private/cli_logger.py", line 823, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/scripts/scripts.py", line 953, in start
    node = ray._private.node.Node(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/_private/node.py", line 340, in __init__
    self.start_head_processes()
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/_private/node.py", line 1367, in start_head_processes
    self._write_cluster_info_to_kv()
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/_private/node.py", line 1329, in _write_cluster_info_to_kv
    assert curr_val == self._session_name.encode("utf-8"), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Session name session_2025-11-22_22-14-28_749697_3775690 does not match persisted value b'session_2025-11-22_22-14-25_239595_3774221'. Perhaps there was an error connecting to Redis.

Traceback (most recent call last):
  File "/home/bs82/max-k-cut-parallel/rayenv/bin/ray", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/scripts/scripts.py", line 2843, in main
    return cli()
           ^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/click/core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/scripts/symmetric_run.py", line 233, in symmetric_run
    if not check_head_node_ready(address):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/scripts/symmetric_run.py", line 53, in check_head_node_ready
    if gcs_client.check_alive([], timeout=1):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python/ray/includes/gcs_client.pxi", line 289, in ray._raylet.InnerGcsClient.check_alive
  File "python/ray/includes/common.pxi", line 198, in ray._raylet.raise_or_return
  File "python/ray/includes/gcs_client.pxi", line 858, in ray._raylet.convert_multi_bool
  File "python/ray/includes/common.pxi", line 135, in ray._raylet.check_status_timeout_as_rpc_error
ray.exceptions.RpcError: Timed out while waiting for GCS to become available.
srun: error: bg4u9g1: task 1: Exited with exit code 1
```

logs/multi-nodes-test-new-14674.out
```
Ray head GCS address: 192.168.154.5:6379
On head node. Starting Ray cluster head...
On worker node. Connecting to Ray cluster at 192.168.154.5:6379...
2025-11-22 22:14:29,587	VINFO scripts.py:1299 -- Send termination request to `[1m/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/sockets/raylet --store_socket_name=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/sockets/plasma_store --object_manager_port=0 --min_worker_port=10002 --max_worker_port=19999 --node_manager_port=0 --node_id=fe3c75a003538650ddbc8c7244eeac446b2171b6b04f74a02a356c49 --node_ip_address=192.168.154.5 --maximum_startup_concurrency=4 --static_resource_list=node:192.168.154.5,1.0,node:__internal_head__,1.0,CPU,4,memory,357951334810,object_store_memory,153407714918 "--python_worker_command=/home/bs82/max-k-cut-parallel/rayenv/bin/python3.11 /home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/_private/workers/setup_worker.py /home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/_private/workers/default_worker.py --node-ip-address=192.168.154.5 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/sockets/plasma_store --raylet-name=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/sockets/raylet --redis-address=None --metrics-agent-port=44582 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --runtime-env-agent-port=58196 --gcs-address=192.168.154.5:6379 --session-name=session_2025-11-22_22-14-25_239595_3774221 --temp-dir=/tmp/ray --webui=127.0.0.1:8265 --cluster-id=c510910cf22db65edc9440b7076012ae61572d293e655a4c10c4655e RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" --java_worker_command= --cpp_worker_command= --native_library_path=/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221 --log_dir=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs --resource_dir=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/runtime_resources --metrics-agent-port=44582 --metrics_export_port=64983 --runtime_env_agent_port=58196 --object_store_memory=153407714918 --plasma_directory=/dev/shm --fallback_directory=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221 --ray-debugger-external=0 --gcs-address=192.168.154.5:6379 --session-name=session_2025-11-22_22-14-25_239595_3774221 --labels= --cluster-id=c510910cf22db65edc9440b7076012ae61572d293e655a4c10c4655e --stdout_filepath=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs/raylet.out --stderr_filepath=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs/raylet.err --head --num_prestart_python_workers=4 "--dashboard_agent_command=/home/bs82/max-k-cut-parallel/rayenv/bin/python3.11 -u /home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/dashboard/agent.py --node-ip-address=192.168.154.5 --metrics-export-port=64983 --grpc-port=44582 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/sockets/plasma_store --raylet-name=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221 --log-dir=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2025-11-22_22-14-25_239595_3774221 --gcs-address=192.168.154.5:6379 --cluster-id-hex=c510910cf22db65edc9440b7076012ae61572d293e655a4c10c4655e --stdout-filepath=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs/dashboard_agent.out --stderr-filepath=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs/dashboard_agent.err" "--runtime_env_agent_command=/home/bs82/max-k-cut-parallel/rayenv/bin/python3.11 -u /home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/_private/runtime_env/agent/main.py --node-ip-address=192.168.154.5 --runtime-env-agent-port=58196 --gcs-address=192.168.154.5:6379 --cluster-id-hex=c510910cf22db65edc9440b7076012ae61572d293e655a4c10c4655e --runtime-env-dir=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/runtime_resources --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --log-dir=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs --temp-dir=/tmp/ray --stdout-filepath=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs/runtime_env_agent.out --stderr-filepath=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs/runtime_env_agent.err" --node-name=192.168.154.5[22m[26m` [2m(via SIGTERM)[22m[26m
2025-11-22 22:14:29,679	INFO scripts.py:1329 -- 1/1 stopped.
2025-11-22 22:14:29,766	VINFO scripts.py:1299 -- Send termination request to `[1m/home/bs82/max-k-cut-parallel/rayenv/bin/python3.11 -u /home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/autoscaler/_private/monitor.py --logs-dir=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=192.168.154.5:6379 --stdout-filepath=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs/monitor.out --stderr-filepath=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs/monitor.err --monitor-ip=192.168.154.5[22m[26m` [2m(via SIGTERM)[22m[26m
2025-11-22 22:14:29,767	VINFO scripts.py:1299 -- Send termination request to `[1m/home/bs82/max-k-cut-parallel/rayenv/bin/python3.11 -u /home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/_private/log_monitor.py --session-dir=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221 --logs-dir=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs --gcs-address=192.168.154.5:6379 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --stdout-filepath=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs/log_monitor.out --stderr-filepath=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs/log_monitor.err[22m[26m` [2m(via SIGTERM)[22m[26m
2025-11-22 22:14:29,767	VINFO scripts.py:1299 -- Send termination request to `[1m/home/bs82/max-k-cut-parallel/rayenv/bin/python3.11 -m ray.util.client.server --address=192.168.154.5:6379 --host=192.168.154.5 --port=10001 --mode=proxy --runtime-env-agent-address=http://192.168.154.5:58196[22m[26m` [2m(via SIGTERM)[22m[26m
2025-11-22 22:14:29,771	VINFO scripts.py:1307 -- Attempted to stop `[1m/home/bs82/max-k-cut-parallel/rayenv/bin/python3.11 -u /home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/_private/log_monitor.py --session-dir=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221 --logs-dir=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs --gcs-address=192.168.154.5:6379 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --stdout-filepath=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs/log_monitor.out --stderr-filepath=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs/log_monitor.err[22m[26m`, but process was already dead.
2025-11-22 22:14:29,773	VINFO scripts.py:1299 -- Send termination request to `[1m/home/bs82/max-k-cut-parallel/rayenv/bin/python3.11 /home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/dashboard/dashboard.py --host=127.0.0.1 --port=8265 --port-retries=0 --temp-dir=/tmp/ray --log-dir=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs --session-dir=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=192.168.154.5:6379 --cluster-id-hex=c510910cf22db65edc9440b7076012ae61572d293e655a4c10c4655e --node-ip-address=192.168.154.5 --stdout-filepath=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs/dashboard.out --stderr-filepath=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs/dashboard.err[22m[26m` [2m(via SIGTERM)[22m[26m
2025-11-22 22:14:30,027	INFO scripts.py:1329 -- 1/4 stopped.
2025-11-22 22:14:30,279	INFO scripts.py:1329 -- 2/4 stopped.
2025-11-22 22:14:30,410	INFO scripts.py:1329 -- 3/4 stopped.
2025-11-22 22:14:30,410	INFO scripts.py:1329 -- 4/4 stopped.
2025-11-22 22:14:30,497	VINFO scripts.py:1299 -- Send termination request to `[1m/home/bs82/max-k-cut-parallel/rayenv/lib/python3.11/site-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs --config_list=eyJvYmplY3Rfc3BpbGxpbmdfY29uZmlnIjogIntcInR5cGVcIjogXCJmaWxlc3lzdGVtXCIsIFwicGFyYW1zXCI6IHtcImRpcmVjdG9yeV9wYXRoXCI6IFwiL3RtcC9yYXkvc2Vzc2lvbl8yMDI1LTExLTIyXzIyLTE0LTI1XzIzOTU5NV8zNzc0MjIxXCJ9fSIsICJpc19leHRlcm5hbF9zdG9yYWdlX3R5cGVfZnMiOiB0cnVlfQ== --gcs_server_port=6379 --metrics-agent-port=44582 --node-ip-address=192.168.154.5 --session-name=session_2025-11-22_22-14-25_239595_3774221 --ray-commit=9527a555280fb9837ce73dabf01559c20656a456 --stdout_filepath=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs/gcs_server.out --stderr_filepath=/tmp/ray/session_2025-11-22_22-14-25_239595_3774221/logs/gcs_server.err[22m[26m` [2m(via SIGTERM)[22m[26m
2025-11-22 22:14:30,629	INFO scripts.py:1329 -- 1/1 stopped.
2025-11-22 22:14:30,629	SUCC scripts.py:1374 -- [32mStopped all 6 Ray processes.[39m
2025-11-22 22:14:35,198	INFO scripts.py:1371 -- Did not find any active Ray processes.
```

My sbatch file:
```
#!/bin/bash
#SBATCH --job-name=multi-nodes-test
#SBATCH --output=logs/multi-nodes-test-new-%j.out
#SBATCH --error=logs/multi-nodes-test-new-%j.err
#SBATCH --nodes=2
#SBATCH --tasks-per-node=1

#SBATCH --partition=commons
#SBATCH --cpus-per-task=3
#SBATCH --mem=16GB
#SBATCH --time=23:00:00

# Clean environment
module purge || true
unset LD_PRELOAD || true
export XALT_EXECUTABLE_TRACKING=0
export XALT_RUNNABLE=0

# Conda
cd /home/bs82/max-k-cut-parallel/
mkdir -p logs
source ~/miniforge3/etc/profile.d/conda.sh
conda activate ./rayenv

nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST")
nodes_array=($nodes)
head_node=${nodes_array[0]}
port=6379

# Ask Slurm to run hostname -I on the head node and grab the first IP
head_ip=$(srun -N1 -n1 -w "$head_node" hostname -I | awk '{print $1}')

ip_head="${head_ip}:${port}"
export ip_heada
echo "Ray head GCS address: $ip_head"

srun --nodes="$SLURM_JOB_NUM_NODES" --ntasks="$SLURM_JOB_NUM_NODES" \
    ray symmetric-run \
        --address "$ip_head" \
        --min-nodes "$SLURM_JOB_NUM_NODES" \
        --num-cpus "${SLURM_CPUS_PER_TASK}" \
        -- \
        python -u src/test_multi_nodes.py
```

and my testing code:
```
import os
import socket
from collections import Counter

import ray
from ray.util.scheduling_strategies import NodeAffinitySchedulingStrategy


def main():
    print("Connecting with ray.init(address='auto')", flush=True)
    ray.init(address="auto")

    # List nodes in the cluster
    nodes = [n for n in ray.nodes() if n.get("Alive", False)]
    print("\nAlive nodes:")
    for n in nodes:
        print(f"  NodeID={n['NodeID']}  Hostname={n['NodeManagerAddress']}")
    print(flush=True)

    if len(nodes) != 2:
        raise RuntimeError(f"Expected exactly 2 nodes, but found {len(nodes)}")

    node0_id = nodes[0]["NodeID"]
    node1_id = nodes[1]["NodeID"]
    node0_host = nodes[0]["NodeManagerAddress"]
    node1_host = nodes[1]["NodeManagerAddress"]

    print(f"\nNode 0: {node0_id} (host {node0_host})")
    print(f"Node 1: {node1_id} (host {node1_host})\n", flush=True)

    @ray.remote
    def worker_info(i):
        ctx = ray.get_runtime_context()
        return {
            "task_id": i,
            "pid": os.getpid(),
            "hostname": socket.gethostname(),
            "node_id": ctx.get_node_id(),
        }

    num_tasks = 20
    print(f"Launching {num_tasks} tasks", flush=True)

    half = num_tasks // 2
    futures = []

    # First half pinned to node 0
    for i in range(half):
        futures.append(
            worker_info.options(
                scheduling_strategy=NodeAffinitySchedulingStrategy(
                    node_id=node0_id,
                    soft=False,
                )
            ).remote(i)
        )

    # Second half pinned to node 1
    for i in range(half, num_tasks):
        futures.append(
            worker_info.options(
                scheduling_strategy=NodeAffinitySchedulingStrategy(
                    node_id=node1_id,
                    soft=False,
                )
            ).remote(i)
        )

    results = ray.get(futures)

    # Print each task location
    for r in sorted(results, key=lambda x: x["task_id"]):
        print(
            f"task {r['task_id']:2d}  host={r['hostname']}  pid={r['pid']}  node_id={r['node_id']}"
        )

    # Count by hostname and node_id
    host_counts = Counter(r["hostname"] for r in results)
    node_counts = Counter(r["node_id"] for r in results)

    print("\nTask distribution by hostname:")
    for host, cnt in host_counts.items():
        print(f"  {host}: {cnt} tasks")

    print("\nTask distribution by node_id:")
    for nid, cnt in node_counts.items():
        print(f"  {nid}: {cnt} tasks")

    print("\nExpected split:")
    print(f"  Node 0 ({node0_host}) should have {half} tasks")
    print(f"  Node 1 ({node1_host}) should have {num_tasks - half} tasks")

    assert node_counts[node0_id] == half, "Node 0 did not get the expected number of tasks"
    assert node_counts[node1_id] == num_tasks - half, "Node 1 did not get the expected number of tasks"

    print("\nExact half half split confirmed.")


if __name__ == "__main__":
    main()

```

**Comment by barbara-su** [comment]
Ray version: 2.52.0

**Comment by barbara-su** [comment]
(But since my code is working with my modified symmetric_run, feel free to close the issue)

**Comment by jjyao** [comment]
@barbara-su could you try the unmodified symmetric_run and see if it  works?

**Comment by barbara-su** [comment]
No. Check the above error log.

**Comment by richardliaw** [comment]
This is the diff between what you have and what I have. Not exactly sure what is the root difference beyond having extra timeouts on cluster wait and waiting for head node to start. 

```diff
➜  ray git:(master) ✗ diff python/ray/scripts/symmetric_run.py _new_symmetric.py
13a14
> import os
17c18
< CLUSTER_WAIT_TIMEOUT = env_integer("RAY_SYMMETRIC_RUN_CLUSTER_WAIT_TIMEOUT", 30)
---
> CLUSTER_WAIT_TIMEOUT = 180 # env_integer("RAY_SYMMETRIC_RUN_CLUSTER_WAIT_TIMEOUT", 30)
38a40,44
>         # try:
>         #     # Debug info
>         #     subprocess.run(["ray", "status"], check=False)
>         # except Exception:
>         #     pass
136,139d141
< 
<     if all_args and all_args[0] == "symmetric-run":
<         all_args = all_args[1:]
< 
195a198,203
>     
>     click.echo(f"[DEBUG] hostname={socket.gethostname()}")
>     click.echo(f"[DEBUG] resolved_gcs_host={resolved_gcs_host}")
>     click.echo(f"[DEBUG] my_ips={my_ips}")
>     click.echo(f"[DEBUG] is_head={is_head}")
>     
231,234c239,244
<             click.echo(f"On worker node. Connecting to Ray cluster at {address}...")
< 
<             if not check_head_node_ready(address):
<                 raise click.ClickException("Timed out waiting for head node to start.")
---
>             click.echo(f"[WORKER] Hostname: {socket.gethostname()}")
>             click.echo(f"[WORKER] address argument: {address}")
>             click.echo(f"[WORKER] ip_head env var: {os.getenv('ip_head', '<not_set>')}")
>             click.echo(f"[WORKER] Local IPs: {my_ips}")
>             click.echo(f"[WORKER] Sleeping 10 seconds to let head come up...")
>             time.sleep(10)
246,247c256
<             # This command will block until the Ray cluster is stopped.
<             subprocess.run(ray_start_cmd, check=True)
---
>             click.echo(f"[WORKER] Running worker ray start: {' '.join(ray_start_cmd)}")
248a258,268
>             proc = subprocess.run(
>                 ray_start_cmd,
>                 check=False,
>                 capture_output=True,
>             )
>             click.echo(f"[WORKER] ray start return code: {proc.returncode}")
>             if proc.stdout:
>                 click.echo(f"[WORKER] ray start stdout:\n{proc.stdout.decode()}")
>             if proc.stderr:
>                 click.echo(f"[WORKER] ray start stderr:\n{proc.stderr.decode()}")
> 
260c280,285
<         subprocess.run(["ray", "stop"])
---
>         if is_head:
>             subprocess.run(
>                 ["ray", "stop"],
>                 stdout=subprocess.DEVNULL,
>                 stderr=subprocess.DEVNULL,
>             )
\ No newline at end of file
```

**Comment by richardliaw** [comment]
For now, I'll close this issue since theoretically this should not be an issue (worker dies when waiting for head node to start), and the original issue is already addressed on master.

That being said, the error messages you posted are odd:

* AssertionError: Session name session_2025-11-22_22-14-28_749697_3775690 does not match persisted value b'session_2025-11-22_22-14-25_239595_3774221'. Perhaps there was an error connecting to Redis.

and

* ray.exceptions.RpcError: Timed out while waiting for GCS to become available.

Will keep an eye on these and open a new issue if that arises.
