### ISSUE TITLE
[RLlib] Wasted compute on double evaluation

### ISSUE THREAD

**Issue by matthieu-zimmer** [ray-project/ray#59037]
### What happened + What you expected to happen

**Evaluation is running twice in BC.**

It's fairly easy to reproduce the bug you can just run examples/offline_rl/train_w_bc_finetune_w_ppo.py 

I've attached a slightly modified version that skip PPO finetuning and include a callback on_episode_end to better show the problem.

[eval_bug.py](https://github.com/user-attachments/files/23798307/eval_bug.py)

I've also added a print line 2003 of algorithm.py:

```
                for env_s, ag_s, met, iter in results:
                    print(f"HERE {iter=} {self.iteration=}")
                    if iter != self.iteration:
                        continue
```

And we have
```
       .evaluation(
            evaluation_interval=10,
            evaluation_num_env_runners=1,
            evaluation_duration_unit="episodes",  # I've added this 
            evaluation_duration=5,
            evaluation_parallel_to_training=False,
        )
```
We expect to run 5 episodes at every evaluation, but after the first evaluation it'll always collect 10 episodes. It's very annoying when evaluation is slow.

Logs:
```
Training ...
(SingleAgentEnvRunner pid=387470) Episode return 22.0 T:22 C:1 527dc286551a4336aff381a9d7b74606
(SingleAgentEnvRunner pid=387470) Episode return 85.0 T:85 C:1 be0c5e5b2e044b8da08bc9695f4f16eb
(SingleAgentEnvRunner pid=387470) Episode return 59.0 T:59 C:1 73176768988e409db32b05251415fea3
(SingleAgentEnvRunner pid=387470) Episode return 49.0 T:49 C:1 a08a6beb9f2d46aa89111263003b242f
(SingleAgentEnvRunner pid=387470) Episode return 50.0 T:50 C:1 9348baebe05542599d4e91193127fed7
(BC(env=CartPole-v1; env-runners=0; learners=0; multi-agent=False) pid=386832) HERE iter=9 self.iteration=9     # All good
Training ...
(SingleAgentEnvRunner pid=387470) Episode return 42.0 T:42 C:1 1621a6bdafd845bcb4281d5745de9a22                 # Wasted compute
(SingleAgentEnvRunner pid=387470) Episode return 43.0 T:43 C:1 751135e0982a4a5ba585a67b6d0842e2                 # Wasted compute
(SingleAgentEnvRunner pid=387470) Episode return 98.0 T:98 C:1 815c84a46bcb4994a4f515e3e9f23f7f                 # Wasted compute
(SingleAgentEnvRunner pid=387470) Episode return 32.0 T:32 C:1 fd740e56b7df4cffad073f4b575a310b                 # Wasted compute
(SingleAgentEnvRunner pid=387470) Episode return 25.0 T:25 C:1 6b1ac2ae7135444f94f692d9c1f4a9c5                 # Wasted compute
(BC(env=CartPole-v1; env-runners=0; learners=0; multi-agent=False) pid=386832) HERE iter=9 self.iteration=19    # Why 9? All previous episode are discarded
(SingleAgentEnvRunner pid=387470) Episode return 179.0 T:179 C:1 0dddf6f5421b47c19eb40bde81718250
(SingleAgentEnvRunner pid=387470) Episode return 77.0 T:77 C:1 4a7402b368084eda8eac52e5d9e9edea
(SingleAgentEnvRunner pid=387470) Episode return 177.0 T:177 C:1 cc4e495a2d8f4e5da63c85ace1f64511
(SingleAgentEnvRunner pid=387470) Episode return 69.0 T:69 C:1 b6758214e3024093a84f142b7c9f208c
(SingleAgentEnvRunner pid=387470) Episode return 117.0 T:117 C:1 f3a69a677bd14829a86cbb4be66290ed
(BC(env=CartPole-v1; env-runners=0; learners=0; multi-agent=False) pid=386832) HERE iter=19 self.iteration=19
```

The first evaluation doesn't have the bug, but all subsequent evaluation has it.

### Versions / Dependencies

rllib 2.52.0
Python 3.10.19
Ubuntu 22.04
export RAY_DEDUP_LOGS=0
inside slurm cluster

### Reproduction script

[eval_bug.py](https://github.com/user-attachments/files/23798307/eval_bug.py)

### Issue Severity

High: It blocks me from completing my task.

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the issue @matthieu-zimmer, we're looking into it and hope to have a solution soon

**Comment by petern48** [comment]
I decided to look into solving this issue and found that it has already been fixed by https://github.com/ray-project/ray/pull/60777

In the commit before it (936a78d8ef8740954ddf42796d683e9181c6dca7), I see 
```
[36m(BC(env=CartPole-v1; env-runners=0; learners=0; multi-agent=False) pid=45245)[0m HERE iter=9 self.iteration=9
[36m(SingleAgentEnvRunner pid=45257)[0m Episode return 48.0 T:48 C:1 23d4a538570d4196b751b3c697a7b05e
[36m(SingleAgentEnvRunner pid=45257)[0m Episode return 51.0 T:51 C:1 1cec6234a3174050b94e7ac1dfeb8988
[36m(SingleAgentEnvRunner pid=45257)[0m Episode return 61.0 T:61 C:1 dbce83f3bfe94f978203f4df15d1eea1
[36m(SingleAgentEnvRunner pid=45257)[0m Episode return 85.0 T:85 C:1 70e3aea2cb554fe084af187ab644918d
[36m(SingleAgentEnvRunner pid=45257)[0m Episode return 83.0 T:83 C:1 589a964f86f24f38a8779e70e250d79b
[36m(SingleAgentEnvRunner pid=45257)[0m Episode return 50.0 T:50 C:1 21286fc93425458ba417e2f965ddc2a5
[36m(SingleAgentEnvRunner pid=45257)[0m Episode return 42.0 T:42 C:1 141dccad4c8d4281978bdb6aa0c4287c
[36m(BC(env=CartPole-v1; env-runners=0; learners=0; multi-agent=False) pid=45245)[0m HERE iter=9 self.iteration=19   -- HERE's the indicatino of the bug)
...
```
In the commit for the PR (4ab83f0d598cd44e43c9eb2225ee49efa227d231), it's properly fixed. Specifically we get `iter=19 self.iteration=19` for the last line instead of `iter=9 self.iteration=19`:
```
[36m(BC(env=CartPole-v1; env-runners=0; learners=0; multi-agent=False) pid=43933)[0m HERE iter=9 self.iteration=9
[36m(SingleAgentEnvRunner pid=43941)[0m Episode return 62.0 T:62 C:1 ac529ef75082409197c92e0b96a0f653
[36m(SingleAgentEnvRunner pid=43941)[0m Episode return 32.0 T:32 C:1 182dbd97a33640449ad8afd7d016a857
[36m(SingleAgentEnvRunner pid=43941)[0m Episode return 87.0 T:87 C:1 6aad0a644572481a803fa7c54a140c9e
[36m(SingleAgentEnvRunner pid=43941)[0m Episode return 96.0 T:96 C:1 53ded2bc715b450dad2329640748fd9a
[36m(SingleAgentEnvRunner pid=43941)[0m Episode return 114.0 T:114 C:1 b90c21204be14c5dbe0132044e85e2db
[36m(BC(env=CartPole-v1; env-runners=0; learners=0; multi-agent=False) pid=43933)[0m HERE iter=19 self.iteration=19  -- Indication that it's fixed.
...
```

Can we close this?

**Comment by lonexreb** [comment]
I spent some time tracing this on current `master` and I'm not sure the mechanism still exists there — wanted to share what I found before proposing a fix, since it looks like the relevant code has changed since 2.52.

**What the logs show:** at iteration 19 the first result batch is tagged `iter=9` (the *previous* evaluation's iteration), gets dropped by the `if iter != self.iteration: continue` guard, but the 5 episodes were already sampled (the wasted compute), and then a fresh round of 5 is collected. So the extra work is a whole leftover round from the prior `evaluate()` call surfacing at the start of the next one.

**On master:** your config (`evaluation_num_env_runners=1`, `evaluation_parallel_to_training=False`, fixed `evaluation_duration=5`) dispatches to `Algorithm._evaluate_with_fixed_duration()`, and that path now samples via the **synchronous** `EnvRunnerGroup.foreach_env_runner(...)` (which goes through `FaultTolerantActorManager.foreach_actor` with a timeout), not the async `foreach_env_runner_async` + `fetch_ready_async_reqs` fetch. A synchronous `foreach_actor` only returns results for the calls it just issued, so a request left over from a previous `evaluate()` shouldn't be able to come back tagged with the old `iter`. In that path the `iter != self.iteration` guard effectively never fires (it only really matters for the `parallel_to_training` / auto-duration path where training advances the iteration concurrently).

Tracing a single-worker `episodes`-unit run through the loop, round 0 requests 5 episodes, `num_units_done` reaches 5 via `met[NUM_EPISODES].peek()`, and the `while` exits after one round — I couldn't find where a second round of 5 would come from.

**So my question before writing a patch:** does this still reproduce on latest `master`? If you're still on 2.52 (or the async fetch path via a different config), that would explain it and it may already be fixed. If it *does* still repro on master with `eval_bug.py`, could you share what `Algorithm.evaluate` dispatches to in your run (i.e. is it `_evaluate_with_fixed_duration` or `_evaluate_with_auto_duration`)? That tells me exactly which loop to fix, and I'll put up a PR with a regression test. I'd rather target the real path than guess.

**Comment by lonexreb** [comment]
Update: I built current `master` from source and ran this end-to-end — **it no longer reproduces**.

I counted episodes actually sampled by the eval EnvRunner (via an `on_episode_end` callback that fires on the eval runner) across multiple evaluations, using your exact eval config (`evaluation_duration_unit="episodes"`, `evaluation_duration=5`, `evaluation_num_env_runners=1`, `evaluation_parallel_to_training=False`):

- **PPO / CartPole**, 5 evaluations → **25 total episodes** sampled (exactly 5 per eval).
- **BC / CartPole** (the offline example from `train_w_bc_finetune_w_ppo.py`, model and data unchanged), 4 evaluations → **20 total** (exactly 5 per eval).

No second round of collection after the first eval; the eval runner samples exactly `evaluation_duration` episodes every time.

The non-parallel path (`_evaluate_with_fixed_duration`) now samples synchronously via `EnvRunnerGroup.foreach_env_runner(...)` rather than the async `foreach_env_runner_async_fetch_ready` used in 2.52, so a request left in flight by a previous `evaluate()` can no longer resurface tagged with the old iteration (the "wasted compute" you saw). Looks resolved on master — I think this can be closed, but happy to dig further if you can still repro on latest.
