### ISSUE TITLE
[rllib] ModuleNotFoundError: No module named 'tree'

### ISSUE THREAD

**Issue by forhonourlx** [ray-project/ray#7645]
*Ray version and other system information (Python version, TensorFlow version, OS):*
Python3.6 
pip install -U ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl
On 2020-03-18
### Reproduction (REQUIRED)
$ rllib train -f atari-ddppo.yaml

Traceback (most recent call last):
  File "/home/simon/anaconda3/bin/rllib", line 5, in <module>
    from ray.rllib.scripts import cli
  File "/home/simon/anaconda3/lib/python3.6/site-packages/ray/rllib/__init__.py", line 9, in <module>
    from ray.rllib.evaluation.policy_graph import PolicyGraph
  File "/home/simon/anaconda3/lib/python3.6/site-packages/ray/rllib/evaluation/__init__.py", line 2, in <module>
    from ray.rllib.evaluation.rollout_worker import RolloutWorker
  File "/home/simon/anaconda3/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 19, in <module>
    from ray.rllib.evaluation.sampler import AsyncSampler, SyncSampler
  File "/home/simon/anaconda3/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 11, in <module>
    from ray.rllib.evaluation.sample_batch_builder import \
  File "/home/simon/anaconda3/lib/python3.6/site-packages/ray/rllib/evaluation/sample_batch_builder.py", line 6, in <module>
    from ray.rllib.policy.sample_batch import SampleBatch, MultiAgentBatch
  File "/home/simon/anaconda3/lib/python3.6/site-packages/ray/rllib/policy/__init__.py", line 2, in <module>
    from ray.rllib.policy.torch_policy import TorchPolicy
  File "/home/simon/anaconda3/lib/python3.6/site-packages/ray/rllib/policy/torch_policy.py", line 10, in <module>
    from ray.rllib.utils.torch_ops import convert_to_non_torch_type
  File "/home/simon/anaconda3/lib/python3.6/site-packages/ray/rllib/utils/torch_ops.py", line 1, in <module>
    import tree
ModuleNotFoundError: No module named 'tree'

**Comment by CesMak** [comment]
I have the same error..... 
Any solution found so far

**Comment by sven1977** [comment]
For now, could you simply try: `pip install dm_tree` to fix this?
Let me know, whether this works.

**Comment by forhonourlx** [comment]
Thanks, it does work.

**Comment by sven1977** [comment]
Ok, great! Sorry, we added this requirement in one of the recent PRs.

From setup.py: But yeah, if you just update your ray repo without wheel upgrade, this would have failed.

```
extras["rllib"] = extras["tune"] + [
    "atari_py",
    "dm_tree",
    "gym[atari]",
    "lz4",
    "opencv-python-headless",
    "pyyaml",
    "scipy",
]
```

**Comment by dciborow** [comment]
Any way this error message can be improved.... Google saved me here by this being a top result for  ModuleNotFoundError: No module named 'tree'

I'd assume anyone who actually needs tree, as the rest of us probably did simply does pip install tree. But at least google saves us....

**Comment by ibrottier** [comment]
> For now, could you simply try: `pip install dm-tree` to fix this?
> Let me know, whether this works.

Im having this problem when importing "from ray.rllib.env import MultiAgentEnv" and the pip install didn't seem to work

any idea?

**Comment by andykat** [comment]
I am also still having issue after trying pip install dm-tree

**Comment by caesar025** [comment]
I am also still having this issue, despite the pip install. Any ideas on how to fix?

**Comment by XuandongZhao** [comment]
Still have the same error after installing dm-tree. And my python version is python3.8.

**Comment by zzcNEU** [comment]
> Still have the same error after installing dm-tree. And my python version is python3.8.

have you solve it? I have the same error on win10 system.

**Comment by dciborow** [comment]
this solution was previously working... looks to have recently broken again.

**Comment by enikon** [comment]
dciborow:
Worked for me on Win10

**Comment by businesscazz** [comment]
Hey Team,

I tried to follow the preceeding steps, with no success. Still getting ModuleNotFoundError: No module named tree. I'm trying to run one of the multi-agent_rl - I'm very new to all of this, so any help would be greatly appreciated. 
Thanks

**Comment by MedhaviMonish** [comment]
businesscazz,  can you show what the error is when you use

pip uninstall tree
pip uninstall dm-tree

pip install --upgrade ray
pip install dm-tree

because  i also just started rllib yesterday and this problem was fixed with above code

**Comment by benhamlen** [comment]
I believe the issue is that Tree should be capitalized??? Manually editing the files where the import error for Tree occurs clears up the error but there are SO MANY files that use it in ray that it doesn't seem feasible to edit them all. Did python recently change to case-sensitive import statements, or did the package name for tree recently change from "tree" to "Tree"?

**Comment by kiranikram** [comment]
I have tried all of the above , but I am still getting that error.

**Comment by dcolley** [comment]
@kiranikram Try running the commands above **_one-by-one_**. Some commands require you to answer [y/n]...

**Comment by voljumet** [comment]
> pip uninstall tree pip uninstall dm-tree
> 
> pip install --upgrade ray pip install dm-tree
> 
> Working now

This worked for me in my fresh environment on my M1 MacOS 12.3.1

**Comment by JingDang99** [comment]
Hello developers, I also encountered the "no module named dm_tree" warning while using the ray library, and after reading the forum discussions, tried

pip uninstall tree
pip uninstall dm-tree

pip install --upgrade ray
pip install --upgrade ray

but it still didn't work, I went back to my virtual environment's site-package and realized that I only had the
dm_tree-0.1.8.dist-info file, not dm_tree-0.1.8 file.

So I pip uninstalled the tree again
pip uninstall dm-tree and found the same situation.

I think this is very strange and I don't really understand what's going on here, I'm still trying to fix it, if you could give me some advice it would be greatly appreciated!

**Comment by JingDang99** [comment]
Hello developers, I also encountered the "no module named dm_tree" warning while using the ray library, and after reading the forum discussions, tried

pip uninstall tree
pip uninstall dm-tree

pip install --upgrade ray

pip install tree
pip install dm-tree

but it still didn't work, I went back to my virtual environment's site-package and realized that I only had the
dm_tree-0.1.8.dist-info file, not dm_tree-0.1.8 file.

So I pip 

uninstalled the tree 
pip install dm-tree again and found the same situation.

I think this is very strange and I don't really understand what's going on here, I'm still trying to fix it, if you could give me some advice it would be greatly appreciated!

**Comment by JingDang99** [comment]
Hello developers, I also encountered the "no module named dm_tree" warning while using the ray library, and after reading the forum discussions, tried

pip uninstall tree
pip uninstall dm-tree

pip install --upgrade ray

pip install tree
pip install dm-tree

but it still didn't work, I went back to my virtual environment's site-package and realized that I only had the
dm_tree-0.1.8.dist-info file, not dm_tree-0.1.8 file.

So I 

pipuninstalled the tree
pip install dm-tree 

again 
and found the same situation.

I think this is very strange and I don't really understand what's going on here, I'm still trying to fix it, if you could give me some advice it would be greatly appreciated!

**Comment by PaulEcoffet** [comment]
Hello, you should not re-install the tree package but only the dm-tree one.

Do 

```sh
pip uninstall tree
pip uninstall dm-tree

pip install --upgrade ray

#### Here we do not install tree but only dm-tree
pip install dm-tree
```

**Comment by JingDang99** [comment]
> Hello, you should not re-install the tree package but only the dm-tree one.
> 
> Do
> 
> ```shell
> pip uninstall tree
> pip uninstall dm-tree
> 
> pip install --upgrade ray
> 
> #### Here we do not install tree but only dm-tree
> pip install dm-tree
> ```

Thank you very much, now I got it. 

Since dm_tree generates a tree folder and a dm_tree folder describing it, 

I have taken to 

import dm_tree as tree 

which is incorrect since the main files generated in the installation are in the tree folder rather than dm_tree. 

Thank you very much for your reply, as I have just started writing code and my knowledge about it was too weak to understand what you said quickly, now it all makes sense, thank you very much.

**Comment by Emilyhelin** [comment]
How long does it take for you to run the 'pip uninstall tree' command? It has been running for over an hour but is still incomplete.

**Comment by Emilyhelin** [comment]
> pip install dm-tree

I solved it by running it in cmd

**Comment by VeigarJia** [comment]
thank you sooooo much!!!
