### ISSUE TITLE
[tune] Can't suggest initial parameters for BayesOptSearch

### ISSUE THREAD

**Issue by redzhepdx** [ray-project/ray#8165]
[tune]

### What is your question?
I am trying to add Ray[tune] into my own model training pipeline. I have some good parameters already found by hand and I know that hyper-parameter optimization can't produce better configuration all the time. I would like to add my initial parameters as additional suggestions that optimizer can compare against its own discoveries. I couldn't find this functionality in BayesOptSearch. I would like to know if there is a way to do it for BayesOptSearch.

*Python 3.7 Ray 0.8.2 Ubuntu 19.10*

**Comment by richardliaw** [comment]
We should document this, but one way you can do this:

```
bayes_opt = BayesOptSearch(...)
optimizer = bayes_opt.optimizer
for param_dict, score in your_initial_parameters:
optimizer.register(
	params=param_dict,
    target=score)
```

**Comment by redzhepdx** [comment]
Thanks a lot but it isn't exactly what I am looking for but it gave me a hint. I am looking for a way to add those initial_parameters into experiment queue like probe function of [bayesian-optimization](https://github.com/fmfn/BayesianOptimization) but It isn't possible in the Ray because in the constructor of BayesOptSearch you instantiate BayesianOptimization object with `None` function.
`self.optimizer = byo.BayesianOptimization(
            f=None, pbounds=space, verbose=verbose, random_state=random_state)`

**Comment by richardliaw** [comment]
Got it; what was the final workaround you came up with?

**Comment by redzhepdx** [comment]
It is very similar to your approach but it calculates scores for every initial parameter before `tune.run(...)`. I think a similar functionality can be part of the library.
Note : `tune.track()` lines need to be in try-catch block otherwise, it throws an AttributeError!
```
def function_to_optimize(args):
    ...
    try:
        tune.track.log(accuracy=score)
    except AttributeError:
    ....
    return score # Function has to return the score in this case

# Bayes Optimizer
bayes_opt = BayesOptSearch(...)
optimizer = bayes_opt.optimizer

# Run function for every initial parameter and register
for param_dict in your_initial_parameters:
     score = function_to_optimize(param_dict)
     optimizer.register( params=param_dict,  target=score)
....
```

**Comment by redzhepdx** [comment]
Unfortunately, the solution that I proposed doesn't solve the issue because Ray has its own internal experiment collection container[`Trials` array].  When you register (param, score) pairs via the optimizer object of BayesianOpt, it doesn't save those previously registered parameters into its own container or it doesn't consider them in `ExperimentAnalysis` object's  `get_best_trial()` function

**Comment by richardliaw** [comment]
Got it. @redzhepdx I just opened a PR to attempt to make your user experience better: https://github.com/ray-project/ray/pull/8216

Basically:
```python
BayesOptSearch(..., points_to_evaluate=your_initial_parameters)

**Comment by richardliaw** [comment]
BTW, any reason to use BayesOpt instead of say Scikit-Optimize (SkoptSearch)?

**Comment by redzhepdx** [comment]
I am using HyperOpt(Tree-structured Parzen Estimator) now but on the low capacity devices, the execution of BayesOpt(Bayesian Optimization) is faster than other algorithms. I would like to have the functionality of switching between different hyper-parameter optimization algorithms according to the hardware specs of any device.

**Comment by richardliaw** [comment]
Thanks got it; I'll get this merged in a day or two.

**Comment by richardliaw** [comment]
This should be fixed now.

**Comment by rogertrullo** [comment]
> This should be fixed now.

I am using ray 1.0.0 (latest pip) and I still have the same issue. 
Wouldn't it be better to add some `**kwargs` to pass to the optimizer?

**Comment by richardliaw** [comment]
Yeah good point. I guess the original issue was never solved properly - 

```python
BayesOpt(x0=[list of points], y0=[list of optional responses]) 
```
would work for you  right?

**Comment by rogertrullo** [comment]
> Yeah good point. I guess the original issue was never solved properly -
> 
> ```python
> BayesOpt(x0=[list of points], y0=[list of optional responses]) 
> ```
> 
> would work for you right?
yeah that can work, but maybe it is better to keep the `points_to_evaluate` so that it matches the hyperopt initial values?

**Comment by rogertrullo** [comment]
> Yeah good point. I guess the original issue was never solved properly -
> 
> ```python
> BayesOpt(x0=[list of points], y0=[list of optional responses]) 
> ```
> 
> would work for you right?

yeah that can work, but maybe it is better to keep the points_to_evaluate so that it matches the hyperopt initial values?

**Comment by krfricke** [comment]
We added support for `points_to_evaluate` for all search algorithms in https://github.com/ray-project/ray/pull/12790 and https://github.com/ray-project/ray/pull/12916.

I'm a bit lost if everything's solved by this. We could also support supplying existing results for these `points_to_evaluate`, is this a desired feature or are most use cases covered by the existing PRs?

**Comment by krfricke** [comment]
I'll close this issue for now, please re-open or open a new issue if your use case is not covered by the PRs.
