### ISSUE TITLE
Using Ray on two machines (with docker) .

### ISSUE THREAD

**Issue by yanyuechuixue** [ray-project/ray#8646]
### What is your question?

I have two machine(A,B) and both installed docker. 
Here :
> Container 'a' on machine A, ports expose: 0.0.0.0:58889-58893->58889-58893/tcp , container ip 172.17.0.4;
> Container 'b' on machine B, ports expose: 0.0.0.0:58889-58893->58889-58893/tcp , container ip 172.17.0.3;

In Container 'a', following [this](https://docs.ray.io/en/latest/using-ray-on-a-cluster.html), I run
```bash
ray start --head --redis-port=58889 --redis-shard-ports=58890 --node-manager-port=58891 --object-manager-port=58892 --num-cpus=8 --include-webui=1 --webui-host=0.0.0.0
```
In Container 'b', I run
```bash
ray start --address='192.168.1.158:58889' --node-manager-port=58891 --object-manager-port=58892 --num-cpus=8
```
where `192.168.1.158` is the ip address of machine A.

Then I open the webui, it shows:
``` log
af940184d3ea (172.17.0.3) | 0 workers / 80 cores
bf049f0b8e6f (172.17.0.4) | 8 workers / 80 cores
```
which means no works on Container 'b' on machine B.

However, what I expected is 8 workers on Container 'b'.

I have also tryed  adding "--node-ip-address='192.168.1.68'", where '192.168.1.68'' is the ip address of machine B. but it still 0 workers, and it gives some error like:
```log
F0528 04:41:19.140461   831 redis_context.cc:239] Could not establish connection to redis 172.17.0.4:58890 (context.err = 1)
--
  | *** Check failure stack trace: ***
  | @     0x55e552dbd11d  google::LogMessage::Fail()
  | @     0x55e552dbe58c  google::LogMessage::SendToLog()
  | @     0x55e552dbcdf9  google::LogMessage::Flush()
  | @     0x55e552dbd011  google::LogMessage::~LogMessage()
  | @     0x55e552a818f9  ray::RayLog::~RayLog()
  | @     0x55e55297688d  ray::gcs::ConnectWithRetries<>()
  | @     0x55e552976c19  ray::gcs::RedisContext::Connect()
  | @     0x55e552927982  ray::gcs::RedisGcsClient::Connect()
  | @     0x55e5528083b5  main
  | @     0x7f4085cc4b97  __libc_start_main
  | @     0x55e552818a31  (unknown)
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python versions are 3.7.6
Ray versions are 0.8.4
OS are :
Machine A: Ubuntu 18.04
Machine B: Ubuntu 16.04

Thank you very much!

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/issues/8033

@ijrsvt This might be the similar issue. I saw this sort of questions a lot.

**Comment by songpengwei** [comment]
how about use public ip when start the worker node?

**Comment by yanyuechuixue** [comment]
> how about use public ip when start the worker node?

If use `--node-ip-address=192.168.1.158` when start the head node, the webui can not be connected and I can not connect to the ray server in python:
```
WARNING services.py:211 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2
```

and if use `--node-ip-address=192.168.1.68` when add the worker node, it would still be 0 workers, and gives some error like:
```
F0528 04:41:19.140461   831 redis_context.cc:239] Could not establish connection to redis 172.17.0.4:58890 (context.err = 1)
--
  | *** Check failure stack trace: ***
  | @     0x55e552dbd11d  google::LogMessage::Fail()
  | @     0x55e552dbe58c  google::LogMessage::SendToLog()
  | @     0x55e552dbcdf9  google::LogMessage::Flush()
  | @     0x55e552dbd011  google::LogMessage::~LogMessage()
  | @     0x55e552a818f9  ray::RayLog::~RayLog()
  | @     0x55e55297688d  ray::gcs::ConnectWithRetries<>()
  | @     0x55e552976c19  ray::gcs::RedisContext::Connect()
  | @     0x55e552927982  ray::gcs::RedisGcsClient::Connect()
  | @     0x55e5528083b5  main
  | @     0x7f4085cc4b97  __libc_start_main
  | @     0x55e552818a31  (unknown)
```

**Comment by ijrsvt** [comment]
In the initial config (where it was 0 workers on Container B), what happens if you run `ray.nodes()` after `ray.init(address='auto')`.

**Comment by ijrsvt** [comment]
@yanyuechuixue Any updates?

**Comment by yanyuechuixue** [comment]
> @yanyuechuixue Any updates?

I have not try your suggestion yet. Because I have run the jobs on the two machine by hand.

I will try your method as soon as the jobs are done.

Thank you very much!

**Comment by muhammadsyahyas** [comment]
Have anybody managed to solve this issue in Linux machine?

**Comment by rkooo567** [comment]
This must have fixed in the nightly version. Can you try?

**Comment by muhammadsyahyas** [comment]
I've tried the nightly version [1.1.0.dev0](https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.1.0.dev0-cp37-cp37m-manylinux1_x86_64.whl) (per about 2 hours ago). It is still failed.

![alt text](https://i.ibb.co/7jkd8GT/Screenshot-from-2020-10-11-13-32-04.png "screenshot")

I used `--network=host` to make sure the problem not coming from Docker publish port mapping. I've tested using cloud VM, with [required ports opened](https://docs.ray.io/en/master/configure.html#ray-ports). Both VMs were in different network, with head node published to public IP. It seems there are undocumented port assigned with random number used by the raylet to connect to the redis.

From inside docker container head node, using `python`:
```
>>> import ray
>>> ray.__version__
'1.1.0.dev0'
>>> ray.init(address="auto", _redis_password="xyz")
2020-10-11 06:31:01,754	INFO worker.py:651 -- Connecting to existing Ray cluster at address: 192.168.0.65:6379
{'node_ip_address': '192.168.0.65', 'raylet_ip_address': '192.168.0.65', 'redis_address': '192.168.0.65:6379', 'object_store_address': '/tmp/ray/session_2020-10-11_06-28-41_888253_6/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2020-10-11_06-28-41_888253_6/sockets/raylet', 'webui_url': '192.168.0.65:8265', 'session_dir': '/tmp/ray/session_2020-10-11_06-28-41_888253_6', 'metrics_export_port': 50719, 'node_id': 'afcf33f84bf3e3ce98d8439669b9fa26c7cc18ee'}
>>> ray.nodes()
[{'NodeID': 'afcf33f84bf3e3ce98d8439669b9fa26c7cc18ee', 'Alive': True, 'NodeManagerAddress': '192.168.0.65', 'NodeManagerHostname': 'xxx-head', 'NodeManagerPort': 6381, 'ObjectManagerPort': 6382, 'ObjectStoreSocketName': '/tmp/ray/session_2020-10-11_06-28-41_888253_6/sockets/plasma_store', 'RayletSocketName': '/tmp/ray/session_2020-10-11_06-28-41_888253_6/sockets/raylet', 'MetricsExportPort': 54277, 'alive': True, 'Resources': {'object_store_memory': 3.0, 'node:192.168.0.65': 1.0, 'CPU': 1.0, 'memory': 29.0}}]
>>> (pid=raylet, ip=192.168.0.241) F1011 06:31:48.599061    10    10 redis_context.cc:298] Could not establish connection to redis 192.168.0.65:48222 (context.err = 1)
(pid=raylet, ip=192.168.0.241) *** Check failure stack trace: ***
(pid=raylet, ip=192.168.0.241)     @     0x55b7c624a42d  google::LogMessage::Fail()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c624b89c  google::LogMessage::SendToLog()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c624a109  google::LogMessage::Flush()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c624a321  google::LogMessage::~LogMessage()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c61fee99  ray::RayLog::~RayLog()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c600e3ba  ray::gcs::ConnectWithRetries<>()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c600f839  ray::gcs::RedisContext::Connect()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c607380f  ray::gcs::RedisClient::Connect()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c6074801  ray::gcs::RedisClient::Connect()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c60150da  ray::gcs::RedisGcsClient::Connect()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c5fae9d6  ray::gcs::ServiceBasedGcsClient::Connect()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c5e5de83  main
(pid=raylet, ip=192.168.0.241)     @     0x7fbb3348709b  __libc_start_main
(pid=raylet, ip=192.168.0.241)     @     0x55b7c5e754b1  (unknown)
(pid=raylet, ip=192.168.0.241) F1011 06:31:48.599061    10    10 redis_context.cc:298] Could not establish connection to redis 192.168.0.65:48222 (context.err = 1)
(pid=raylet, ip=192.168.0.241) *** Check failure stack trace: ***
(pid=raylet, ip=192.168.0.241)     @     0x55b7c624a42d  google::LogMessage::Fail()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c624b89c  google::LogMessage::SendToLog()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c624a109  google::LogMessage::Flush()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c624a321  google::LogMessage::~LogMessage()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c61fee99  ray::RayLog::~RayLog()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c600e3ba  ray::gcs::ConnectWithRetries<>()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c600f839  ray::gcs::RedisContext::Connect()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c607380f  ray::gcs::RedisClient::Connect()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c6074801  ray::gcs::RedisClient::Connect()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c60150da  ray::gcs::RedisGcsClient::Connect()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c5fae9d6  ray::gcs::ServiceBasedGcsClient::Connect()
(pid=raylet, ip=192.168.0.241)     @     0x55b7c5e5de83  main
(pid=raylet, ip=192.168.0.241)     @     0x7fbb3348709b  __libc_start_main
(pid=raylet, ip=192.168.0.241)     @     0x55b7c5e754b1  (unknown)

KeyboardInterrupt
```
See, it tried to connect to port `48222`. However, I configured all required ports mentioned in the docs to static values, and none of them leaved for random assignment nor to port `48222`. I think this behavior still the same with release version 1.0.0; I saw random assigned port too, with same error message.

**Comment by ijrsvt** [comment]
What is the output from `ray start --head`? @muhammadsyahyas

**Comment by manishagarwal23** [comment]
Following

**Comment by manishagarwal23** [comment]
I am also facing these issues. For me I see PS command on worker not showing any raylet process where as on head node I see raylets . Some answer would really help. Do you see raylet process running in worker docker ?

**Comment by muhammadsyahyas** [comment]
@ijrsvt I forgot to take the snapshot, as far as I remember there was no error from the `ray start --head`.

**Comment by DonYum** [comment]
I have encountered this problem too. Using host network is a solution, however, not elegant.
Is there any other solution?
