### ISSUE TITLE
ray::IDLE processes persist if I disconnect and kill master process from IDE

### ISSUE THREAD

**Issue by mcrowson** [ray-project/ray#9528]
### What is the problem?
When developing locally I sometimes start up a tune.run, and part way through i might kill the process from my IDE (using VSCodium). This disconnects me and the IDE indicates that no debug process is running, however I have extra ray:IDLE processes that still are sucking up ram. 

### Reproduction (REQUIRED)
```python
from ray import rllib, tune
from ray.rllib.examples.env.random_env import RandomEnv


class DummyEnv(RandomEnv):

    def step(self, obs):
        while True:
            continue


conf = rllib.agents.ppo.DEFAULT_CONFIG.copy()
conf['env'] = DummyEnv

tune.run(
        rllib.agents.ppo.PPOTrainer,
        config=conf
    )

```

Run that with the debugger from within VSCodium and then click that nice juicy disconnect button up top because you realized your gym env is messed up and stuck in a loop.

```bash
>ps -aux | grep ray:                                     
myuser    23820  1.6  1.5 13424408 510184 pts/3 Sl   16:26   0:04 ray::PPO.train()
myuser    23821  0.5  0.1 8117500 62816 pts/3   Sl   16:26   0:01 ray::IDLE
myuser    23822  0.4  0.1 8117500 62892 pts/3   Sl   16:26   0:01 ray::IDLE
myuser    23823  0.4  0.1 8117492 62648 pts/3   Sl   16:26   0:01 ray::IDLE
myuser    23824  0.5  0.1 8117492 62716 pts/3   Sl   16:26   0:01 ray::IDLE
myuser    23825  0.4  0.1 8117492 62432 pts/3   Sl   16:26   0:01 ray::IDLE
myuser    23826  0.4  0.1 8117492 62408 pts/3   Sl   16:26   0:01 ray::IDLE
myuser    23827  0.4  0.1 8117492 62784 pts/3   Sl   16:26   0:01 ray::IDLE
myuser    23828  0.4  0.1 8117492 62780 pts/3   Sl   16:26   0:01 ray::IDLE
myuser    23829  0.4  0.1 8117492 62800 pts/3   Sl   16:26   0:01 ray::IDLE
myuser    23830  0.4  0.1 8117492 62428 pts/3   Sl   16:26   0:01 ray::IDLE
myuser    23831  0.4  0.1 8117492 62888 pts/3   Sl   16:26   0:01 ray::IDLE
myuser    23832 98.8  1.4 12063172 474880 pts/3 Rl   16:26   4:10 ray::RolloutWorker.par_iter_next()
myuser    23833  0.4  0.1 8117516 62516 pts/3   Sl   16:26   0:01 ray::IDLE
myuser    23834 98.8  1.4 12063236 474352 pts/3 Rl   16:26   4:09 ray::RolloutWorker.par_iter_next()
myuser    23835  0.4  0.1 8117492 62716 pts/3   Sl   16:26   0:01 ray::IDLE
```

**Comment by kivo360** [comment]
Same issue. Not only with tune.

**Comment by Linlinzhao** [comment]
How to kill those idle processes? I used Ray to parallelize nested for loops, now tons of IDLE processes are remaining on the remote.

**Comment by KaleabTessera** [comment]
Hack for now `ps aux | grep ray::IDLE | grep -v grep | awk '{print $2}' | xargs kill -9`

**Comment by mcrowson** [comment]
Yea that is what I've been doing, just seems like the wrong long term solution.

**Comment by duburcqa** [comment]
I have the same issue, but including some rollout workers and other stuffs, and it is even allocating part of the RAM. I would like to have a simple, cross-platform way to kill them all.

**Comment by DonYum** [comment]
This has confused me for some days. `kill pid` can only apply on one node...
And why this issue's priority is just `P3`? @rkooo567

**Comment by rkooo567** [comment]
Hmm, maybe we can revisit this. It looks like many people seem to have the same issue.

To be clear, did I understand this issue correctly?

- Start a driver
- Kill a driver using IDE 
- There are leak processes?

Is this correct?

**Comment by rokrokss** [comment]
In my case,
- Start a driver
- do ray.data.read_parquet().to_modin()
- ray.shutdown
- There are leak "ray:IDLE" processes

**Comment by krfricke** [comment]
cc @rkooo567 is this still tracked? Can I assign this to you or someone else from core? (it currently shows up as Ray Tune issue which it apparently is not)

**Comment by mimoralea** [comment]
You can always do `ray stop --force`.

**Comment by rkooo567** [comment]
@krfricke it is not tracked right now. Do you have a repro btw?

**Comment by kcmrt** [comment]
hi , i hava same problem issue too. 
Although the job is finished, the processes are still running and i dont want to use script that kills to process.
do u have any solution ?

**Comment by rkooo567** [comment]
@muratkoc93 is it possible for you to share the reproduction script? We will fix the issue, and having more repro script will help us fixing issue quickly. If there are IDLE processes not cleaned up after the job is terminated, it is a bug

**Comment by cadedaniel** [comment]
I'm not able to reproduce this. Does anyone have a repro script? Else I think we should close.

I tried with VSCode 1.74.2, Ray 2.1.0. I created the following Ray Tune script and entered debugging mode, then killed it with KeyboardInterrupt (cmd+c). I saw the IDLE processes come into existence and then immediately go away. I tried for both local mode and with Ray running on my machine (`ray start --head`).

```
#!/usr/bin/env python3

from ray import tune

def to_debug(*args):
    import time
    i = 0
    while True:
        print('iter', i)
        time.sleep(1)
        i += 1

tune.run(to_debug)
```

```
while true; do echo 'checking..' ; ps aux | grep 'IDL[E]'; sleep 1; done
```

**Comment by cadedaniel** [comment]
It looks like we fixed a bug where workloads with Ray Datasets would leak IDLE processes due to a leaked reference to a stats actor. This is fixed in https://github.com/ray-project/ray/issues/22154. It could be that the observed leaking was due to this..

I will close for now, if someone has a repro script happy to fix

cc @muratkoc93 @rkooo567

**Comment by mjlbach** [comment]
I still see this issue on the latest ray release (ray-2.3.0) @cadedaniel. I'll try to get a reliable reproduction.

**Comment by rkooo567** [comment]
Please reopen the issue once you find the repro!

**Comment by claysmyth** [comment]
Same issue! Any updates on a solution?

**Comment by cadedaniel** [comment]
@claysmyth do you have a repro? We want to fix this!

**Comment by claysmyth** [comment]
@cadedaniel My issue may have been a false alarm actually. My VSCode crashed while running a jupyter notebook utilizing ray remote. I then forced logged out. I think what actually happened is that having ray remotes idle kept the jupyter notebook server running, even after logging out. Once I found and killed the jupyter notebook, the ray remotes also were killed. 

However, I'll do some digging and report back if I find anything strange. Thanks!

**Comment by dss010101** [comment]
i see a ton of these when working remotely w/ vscode (in a devcontainer)

**Comment by rkooo567** [comment]
@dss010101 can you provide a repro script?

**Comment by dss010101** [comment]
> @dss010101 can you provide a repro script?

i will try to come up with one...but basically
1. create a vscode devcontainer (i use an amazon 2023 api w/ python 3.11 installed)
2. run remotely from windows to a linux box -> your container/dev environment should be running on the linux box
3. build a simple flask app and just do ray.init() on start up 
4. run the flask project
5. kill the python process (i do so my killing from the vscode terminal window)
6. if you do a ps -ef| grep 'ray' you probably will see a number of defunct/dangling processes over time depending on many times you repeat steps 4 & 5

**Comment by josomir** [comment]
Has there been any solution to this issue? I still see leaking ray:IDLEs, especially after version 2.11.0

**Comment by ycli12** [comment]
https://discuss.ray.io/t/why-ray-have-memory-leakage-issue-after-complex-tasks-with-modin/20890
I also got the same problem and release memory by killing the idel worker
